import type { AudienceItem } from "./audiences";

export const audiencesNl: AudienceItem[] = [
  {
    slug: "gemeenteleden",
    cluster: "geestelijk",
    status: "kernlijn",
    name: "Gemeenteleden & christenen",
    shortName: "Gemeenteleden",
    proposition: "Vind niet zomaar een rol in de gemeente — vind de plek waar je tot bloei komt.",
    heroTitle: "Ontdek de plek die God specifiek voor jou bedoeld heeft",
    heroSubtitle:
      "Door je gaven en je unieke functie helder te krijgen, vind je niet zomaar een rol in de gemeente — je vindt de plek waar je tot bloei komt.",
    ctaLabel: "Plan een vrijblijvend kennismakingsgesprek",
    intro:
      "JANE is een coachingstraject dat ontwikkeld is voor christenen die meer willen dan 'iets doen' in hun gemeente. Het is geen persoonlijkheidstest en geen pastorale begeleiding — het is een gestructureerd inzichtsinstrument dat je laat zien welke geestelijke functie God in jou heeft gelegd, en hoe je daar vanuit kunt leven en dienen.",
    recognition: [
      "Je doet al jaren iets in de gemeente, maar voelt je er niet écht thuis in.",
      "Anderen zien jou anders dan jij jezelf ziet — en je vraagt je af welk beeld klopt.",
      "Je hebt het gevoel dat je gaven nog onontdekt zijn, of dat ze niet worden gezien.",
      "Je wilt dienen vanuit wie je bent, niet vanuit wat er nodig blijkt.",
    ],
    whatJaneDoes: [
      { title: "Inzicht in je geestelijke gaven.", body: "Aan de hand van de 35 gaventeksten en de vijfvoudige bediening (Apostel, Profeet, Evangelist, Herder, Leraar) ontdek je welke gaven specifiek bij jou horen." },
      { title: "Helderheid over je unieke functie.", body: "Uit de 27 Jane-functies krijg je een persoonlijk profiel — niet één type-aanduiding maar een combinatie die specifiek is voor jou." },
      { title: "Herkenning van wat je tegenhoudt.", body: "De drie-stappen-workshop legt bloot welk gedrag je onbewust inzet om je echte bestemming uit de weg te gaan: je 'compensatietalent' en je 'blinde vlek'." },
      { title: "Een persoonlijk Jane-diagram.", body: "Aan het einde van het traject heb je een visuele samenvatting (Jane-diagram) waar je in je gemeentelijke en persoonlijke leven mee verder kunt." },
    ],
    traject: [
      { step: "1", title: "Intake-gesprek", duration: "1 uur", what: "Vrijblijvend kennismakingsgesprek waarin we kijken of JANE bij jou past en welke vragen voor jou centraal staan." },
      { step: "2", title: "Stap 1 — Wie ben ik niet", duration: "1,5 uur + thuiswerk", what: "We bakenen contouren af door te bepalen welke functies en gedragingen niet bij jou horen. Vaak verrassend bevrijdend." },
      { step: "3", title: "Stap 2 — Wie ben ik wel", duration: "1,5 uur + thuiswerk", what: "We identificeren jouw kernfuncties uit de set van 27 en koppelen die aan de gaventeksten." },
      { step: "4", title: "Stap 3 — Wat houdt me tegen", duration: "1,5 uur + thuiswerk", what: "De diepste stap: ontdek je blinde vlek en het compensatiegedrag dat je inzet om die te verbergen — voor jezelf en voor anderen." },
      { step: "5", title: "Afronding & Jane-diagram", duration: "1 uur", what: "Persoonlijk diagram, terugkoppeling naar je gemeente, en concrete vervolgstappen." },
      { step: "6", title: "Optionele follow-up", duration: "Na 3 maanden", what: "Eén vervolgsessie om te kijken hoe de inzichten in de praktijk landen." },
    ],
    forWhomYes: [
      "Je actief deel bent van een gemeente, of dat wilt worden.",
      "Je openstaat voor zelfreflectie en eerlijk wilt kijken naar gedrag dat je herkent.",
      "Je bereid bent tussen sessies door thuis te werken aan opdrachten.",
      "Je wilt groeien in dienen vanuit wie je bent, niet vanuit wat er gevraagd wordt.",
    ],
    forWhomNo: [
      "Je zoekt een quick fix of een snelle test.",
      "Je bent op dit moment in een acute crisis — daar past eerst pastorale of professionele zorg.",
      "Je staat niet open voor geestelijke duiding van je leven.",
    ],
    method:
      "De JANE-methode is in ruim twee decennia ontwikkeld door Dirk van der Schaaf en ingezet bij honderden mensen binnen gemeentes als VEG Bennekom, PG Wassenaar, Familiekerk De Fakkel, Pinkstergemeente Alkmaar en Alphakerk. De methode is voor de VPE-koepel gebruikt als pilot-traject voor gemeenteleiders en is breed inzetbaar over denominaties heen.",
    faq: [
      { q: "Is dit een psychologische test?", a: "Nee. JANE is een geestelijk inzichtsinstrument dat reflectie en uitkomst combineert. Het is niet wetenschappelijk gevalideerd als persoonlijkheidstest, maar in de praktijk bij honderden mensen ingezet en herkenbaar bevonden." },
      { q: "Heb ik er iets aan als ik niet uit een evangelische gemeente kom?", a: "Ja. De methode is ontwikkeld vanuit de evangelische/charismatische traditie, maar werkt breed over denominaties heen. De geestelijke laag (gaven, vijfvoudige bediening) wordt zo aangereikt dat je er met je eigen achtergrond mee uit de voeten kunt." },
      { q: "Hoe lang duurt het hele traject?", a: "Doorgaans 6 tot 8 weken, met sessies van anderhalf uur en thuiswerk daartussen. Het tempo wordt afgestemd op jouw situatie." },
      { q: "Wat als ik geen 'spectaculaire' gaven blijk te hebben?", a: "Dat overkomt vrijwel iedereen die deze gedachte heeft. JANE laat zien dat de 27 functies van gelijke waarde zijn — en dat de 'onzichtbare' gaven (zoals helpen, ondersteunen, gastvrij zijn) vaak het gemeentewerk dragen." },
      { q: "Wat kost een traject?", a: "Neem contact op voor een actueel tarief. We werken met staffeling voor jongeren, studenten en gemeenteleden zonder eigen inkomen." },
    ],
    closingTitle: "Een laatste stap",
    closingText:
      "Klaar om te ontdekken wat God specifiek voor jou heeft bedoeld? Plan een vrijblijvend kennismakingsgesprek van 30 minuten — daarna kies jij of het traject bij je past. Geen verplichting. Geen verkoop. Een eerste verkenning.",
  },
  {
    slug: "voorgangers",
    cluster: "geestelijk",
    status: "kernlijn",
    name: "Voorgangers & kerkleiders",
    shortName: "Voorgangers",
    proposition: "Voor voorgangers, oudsten en kerkleiders die scherper willen zien welke functie van hen is — en welk gedrag onbewust hun gemeente belast.",
    heroTitle: "Leid vanuit je kern, niet vanuit je vermoeidheid",
    heroSubtitle: "Voor voorgangers, oudsten en kerkleiders die scherper willen zien welke functie van hen is — en welk gedrag onbewust hun gemeente belast.",
    ctaLabel: "Plan een vertrouwelijk verkennend gesprek",
    intro: "Voorganger zijn is geen functie maar een verzameling rollen die in de loop der jaren over je heen worden gelegd: predikant, pastor, leider, organisator, bemiddelaar, soms ook nog manager. JANE helpt je terugbrengen wat van jou is, en herkennen welk gedrag je inzet om de rest staande te houden — gedrag dat vaak meer kost dan het oplevert.",
    recognition: [
      "Je herkent dat je iets doet 'omdat het moet' terwijl je er innerlijk niet bij bent.",
      "Je ziet patronen in je werk waarin je vastloopt, maar je vindt geen taal om er met collega's over te praten.",
      "Je hebt het gevoel dat de gemeente meer ziet van je rol dan van wie je werkelijk bent.",
      "Je voelt vermoeidheid die niet weggaat met een week vakantie.",
    ],
    whatJaneDoes: [
      { title: "Onderscheid maken tussen je functie en je rol.", body: "JANE legt bloot welke van de 27 functies écht in jou zit — los van wat de gemeente of je traditie van een voorganger verwacht." },
      { title: "Herkenning van de blinde vlek.", body: "Voor voorgangers is stap 3 — de compensatie-analyse — vaak de meest waardevolle. Het gedrag dat je inzet om je 'rol' staande te houden, raakt onvermijdelijk je gemeente." },
      { title: "Positionering binnen de vijfvoudige bediening.", body: "Ben je Apostel, Profeet, Evangelist, Herder of Leraar — of een specifieke combinatie? Dit kader helpt je bewuster prioriteren." },
      { title: "Een traject in volledige vertrouwelijkheid.", body: "Anders dan een gemeentebreed traject is dit één-op-één en discreet. Geen rapportage aan de kerkenraad, geen oordeel — alleen jouw helderheid." },
    ],
    traject: [
      { step: "1", title: "Vertrouwelijk verkenningsgesprek", duration: "1 uur", what: "We kijken of het traject past, welke vragen voor jou spelen, en hoe we de vertrouwelijkheid borgen." },
      { step: "2", title: "Stap 1 — Wie ben ik niet", duration: "1,5 uur + thuiswerk", what: "We benoemen de rollen die je vervult maar die niet wezenlijk van jou zijn — vaak een lijst die langer is dan verwacht." },
      { step: "3", title: "Stap 2 — Wie ben ik wel", duration: "1,5 uur + thuiswerk", what: "Identificatie van je kernfuncties uit de 27 en je positie in de vijfvoudige bediening." },
      { step: "4", title: "Stap 3 — Wat houdt me tegen", duration: "2 uur + thuiswerk", what: "Diepgaande analyse van je compensatiegedrag, met aandacht voor het effect op je gemeente." },
      { step: "5", title: "Afronding & vervolgkeuzes", duration: "1,5 uur", what: "Persoonlijk diagram, gespreksleidraad voor je oudstenteam (alleen als jij dat wilt), en concrete vervolgstappen." },
      { step: "6", title: "Maandelijkse begeleiding", duration: "6–12 maanden", what: "Optioneel: lichte coaching gedurende 6 tot 12 maanden om de inzichten te verankeren." },
    ],
    forWhomYes: [
      "Je bent voorganger, oudste, voorzitter van de oudstenraad of in een vergelijkbare leiderschapsrol.",
      "Je staat open voor diep kijken naar eigen patronen — ook als die confronterend zijn.",
      "Je bent bereid om in de tweede helft van het traject keuzes te maken die je rol kunnen veranderen.",
    ],
    forWhomNo: [
      "Je zit middenin een conflict in de gemeente — bemiddel dat eerst af.",
      "Je zoekt een formele beoordeling van je functioneren als voorganger.",
      "Je bent niet bereid om vertrouwelijke inzichten serieus te wegen.",
    ],
    method: "JANE wordt sinds 2008 ingezet voor voorgangers, beginnend met de VPE-pilot 'Jane instrumenten voor gemeenteleiders'. Het meest uitgewerkte coaching-dossier is dat van een voorganger (gepubliceerd met toestemming als anonieme casus). De methode is geschikt voor pinkster-, evangelische, vrije evangelische en reformatorische voorgangers — overal waar leiderschap en geestelijke bediening samenkomen.",
    faq: [
      { q: "Hoort mijn kerkenraad of oudstenteam dit te weten?", a: "Niet noodzakelijk. Dit is een persoonlijk traject met volledige vertrouwelijkheid. Of en hoe je inzichten deelt is jouw keuze." },
      { q: "Is dit niet hetzelfde als een sabbatical?", a: "Nee. Een sabbatical is afstand nemen; JANE is inzicht krijgen. Een combinatie kan effectief zijn — een sabbatical met een JANE-traject in de eerste maanden ervan." },
      { q: "Hoeveel tijd kost het naast mijn gewone werk?", a: "Reken op ongeveer 4–6 uur per maand: anderhalf uur sessie + 2–4 uur thuiswerk. Het traject loopt 4–6 maanden afhankelijk van tempo." },
      { q: "Werkt dit ook voor jongere voorgangers of net beginnende?", a: "Ja, en vaak juist gunstig: hoe vroeger in je bediening, hoe minder geconsolideerd het compensatiegedrag." },
    ],
    closingTitle: "Een laatste stap",
    closingText: "Een eerlijk gesprek over wat van jou is en wat niet, kost je een uur. Plan een vertrouwelijk verkennend gesprek — geen verplichting, geen rapportage, geen oordeel.",
  },
  {
    slug: "jongeren-studiekeuze",
    cluster: "ontwikkeling",
    status: "slapend",
    name: "Jongeren & studiekeuze",
    shortName: "Jongeren",
    proposition: "Voor jongeren tussen 16 en 25 die studie- of werkkeuzes moeten maken, en meer willen dan een test die ze een 'profiel' opplakt.",
    heroTitle: "Niet welk vak past — maar welke jij past",
    heroSubtitle: "Voor jongeren tussen 16 en 25 die studie- of werkkeuzes moeten maken, en meer willen dan een test die ze een 'profiel' opplakt.",
    ctaLabel: "Plan een kennismaking voor jou en je ouder(s)",
    intro: "Een standaard studiekeuzetest deelt je in een hokje. JANE doet iets fundamenteel anders: het laat zien welke functie en gaven werkelijk in jou zitten, en helpt je daar een richting bij te kiezen — in plaats van een richting te kiezen waar je 'in zou moeten passen'.",
    recognition: [
      "Je moet straks een studie kiezen en de lijst lijkt willekeurig.",
      "Iedereen om je heen heeft 'het al door' en jij voelt je achter.",
      "Je hebt al een paar tests gedaan, maar de uitkomsten zeggen niets persoonlijks.",
      "Je twijfelt of je voor het verstandige moet kiezen of voor wat écht bij je hoort.",
    ],
    whatJaneDoes: [
      { title: "Een richting in plaats van een hokje.", body: "Geen profielcode, maar een persoonlijke beschrijving van welke functies en gaven in jou werken — zodat je begrijpt waarom sommige dingen je energie geven en andere niet." },
      { title: "Inzicht waarom bepaalde keuzes terugkomen.", body: "Veel jongeren herkennen 'hetzelfde patroon' in vrienden, hobby's, bijbaantjes. JANE legt bloot waarom dat patroon erbij hoort." },
      { title: "Een gesprek tussen jou en je ouders.", body: "Optioneel maar veelgevraagd: de uitkomsten delen met je ouders, zodat zij begrijpen waarom een 'verstandige' keuze niet altijd de juiste is — of juist wél." },
      { title: "Een persoonlijk Jane-diagram.", body: "Een visuele samenvatting die je later in je studie of werk kunt blijven gebruiken." },
    ],
    traject: [
      { step: "1", title: "Kennismaking", duration: "45 min", what: "Vrijblijvend gesprek, eventueel met ouder(s) erbij, om te kijken of JANE bij jou past." },
      { step: "2", title: "Stap 1 — Wat ben ik niet", duration: "1 uur + thuiswerk", what: "Aangepaste, visuele opdracht: welke dingen krijgen je echt niet aan de praat?" },
      { step: "3", title: "Stap 2 — Wat ben ik wel", duration: "1 uur + thuiswerk", what: "Identificatie van jouw kernfuncties en talenten — vertaald naar studie- en werkvelden." },
      { step: "4", title: "Stap 3 — Wat houdt me tegen", duration: "1 uur + thuiswerk", what: "Welke patronen herken je waardoor je toch tegen jezelf in keuzes maakt?" },
      { step: "5", title: "Afronding + gesprek met ouders", duration: "1,5 uur", what: "Persoonlijk diagram en richting-advies. Optioneel: gezamenlijk gesprek met je ouders." },
    ],
    forWhomYes: [
      "Je bent tussen 16 en 25 en staat voor een studie-, werk- of richtingkeuze.",
      "Je wilt dieper kijken dan een online test.",
      "Je staat open voor reflectie — ook al voelt dat soms ongemakkelijk.",
      "Je ouders steunen je in dit traject, of jij hebt zelf de regie.",
    ],
    forWhomNo: [
      "Je hebt geen ruimte om een paar weken aan jezelf te besteden.",
      "Je wilt vooral een snelle uitkomst, geen reflectie.",
      "Je bent op dit moment in een mentale crisis — daar past eerst andere zorg.",
    ],
    method: "JANE wordt sinds 2009 ook toegepast op jongeren, oorspronkelijk via gemeente-jongerenwerkers. De methode is in vereenvoudigde vorm beschikbaar gemaakt om aan te sluiten bij het taalveld en de levensvragen van jongeren — zonder de inhoudelijke diepte van het volwassen traject te verliezen.",
    faq: [
      { q: "Wat als ik geen idee heb wat ik wil?", a: "Dat is juist het beginpunt. JANE werkt niet via 'wat wil je', maar via 'wie ben je' — en uit dat tweede ontstaat vanzelf richting." },
      { q: "Mogen mijn ouders erbij zijn?", a: "Bij de kennismaking en de afronding kan dat goed werken. De tussenstappen doe je op je eigen kracht; dat is de bedoeling." },
      { q: "Werkt dit ook als ik nergens 'in zit' qua geloof?", a: "Ja. De spirituele laag (gaventeksten) kunnen we in afstemming met jou wel of niet meenemen — JANE werkt ook puur op de functie-laag." },
      { q: "Hoe lang duurt het?", a: "Doorgaans 4 tot 6 weken." },
    ],
    closingTitle: "Een laatste stap",
    closingText: "Een goede keuze begint bij weten wie je bent — niet bij een lijst opleidingen. Plan een vrijblijvende kennismaking, eventueel samen met je ouder(s).",
  },
  {
    slug: "loopbaantransitie",
    cluster: "ontwikkeling",
    status: "kernlijn",
    name: "Loopbaantransitie",
    shortName: "Loopbaan",
    proposition: "Voor professionals die vastlopen, herstellen van burn-out, of voelen dat ze de verkeerde afslag hebben genomen — en geen zin hebben in een nieuwe ronde met dezelfde patronen.",
    heroTitle: "Voor wie meer wil dan opnieuw beginnen",
    heroSubtitle: "Voor professionals die vastlopen, herstellen van burn-out, of voelen dat ze de verkeerde afslag hebben genomen — en geen zin hebben in een nieuwe ronde met dezelfde patronen.",
    ctaLabel: "Plan een intake-gesprek",
    intro: "Bij een loopbaanvraag heb je twee opties: een nieuwe baan zoeken die misschien dezelfde patronen herhaalt, of dieper kijken naar wat onder die patronen zit. JANE biedt dat tweede. Het is geen werkmethodiek, geen LinkedIn-strategie, maar een fundamenteel inzicht in welke functie en welke valkuilen jou maken — zodat je vervolgens met andere ogen naar werk kijkt.",
    recognition: [
      "Je hebt al twee of drie banen achter elkaar gehad die op iets vergelijkbaars stukliepen.",
      "Je herstelt van een burn-out en wilt niet weer in dezelfde val trappen.",
      "Je vraagt je af waarom je zoveel energie kwijt bent aan dingen die er eigenlijk goed uit moeten zien.",
      "Je hebt het gevoel dat de loopbaancoaches tot nu toe vooral CV-advies gaven, niet zelfkennis.",
    ],
    whatJaneDoes: [
      { title: "Een diagnose, geen sollicitatietraining.", body: "JANE start niet bij 'wat zou ik kunnen' maar bij 'wat ben ik' — een onderscheid dat het verschil maakt tussen een herhaling van patronen en een wezenlijke verandering." },
      { title: "Inzicht in patronen die meereizen tussen banen.", body: "Stap 3 (blinde vlek / compensatietalent) legt bloot waarom hetzelfde gedrag steeds terugkomt — onafhankelijk van welke werkgever je hebt." },
      { title: "Vertaling naar concrete loopbaankeuzes.", body: "Uit het traject volgt een Jane-diagram dat direct gekoppeld wordt aan werkvelden, rollen en arbeidsverhoudingen die werkelijk bij jou passen." },
      { title: "Een fundament voor vervolggesprekken.", body: "Veel cliënten gebruiken het Jane-diagram later in gesprekken met loopbaancoaches, headhunters of leidinggevenden — als gemeenschappelijke taal." },
    ],
    traject: [
      { step: "1", title: "Intake-gesprek", duration: "1 uur", what: "Kennismaking, scope-bepaling en helder krijgen van jouw centrale vraag." },
      { step: "2", title: "Stap 1 — Wie ben ik niet", duration: "1,5 uur + thuiswerk", what: "Welke functies en rollen heb je vervuld die niet bij je hoorden — en wat kostte dat je?" },
      { step: "3", title: "Stap 2 — Wie ben ik wel", duration: "1,5 uur + thuiswerk", what: "Identificatie van je kernfuncties met directe loopbaan-vertaling." },
      { step: "4", title: "Stap 3 — Wat houdt me tegen", duration: "2 uur + thuiswerk", what: "De patronen die je meebracht naar elke baan, en waarom ze terugkomen." },
      { step: "5", title: "Loopbaanvertaling", duration: "1,5 uur", what: "Jane-diagram + concrete loopbaanrichtingen + bespreking met je netwerk-omgeving." },
      { step: "6", title: "Follow-up na 3 en 6 maanden", duration: "2 × 1 uur", what: "Check-in om te kijken hoe de inzichten in nieuwe werksituatie landen." },
    ],
    forWhomYes: [
      "Je staat voor een loopbaankeuze of komt uit een burn-out.",
      "Je hebt al wat zelfreflectie achter de rug en wilt nu een stap dieper.",
      "Je hebt ruimte (mentaal en financieel) om 2–3 maanden aan jezelf te besteden.",
      "Je bent bereid om antwoorden te krijgen die wezenlijk anders zijn dan je verwachtte.",
    ],
    forWhomNo: [
      "Je hebt vooral CV-advies of sollicitatietraining nodig.",
      "Je wilt binnen een paar weken een nieuwe baan, geen reflectie.",
      "Je bent nog niet voldoende hersteld van uitval — wacht hier nog even mee.",
    ],
    method: "JANE is sinds 2010 expliciet toegepast op loopbaanvragen, met een eigen submap aan presentatiemateriaal binnen de methodiek (8 documenten 'Loopbaan'). Cliënten variëren van mid-career professionals die heroriënteren tot leidinggevenden na een ontslag of burn-out. Cliënten gebruiken het Jane-diagram vaak nog jaren na het traject als referentiepunt.",
    faq: [
      { q: "Is dit niet hetzelfde als een outplacement-traject?", a: "Nee. Outplacement is gericht op een nieuwe baan binnen een korte termijn. JANE gaat eerst dieper, en levert daarna juist de basis op waarmee outplacement effectiever wordt." },
      { q: "Werkt JANE samen met mijn werkgever, of is dit volledig persoonlijk?", a: "Standaard volledig persoonlijk en vertrouwelijk. In sommige gevallen kan een werkgever (of UWV) een traject vergoeden — dat is alleen op jouw initiatief en in afstemming." },
      { q: "Wat als de uitkomst is dat ik beter zelfstandig kan worden?", a: "Dat overkomt regelmatig. JANE laat zien wat in jou werkt — wat je daar in arbeidsverhouding van maakt, is jouw keuze." },
      { q: "Hoe lang duurt het?", a: "8–12 weken voor het kerntraject, plus follow-ups op 3 en 6 maanden." },
    ],
    closingTitle: "Een laatste stap",
    closingText: "Een loopbaanvraag verdient meer dan een lijst vacatures. Plan een intake-gesprek en ontdek wat het verschil maakt — voor jezelf en voor je volgende stap.",
  },
  {
    slug: "managers",
    cluster: "zakelijk",
    status: "kernlijn",
    name: "Managers & leidinggevenden",
    shortName: "Managers",
    proposition: "Voor leidinggevenden die voelen dat hun aangeleerde stijl niet meer past, of die merken dat hun blinde vlek hun team raakt.",
    heroTitle: "Leid je team vanuit wie je bent — niet vanuit wat je als manager geleerd hebt",
    heroSubtitle: "Voor leidinggevenden die voelen dat hun aangeleerde stijl niet meer past, of die merken dat hun blinde vlek hun team raakt.",
    ctaLabel: "Plan een vertrouwelijk gesprek",
    intro: "De meeste leiderschapstrainingen voegen iets toe: meer vaardigheden, meer modellen, meer feedback. JANE doet het omgekeerde — het haalt eraf wat niet van jou is. Wat overblijft is je eigen leiderschapsfunctie, helder gepositioneerd en bewust van de patronen die je nu nog blokkeren.",
    recognition: [
      "Je hebt een leiderschapsopleiding gehad maar past de modellen niet werkelijk toe.",
      "Je herkent dat je in stress terugvalt op gedrag waarvan je weet dat het niet werkt.",
      "Je team functioneert goed, maar jij vermoedt dat er meer in zit als jij anders zou leiden.",
      "Je hebt het gevoel dat je 'manager-stijl' niet helemaal van jou is.",
    ],
    whatJaneDoes: [
      { title: "Onderscheid maken tussen jou en je rol.", body: "JANE laat zien welke functies van jou zijn (uit de 27) en welke je hebt aangeleerd omdat ze 'horen' bij management. Dat onderscheid is bevrijdend." },
      { title: "Inzicht in stress-patronen.", body: "Stap 3 legt bloot welk compensatiegedrag je inzet onder druk — en hoe dat je team beïnvloedt. Vaak het meest waardevolle inzicht van het traject." },
      { title: "Een leiderschapsstijl die natuurlijk werkt.", body: "In plaats van een 'beste stijl' krijg je jouw stijl: helder, herkenbaar, en bevestigd door wat in jou werkt." },
      { title: "Optioneel: een team-traject volgend.", body: "Veel managers nemen vervolgens hun directe rapporteurs mee in een team-traject (Team Life Statement) om de eigen inzichten te verankeren in de praktijk." },
    ],
    traject: [
      { step: "1", title: "Verkenningsgesprek", duration: "1 uur", what: "Vertrouwelijk gesprek, eventueel via je werkgever bekostigd of geheel privé." },
      { step: "2", title: "Stap 1 — Wie ben ik niet (als manager)", duration: "1,5 uur + thuiswerk", what: "Welke rollen vervul je die niet bij jou horen — en waar betaal je dat?" },
      { step: "3", title: "Stap 2 — Wie ben ik wel", duration: "1,5 uur + thuiswerk", what: "Identificatie van je kernfuncties, vertaald naar leiderschap." },
      { step: "4", title: "Stap 3 — Wat houdt me tegen", duration: "2 uur + thuiswerk", what: "Stress-patronen, compensatiegedrag, en impact op je team." },
      { step: "5", title: "Leiderschapsdiagram", duration: "1,5 uur", what: "Jane-diagram + actiepunten voor je rol als leidinggevende." },
      { step: "6", title: "Optioneel: team-traject", duration: "1 dag offsite", what: "Verlengstuk met je directe team — de Team Life Statement." },
    ],
    forWhomYes: [
      "Je hebt eindverantwoordelijkheid voor een team of afdeling.",
      "Je bent bereid om je eigen stijl te onderzoeken in plaats van die van je team.",
      "Je hebt ruimte voor een traject van 8–10 weken naast je werk.",
      "Je staat open voor inzichten die je leiderschap kunnen veranderen.",
    ],
    forWhomNo: [
      "Je zoekt vooral toolset-uitbreiding (modellen, frameworks).",
      "Je verwacht dat coaching je 'directe handvatten' geeft voor morgen.",
      "Je bent niet bereid om je eigen patronen serieus te bespreken.",
    ],
    method: "JANE wordt sinds 2010 ingezet voor managers via Jane Management Consultants, met materiaal als 'Unieke Bestemming Manager' en 'Jane ACT' (Adviseurs, Coaches en Trainers). Klanten variëren van MKB-directies tot middenmanagement in grotere organisaties. Trajecten worden vaak gevolgd door een Team Life Statement met het directe team.",
    faq: [
      { q: "Vergoedt mijn werkgever dit traject?", a: "Vaak wel, onder noemers als 'leiderschapsontwikkeling' of 'persoonlijke coaching'. We leveren desgewenst een nette offerte aan." },
      { q: "Is dit hetzelfde als executive coaching?", a: "Er zit overlap, maar JANE is methodischer en levert een concreter eindproduct (het diagram). Veel executive coaches verwijzen door voor het JANE-deel." },
      { q: "Werkt dit ook voor middenmanagers, niet alleen top?", a: "Ja, zelfs bijzonder goed. Middenmanagers zitten vaak in de zwaarste rol-onduidelijkheid, waar JANE het meest oplevert." },
      { q: "Wat als ik door het traject merk dat ik geen manager ben?", a: "Dat overkomt sommige cliënten. JANE helpt dan ook de gesprekken voorbereiden om je rol opnieuw vorm te geven." },
    ],
    closingTitle: "Een laatste stap",
    closingText: "Goede leiders kennen zichzelf scherp. Plan een vertrouwelijk verkenningsgesprek en kijk of JANE jouw volgende stap kan ondersteunen.",
  },
  {
    slug: "sales",
    cluster: "zakelijk",
    status: "kernlijn",
    name: "Sales-professionals",
    shortName: "Sales",
    proposition: "Voor sales-professionals die targets halen maar er energie aan kwijtraken, of die voelen dat hun rol langzaam niet meer bij hen past.",
    heroTitle: "Verkopen vanuit echtheid — niet vanuit een script",
    heroSubtitle: "Voor sales-professionals die targets halen maar er energie aan kwijtraken, of die voelen dat hun rol langzaam niet meer bij hen past.",
    ctaLabel: "Plan een sales-coaching intake",
    intro: "Verkoop is een vak waarin energie er sneller in en uit gaat dan in vrijwel elk ander beroep. JANE helpt sales-professionals onderscheid maken tussen de aangeleerde verkoopstijl — vaak vermoeiend, target-gedreven — en hun natuurlijke salesfunctie. Wat overblijft is een manier van verkopen die werkt voor langere termijn én voor jou persoonlijk.",
    recognition: [
      "Je haalt je cijfers maar voelt na elke quarter platter dan de vorige.",
      "Je hebt collega’s die het ‘natuurlijk’ lijken te doen — en je vermoedt dat zij iets weten dat jij niet door hebt.",
      "Je verkoopt graag, maar niet altijd zoals jouw aanpak je dat voorschrijft.",
      "Je hebt verschillende sales-trainingen gehad, maar geen ervan veranderde fundamenteel hoe je werkt.",
    ],
    whatJaneDoes: [
      { title: "Ontdek welke salesfunctie écht bij jou hoort.", body: "Niet elke sales-professional is een ‘hunter’ of een ‘farmer’. JANE laat zien welke combinatie van functies in jou werkt — vaak verrassend specifiek." },
      { title: "Herken welke compensatie energie kost.", body: "Stap 3 legt bloot welk gedrag je inzet om resultaten te halen tegen je eigen aard in — gedrag dat resultaat oplevert maar je leegtrekt." },
      { title: "Een aanpak die duurzaam werkt.", body: "Het traject levert geen nieuwe technieken op, maar inzicht waarmee je bestaande technieken bewuster inzet — sommige loslaat, andere intensiever benut." },
      { title: "Optioneel: een teamtraject voor het hele sales-team.", body: "Als je leidinggevende bent of als sales-team, kunnen we het traject collectief inrichten met een Team Life Statement." },
    ],
    traject: [
      { step: "1", title: "Intake", duration: "1 uur", what: "We bespreken jouw rol, jouw markt en wat je centrale vraag is." },
      { step: "2", title: "Stap 1 — Wat is geen verkoop voor jou", duration: "1,5 uur + thuiswerk", what: "Welke onderdelen van het sales-werk zitten je het meest in de weg?" },
      { step: "3", title: "Stap 2 — Wat is wel jouw verkoop", duration: "1,5 uur + thuiswerk", what: "Identificatie van je natuurlijke sales-functie binnen de 27 Jane-functies." },
      { step: "4", title: "Stap 3 — Wat trekt je leeg", duration: "2 uur + thuiswerk", what: "Patronen die je energie kosten — en hoe je ze herkent vóór ze toeslaan." },
      { step: "5", title: "Sales-diagram", duration: "1,5 uur", what: "Jane-diagram, vertaald naar concrete sales-actiepunten." },
    ],
    forWhomYes: [
      "Je werkt in een sales-rol (account, new business, channel, inside sales, etc.).",
      "Je haalt resultaten maar betaalt er meer voor dan je zou willen.",
      "Je bent bereid om je aanpak te onderzoeken, niet alleen je targets.",
    ],
    forWhomNo: [
      "Je zoekt vooral nieuwe sales-technieken of meer training.",
      "Je verwacht dat coaching je targets verhoogt zonder dat jij verandert.",
      "Je bent in een conflict met je leidinggevende over performance — los dat eerst af.",
    ],
    method: "Met materiaal als ‘Unieke Bestemming Sales 2011’ en cases zoals Alexport heeft JANE sales-professionals begeleid in zowel B2B als B2C, in MKB en grotere organisaties. Het sales-traject is methodisch identiek aan andere Jane-trajecten, maar de vertaling naar de praktijk gebeurt in sales-taal.",
    faq: [
      { q: "Werkt dit ook als ik werkzaam ben in pure B2B-sales (technisch, complex)?", a: "Ja, met name in complexe B2B-sales komt JANE goed tot z’n recht omdat daar de zelfsturing en het bouwen van vertrouwen — beide functie-gevoelig — een sterke rol spelen." },
      { q: "Wordt dit door mijn werkgever vergoed?", a: "Vaak wel, als ‘professionele ontwikkeling’ of ‘verkoop-coaching’. We leveren een offerte die past bij de gangbare HR-budgetten." },
      { q: "Hoe verhoudt dit zich tot Sandler / Spin / Challenger sales?", a: "JANE is geen sales-methodiek, maar een persoonlijk inzichtsinstrument. Deze methodieken zijn technieken; JANE bepaalt welke technieken bij jou werken." },
      { q: "Werkt dit ook voor sales-leidinggevenden?", a: "Ja, en vaak met extra waarde: een sales-manager met inzicht in de eigen functie kan dat doorzetten naar het team." },
    ],
    closingTitle: "Een laatste stap",
    closingText: "Sales doen vanuit kracht in plaats van vanuit script — dat is geen luxe maar een rendement. Plan een intake-gesprek en kijk wat het voor jou kan opleveren.",
  },
  {
    slug: "team-projectleiders",
    cluster: "zakelijk",
    status: "kernlijn",
    name: "Team- en projectleiders",
    shortName: "Teamleiders",
    proposition: "Voor team- en projectleiders die helderheid willen over welke leidersrol bij hen past.",
    heroTitle: "Anderen sturen begint bij jezelf kennen",
    heroSubtitle: "Voor team- en projectleiders in die wonderbaarlijke zone tussen meewerken, sturen en specialist zijn — en die helderheid willen over welke leidersrol bij hen past.",
    ctaLabel: "Plan een verkenningsgesprek",
    intro: "Team- en projectleiders zitten zelden in een eenduidige functie. Je werkt mee, je stuurt, je adviseert, je faciliteert — alles tegelijk, en vaak zonder formele leidinggevende positie. JANE helpt je deze rolverwarring ontwarren en bepaalt welke leiders-modus bij jou natuurlijk werkt.",
    recognition: [
      "Je bent technisch sterk maar voelt dat leidinggeven energie kost in plaats van dat het oplevert.",
      "Je micromanagement-reflex slaat aan onder druk, terwijl je weet dat het niet werkt.",
      "Je hebt geen formele macht over je team maar wel verantwoordelijkheid voor resultaten.",
      "Je vraagt je af of leidinggeven wel echt bij je past, of dat je beter expert kunt blijven.",
    ],
    whatJaneDoes: [
      { title: "Helderheid over je rol-mix.", body: "JANE legt bloot welke functies bij jou natuurlijk werken — meewerken, sturen, faciliteren, adviseren — en in welke verhouding." },
      { title: "Inzicht in stress-patronen.", body: "Wat doe je als project- of teamleider onder druk? Micromanagen, overnemen, juist loslaten? JANE laat zien waarom — en wat erbij hoort." },
      { title: "Onderscheid expert versus leider.", body: "Een belangrijk inzicht voor velen: ben je een leider die toevallig veel weet, of een expert die toevallig leiding geeft? Beide is valide, mits bewust." },
      { title: "Een diagram dat je in je team kunt delen.", body: "Anders dan bij sommige andere coaching-trajecten levert JANE een resultaat op dat je collega’s kunnen begrijpen — handig in matrixstructuren." },
    ],
    traject: [
      { step: "1", title: "Verkenningsgesprek", duration: "1 uur", what: "Wat is jouw rol, wat is je vraag, en past dit traject erbij." },
      { step: "2", title: "Stap 1 — Wat ben ik niet", duration: "1,5 uur + thuiswerk", what: "De stukken van je rol die niet van jou zijn." },
      { step: "3", title: "Stap 2 — Wat ben ik wel", duration: "1,5 uur + thuiswerk", what: "Identificatie van je natuurlijke leidersfuncties." },
      { step: "4", title: "Stap 3 — Wat houdt me tegen", duration: "2 uur + thuiswerk", what: "Stress-patronen, micromanagement-reflex, expert-trap." },
      { step: "5", title: "Leidersdiagram + actieplan", duration: "1,5 uur", what: "Concreet plan voor je rol in komende 6 maanden." },
    ],
    forWhomYes: [
      "Je leidt formeel of informeel een team of project.",
      "Je werkt vaak in een matrix-structuur of zonder duidelijke hiërarchie.",
      "Je bent bereid om je eigen patronen onder de loep te leggen.",
    ],
    forWhomNo: [
      "Je zoekt project management-training of -techniek.",
      "Je verwacht dat coaching je autoriteit bij je team verhoogt zonder dat jij verandert.",
    ],
    method: "Met ‘Unieke Bestemming Team- of Projectleider’ (2011) en de bredere materialen ‘Jane Adviseurs, Coaches en Trainers’ heeft JANE deze specifieke groep al meer dan tien jaar bediend. Cliënten zijn vaak technisch onderlegde professionals die in een leidende rol zijn gerold zonder daar bewust voor te kiezen.",
    faq: [
      { q: "Hoe verhoudt dit zich tot PRINCE2, Agile of Scrum-training?", a: "Methodologie-trainingen leren je hoe je een project of team aanstuurt. JANE laat zien hoe jij dat doet en welke patronen je daarbij meebrengt — complementair, niet vervangend." },
      { q: "Werkt dit ook voor scrum masters of agile coaches?", a: "Bijzonder goed. Hun rol is bij uitstek functie-gedreven en niet hiërarchisch — precies de context waarin JANE veel oplevert." },
      { q: "Hoe lang duurt het?", a: "Doorgaans 8–10 weken." },
    ],
    closingTitle: "Een laatste stap",
    closingText: "Een leider die zichzelf kent, hoeft niet hard te sturen om resultaat te halen. Plan een verkenningsgesprek en ontdek welke leidersfunctie van jou is.",
  },
  {
    slug: "echtparen",
    cluster: "relaties",
    status: "slapend",
    name: "Echtparen",
    shortName: "Echtparen",
    proposition: "Voor stellen die zichzelf en elkaar beter willen begrijpen — als individu én als duo. Geen relatietherapie, wel een dieper inzicht in jullie samenspel.",
    heroTitle: "Twee profielen, één relatie",
    heroSubtitle: "Voor stellen die zichzelf en elkaar beter willen begrijpen — als individu én als duo. Geen relatietherapie, wel een dieper inzicht in jullie samenspel.",
    ctaLabel: "Plan een kennismaking voor jullie samen",
    intro: "Stellen die langer samen zijn ontdekken vaak: ‘we maken hetzelfde gesprek nu al jaren’. JANE biedt geen oplossing daarvoor maar wel een nieuwe taal. Door beiden je eigen Jane-profiel te leren kennen, ontdek je hoe twee functies elkaar aanvullen — en hoe je elkaars blinde vlek triggert. Niet om iets op te lossen, maar om iets te begrijpen.",
    recognition: [
      "Jullie merken dat dezelfde discussies blijven terugkomen — met dezelfde rolverdeling.",
      "Wat jullie aan elkaar trok aan het begin, voelt nu soms juist als de bron van wrijving.",
      "Jullie willen jezelf beter begrijpen, zowel apart als samen.",
      "Jullie zoeken geen therapie maar wel diepgang.",
    ],
    whatJaneDoes: [
      { title: "Twee individuele Jane-profielen.", body: "Eerst werkt elk van jullie afzonderlijk een eigen traject af — zonder gedoe over de relatie. Dat geeft elk een vol persoonlijk diagram." },
      { title: "Dynamiek-analyse.", body: "Daarna kijken we hoe jullie twee profielen op elkaar inwerken: waar vullen jullie aan, waar staan jullie haaks, en hoe loopt dat in de praktijk." },
      { title: "Een gezamenlijk diagram.", body: "Het traject eindigt met een ‘koppeldiagram’ dat jullie samen visueel toont — handig om bewuster terug te kunnen kijken op gespreksdynamiek." },
      { title: "Gespreksopdrachten voor thuis.", body: "Tussen de sessies door werken jullie aan kleine, concrete oefeningen die de inzichten in de praktijk laten landen." },
    ],
    traject: [
      { step: "1", title: "Kennismaking samen", duration: "1 uur", what: "Beide partners aanwezig. Verkenning van de vraag en de werkwijze." },
      { step: "2", title: "Individueel traject — partner 1", duration: "3–4 sessies", what: "Drie-stappen-workshop, geheel persoonlijk." },
      { step: "3", title: "Individueel traject — partner 2", duration: "3–4 sessies", what: "Idem voor de andere partner. Kan parallel of volgordelijk." },
      { step: "4", title: "Dynamiek-sessie 1", duration: "1,5 uur", what: "We leggen de twee profielen naast elkaar en bespreken aanvullingen en spanningen." },
      { step: "5", title: "Dynamiek-sessie 2", duration: "1,5 uur", what: "Vertaling naar concrete situaties in jullie relatie." },
      { step: "6", title: "Afronding", duration: "1 uur", what: "Koppeldiagram + adviezen voor verankering." },
    ],
    forWhomYes: [
      "Jullie zijn samen, niet (op dit moment) in scheidingstraject.",
      "Beide partners willen meedoen, niet één onder druk van de ander.",
      "Jullie zoeken inzicht, geen probleemoplossing.",
    ],
    forWhomNo: [
      "Er speelt acute relatiecrisis of vertrouwensbreuk — daar past eerst relatietherapie.",
      "Eén van beiden is sceptisch of doet alleen mee om de ander tegemoet te komen.",
      "Jullie verwachten een vastomlijnde uitkomst over of jullie ‘bij elkaar passen’.",
    ],
    method: "Echtparen-trajecten zijn een groei-lijn binnen JANE. De methode zelf is bewezen op individueel niveau bij honderden cliënten; de koppel-toepassing wordt selectief aangeboden en bij vraag verder uitgebouwd. Vraag bij intake naar de meest recente cases.",
    faq: [
      { q: "Is dit therapie?", a: "Nee. Dit is een inzichtstraject. Als er onderliggende problematiek speelt die therapie vraagt, verwijzen we door." },
      { q: "Kunnen we dit doen zonder dat we elkaars uitkomsten delen?", a: "Het individuele deel blijft tussen jou en de coach. Tijdens de dynamiek-sessies delen jullie wat jullie zelf willen delen — niets is verplicht." },
      { q: "Hoe lang duurt het hele traject?", a: "Met twee parallelle persoonlijke trajecten plus de twee koppelsessies kom je op 12–16 weken." },
      { q: "Werkt dit ook voor LGBTQ+-stellen?", a: "Ja. De Jane-methodiek is functie-gericht en daarmee niet bedingd door geslacht of relatievorm." },
    ],
    closingTitle: "Een laatste stap",
    closingText: "Een relatie wordt niet beter door over de relatie te praten — soms wordt ze beter door over jezelf te praten. Plan een vrijblijvende kennismaking samen.",
  },
  {
    slug: "kleine-groepen",
    cluster: "relaties",
    status: "slapend",
    name: "Kleine groepen",
    shortName: "Kleine groepen",
    proposition: "Voor huiskringen, vriendengroepen of kleine teams die elkaars gaven willen leren kennen — en willen begrijpen waarom de groep doet wat hij doet.",
    heroTitle: "Een groep die elkaars functie kent, werkt anders",
    heroSubtitle: "Voor huiskringen, vriendengroepen of kleine teams die elkaars gaven willen leren kennen — en willen begrijpen waarom de groep doet wat hij doet.",
    ctaLabel: "Plan een mini-workshop voor jullie groep",
    intro: "In elke kleine groep ontstaat een eigen dynamiek: één neemt automatisch de gespreksleiding, één faciliteert, één is altijd de twijfelaar, één regelt de praktische dingen. Vaak gebeurt dat onbewust — soms ten koste van wie níet die plek pakt. JANE voor groepen helpt jullie elkaars functies leren herkennen, zodat iedereen z’n plek bewust kan invullen.",
    recognition: [
      "Jullie merken dat steeds dezelfde patronen optreden in jullie gesprekken.",
      "Eén of twee personen dragen onevenredig veel, anderen blijven onbenut.",
      "Jullie willen meer zijn dan een gezellige groep — een groep met functie.",
      "Jullie hebben elkaar al langer dan een paar maanden, en zoeken nu verdieping.",
    ],
    whatJaneDoes: [
      { title: "Een mini-workshop drie-stappen.", body: "In één of twee bijeenkomsten doorlopen jullie samen een ingekorte versie van de Jane-methode." },
      { title: "Groepsdiagram.", body: "Het resultaat is een visueel diagram dat álle functies van álle deelnemers samen toont — handig om te zien wat de groep als geheel sterk maakt." },
      { title: "Gespreksopdrachten voor in de groep.", body: "Eenvoudige opdrachten die jullie zelf kunnen blijven gebruiken om bewuster met elkaar om te gaan." },
    ],
    traject: [
      { step: "1", title: "Voorbereidend gesprek met de groepsleider", duration: "1 uur", what: "Inventarisatie van de groep en de centrale vraag." },
      { step: "2", title: "Bijeenkomst 1 — Wie zijn wij niet, wie zijn wij wel", duration: "2,5 uur", what: "De groep doorloopt stap 1 en 2 samen." },
      { step: "3", title: "Bijeenkomst 2 — Wat houdt ons tegen + diagram", duration: "2,5 uur", what: "Stap 3 + opbouw van het groepsdiagram." },
      { step: "4", title: "Follow-up na 6 weken", duration: "1 uur, eventueel online", what: "Korte check-in om te zien hoe de inzichten landen." },
    ],
    forWhomYes: [
      "Jullie zijn een vaste groep van 5–10 personen.",
      "Jullie kennen elkaar minstens enkele maanden.",
      "Jullie willen verdieping, niet alleen kennismaking.",
    ],
    forWhomNo: [
      "Jullie zijn pas net begonnen als groep — wacht 6 maanden.",
      "Er speelt acute spanning binnen de groep — los dat eerst af.",
    ],
    method: "Het groeps-aanbod is een aanvulling op de individuele JANE-trajecten, ontwikkeld op verzoek van huiskringen binnen onder andere de Familiekerk De Fakkel en Vision for Life-deelnemers.",
    faq: [
      { q: "Doet iedereen verplicht mee?", a: "We adviseren dat alle vaste leden meedoen — anders ontstaat scheve dynamiek. Bij twijfel: kom eerst met een kennismakingsgesprek." },
      { q: "Kost dit per persoon of voor de hele groep?", a: "Voor de hele groep. Het tarief is groepsgrootte-onafhankelijk binnen 5–10 personen." },
      { q: "Werkt dit ook bij niet-christelijke groepen?", a: "Ja, de spirituele laag wordt naar wens van de groep wel of niet meegenomen." },
    ],
    closingTitle: "Een laatste stap",
    closingText: "Een groep is meer dan haar leden. Plan een mini-workshop voor jullie groep en ontdek wat de samenstelling daadwerkelijk is.",
  },
  {
    slug: "teams",
    cluster: "team",
    status: "groeilijn",
    name: "Teams in bedrijf of kerk",
    shortName: "Teams",
    proposition: "Voor teams die hun collectieve sterkte willen begrijpen — en hun blinde vlek vóór die het werk beïnvloedt.",
    heroTitle: "Een team is meer dan de som van zijn functies",
    heroSubtitle: "Voor teams in bedrijf of kerk die hun collectieve sterkte willen begrijpen — en hun blinde vlek vóór die het werk beïnvloedt.",
    ctaLabel: "Plan een oriëntatie met de teamleider",
    intro: "Een team functioneert op een laag boven de individuele profielen: er ontstaan patronen die niet uit één persoon komen maar uit de combinatie. Sommige teams hebben hetzelfde compensatiegedrag als geheel — een collectieve blinde vlek. Het Team Life Statement-traject brengt die collectieve laag in beeld en levert een gedragen verklaring op over wie dit team is.",
    recognition: [
      "Jullie team haalt resultaten, maar de teamleider voelt dat er meer in zit.",
      "Bepaalde gesprekken keren steeds terug zonder dat iemand kan benoemen waarom.",
      "Onder druk vervallen jullie als team in patronen die niemand wil — en niemand kan stoppen.",
      "Jullie hebben individuele teamleden goed in beeld, maar het collectief niet.",
    ],
    whatJaneDoes: [
      { title: "Individuele Jane-profielen", body: "Voorafgaand werkt elk teamlid een eigen kort traject af, zodat de offsite begint met heldere persoonlijke uitgangsposities." },
      { title: "Team Blinde Vlek-analyse", body: "Op de offsite leggen we de profielen naast elkaar en identificeren we de collectieve blinde vlek — patronen die uit de combinatie ontstaan." },
      { title: "Team Life Statement", body: "Het team formuleert samen een verklaring over wie het is, wat zijn opdracht is, en welke gedragingen daar bij horen — en welke niet." },
      { title: "Team-diagram", body: "Een visuele samenvatting die jullie kunnen blijven gebruiken in het teamgesprek." },
    ],
    traject: [
      { step: "1", title: "Oriëntatie met de teamleider", duration: "1,5 uur", what: "Beoordeling of het team rijp is, en hoe we de offsite inrichten." },
      { step: "2", title: "Individuele profielen vooraf", duration: "Per teamlid 2–3 sessies", what: "Iedereen brengt z'n eigen profiel mee de offsite in." },
      { step: "3", title: "Offsite-dag", duration: "1 dag (vaak buiten kantoor)", what: "Drie blokken: profielen leggen, blinde vlek analyseren, Life Statement formuleren." },
      { step: "4", title: "Team-diagram + actieplan", duration: "Eindblok van de offsite", what: "Visuele samenvatting en concrete vervolgafspraken." },
      { step: "5", title: "Follow-up na 3 en 6 maanden", duration: "2 × 2 uur", what: "Check-ins met het team om verankering te bewaken." },
    ],
    forWhomYes: [
      "Een team van 4–12 personen dat minstens 6 maanden samenwerkt.",
      "Een teamleider die zelf bereid is mee te doen, niet alleen te observeren.",
      "Voldoende vertrouwen in het team om kwetsbaar te kunnen zijn.",
    ],
    forWhomNo: [
      "Een team in acute crisis of reorganisatie.",
      "Een team waarbij wantrouwen of conflicten eerst andere interventie vragen.",
      "Een teamleider die het traject 'aan het team oplegt' zonder mee te doen.",
    ],
    method: "Het Team Life Statement-traject is in volledig uitgewerkte vorm gerealiseerd voor Villa Klarendal in november 2014 — een dag die drie samenhangende producten opleverde (Team Blinde Vlek, Team Life Statement, Team Diagram). De methode is sindsdien direct beschikbaar maar werd selectief ingezet. Vraag bij intake naar de meest recente cases.",
    faq: [
      { q: "Wat is het verschil met een gewone team-offsite?", a: "Een offsite is vaak doel-gedreven (visie, strategie). Een Team Life Statement is identiteitsgedreven: wie zijn we als team. De uitkomsten zijn diepgaander en langduriger." },
      { q: "Hoe groot mag een team zijn?", a: "Tot 12 personen. Boven die grootte werken we met een gefaseerde aanpak waar de cellen apart een eigen traject doen en daarna samenkomen." },
      { q: "Kunnen wij dit ook online doen?", a: "Het individuele deel ja. De offsite-dag is bewust fysiek — de meerwaarde van een hele dag samen in één ruimte is methodisch belangrijk." },
    ],
    closingTitle: "Een laatste stap",
    closingText: "Een team dat z'n collectieve sterkte kent, werkt anders. Plan een oriëntatie met jou als teamleider — daarna beslissen we samen of het traject jullie team verder helpt.",
  },
  {
    slug: "oudstenteams",
    cluster: "team",
    status: "specialistisch",
    name: "Oudstenteams en kerkbesturen",
    shortName: "Oudstenteams",
    proposition: "Voor oudstenteams, kerkenraden en geestelijke besturen die stagneren in besluitvorming — of voelen dat hun gaven niet bewust worden ingezet.",
    heroTitle: "Besluit op gaven, niet op anciënniteit",
    heroSubtitle: "Voor oudstenteams, kerkenraden en geestelijke besturen die stagneren in besluitvorming — of voelen dat hun gaven niet bewust worden ingezet.",
    ctaLabel: "Plan een vertrouwelijk gesprek",
    intro: "Oudstenteams en kerkbesturen kennen een specifiek probleem: vaak draaien besluiten impliciet op anciënniteit, stemgewicht of langdurig opgebouwde rollen — terwijl de feitelijke gaven en functies in het team niet bewust worden ingezet. JANE legt bloot wie binnen het team welke functie heeft, en helpt jullie besluiten structureren op basis van die werkelijkheid.",
    recognition: [
      "Jullie maken besluiten waar de gemeente niet altijd in meekomt — of die jullie zelf na een tijd terugdraaien.",
      "Bepaalde leden van het team domineren impliciet, anderen blijven onbenut.",
      "Jullie merken dat oude rolverdelingen niet meer passen bij de gemeente nu.",
      "Een collectieve blinde vlek voelt herkenbaar maar is niet te benoemen.",
    ],
    whatJaneDoes: [
      { title: "Individuele profielen voor alle bestuursleden", body: "Voor elk lid een persoonlijk Jane-profiel — vaak verrassend ten opzichte van hoe het team elkaar denkt te kennen." },
      { title: "Team-diagram + collectieve blinde vlek", body: "De profielen samen tonen welk soort besluiten dit team natuurlijk neemt — en welke besluiten het systematisch uit de weg gaat." },
      { title: "Werksessie 'hoe nemen wij besluiten'", body: "Concrete afspraken: wie heeft welke stem bij welk type besluit, en hoe maken we de impliciete dynamiek expliciet." },
      { title: "Vertrouwelijke setting", body: "Het traject is intern en discreet — uitkomsten worden alleen gedeeld zoals het team zelf kiest." },
    ],
    traject: [
      { step: "1", title: "Oriëntatie met de voorzitter", duration: "1,5 uur", what: "Beoordeling van de groep, draagvlak, en hoe we vertrouwelijkheid borgen." },
      { step: "2", title: "Individuele profielen", duration: "Per lid 2–3 sessies", what: "Persoonlijk traject voor elk teamlid." },
      { step: "3", title: "Teamdag", duration: "1 dag offsite", what: "Profielen leggen, blinde vlek herkennen, besluitvorming herstructureren." },
      { step: "4", title: "Besluitvormingskader", duration: "Eindblok teamdag", what: "Concrete afspraken over hoe besluiten genomen worden." },
      { step: "5", title: "Follow-up na 6 maanden", duration: "Halve dag", what: "Check of de nieuwe structuur werkt — eventuele aanpassingen." },
    ],
    forWhomYes: [
      "Een oudstenteam, kerkenraad of geestelijk bestuur dat 6+ maanden samenwerkt.",
      "Bestuurslid-bestuurslid voldoende vertrouwen om kwetsbaar te zijn.",
      "Bereidheid om bestaande rolverdelingen te heronderzoeken.",
    ],
    forWhomNo: [
      "Het team zit middenin een conflict over leiderschap — los dat eerst af.",
      "Eén lid weigert mee te doen of doet alleen mee onder druk.",
      "Het team wil 'efficiënter vergaderen' zonder fundamentele heroriëntatie.",
    ],
    method: "JANE wordt sinds 2007 ingezet bij oudstenteams en bestuurslagen van gemeentes, met als vroegste voorbeeld 'de Shelter Oudstenteam' (2007) en 'Jane voorstel EC Europoort' (2006). Het traject is geschikt voor pinkster-, evangelische, vrij-evangelische en reformatorische gemeentes.",
    faq: [
      { q: "Moet de hele oudstenraad meedoen?", a: "Ja. Eén ontbrekend lid maakt het diagram onvolledig en de werksessie minder effectief." },
      { q: "Hoe vertrouwelijk is dit?", a: "Volledig vertrouwelijk binnen het team. Niets wordt gedeeld met de gemeente of derden zonder expliciete teamafspraak." },
      { q: "Is dit een audit?", a: "Nee. Het is een inzichtstraject zonder oordeel of advies over personen. De uitkomsten zijn beschrijvend, niet evaluerend." },
      { q: "Hoe lang duurt het hele traject?", a: "Vanaf oriëntatie tot follow-up: 4–6 maanden." },
    ],
    closingTitle: "Een laatste stap",
    closingText: "Beslissen op gaven in plaats van op anciënniteit kan een oudstenteam ingrijpend verlichten. Plan een vertrouwelijk gesprek met de voorzitter — zonder verplichtingen.",
  },
  {
    slug: "bedrijven-mkb",
    cluster: "team",
    status: "groeilijn",
    name: "MKB-organisaties",
    shortName: "Bedrijven",
    proposition: "Voor MKB-organisaties die HR willen baseren op werkelijke functies en gaven — niet op generieke functieprofielen.",
    heroTitle: "Mensen op hun functie, niet op hun titel",
    heroSubtitle: "Voor MKB-organisaties die HR willen baseren op werkelijke functies en gaven — niet op generieke functieprofielen.",
    ctaLabel: "Plan een kennismaking met de directie",
    intro: "Veel HR-instrumenten werken vanaf de organisatie naar de mens: hier is een functieprofiel, wie past erin? JANE werkt omgekeerd: wat zit er in deze mens, en hoe past dat in onze organisatie. Voor MKB-bedrijven die mensgericht willen werven, ontwikkelen en teams willen samenstellen, is dat een fundamenteel ander vertrekpunt.",
    recognition: [
      "Jullie hebben hoge verloop of disengagement op rollen waar mensen 'op papier passen'.",
      "Werving voelt als gokken — mensen lijken hetzelfde maar functioneren totaal anders.",
      "Jullie hebben mensen die onderpresteren in hun rol, maar van wie iedereen weet 'die zit op de verkeerde stoel'.",
      "Jullie willen meer dan een persoonlijkheidstest in het wervingsproces.",
    ],
    whatJaneDoes: [
      { title: "Jane Companyfuncties als kader", body: "Het volledig uitgewerkte 'boek 6 companyfuncties met competentiecheck' biedt een framework dat de 27 Jane-functies koppelt aan concrete bedrijfsrollen en competenties." },
      { title: "Toepasbaar bij werving", body: "JANE wordt ingezet bij sleutelposities om voorbij CV en assessmentcentrum te kijken naar de werkelijke functie-fit." },
      { title: "Toepasbaar bij ontwikkeling", body: "Bestaande medewerkers krijgen via een persoonlijk JANE-traject inzicht in de richting waarin ze duurzaam kunnen groeien — vaak een andere richting dan de organisatie had verwacht." },
      { title: "Toepasbaar bij teamsamenstelling", body: "Bij het opzetten van nieuwe teams of reorganisaties gebruikt JANE de profielen om bewust een functie-portfolio samen te stellen." },
    ],
    traject: [
      { step: "1", title: "Kennismaking met de directie", duration: "1,5 uur", what: "Wat is jullie HR-vraagstuk, en past JANE als instrument." },
      { step: "2", title: "Pilot — directie of MT", duration: "Per persoon 3–4 sessies", what: "Begin met de directie of het MT zelf, zodat jullie het instrument eerst op jezelf ervaren." },
      { step: "3", title: "Bedrijfs-implementatie", duration: "Op maat", what: "Inzet bij werving, ontwikkeling of teamsamenstelling, afhankelijk van prioriteit." },
      { step: "4", title: "Train-the-trainer (optioneel)", duration: "Aparte module", what: "Voor organisaties die JANE structureel willen inzetten: opleiding van interne HR-mensen." },
    ],
    forWhomYes: [
      "MKB-organisaties van 20 tot 250 medewerkers.",
      "Directies die HR strategisch zien, niet als administratie.",
      "Bedrijven met een specifiek HR-vraagstuk (werving, doorstroming, teamopbouw).",
    ],
    forWhomNo: [
      "Organisaties die vooral standaard-functieprofielen willen invoeren.",
      "Bedrijven die JANE als 'eenmalig screeningsinstrument' willen gebruiken — daarvoor is het te ingrijpend.",
      "Organisaties in acute crisis waar HR-vernieuwing nu niet past.",
    ],
    method: "JANE biedt al meer dan tien jaar een bedrijfsmatige toepassing onder de noemers 'Jane Management Consultants' en 'Jane Adviseurs, Coaches en Trainers'. Het bedrijfsframework — boek 6 companyfuncties met competentiecheck — is volledig uitgewerkt maar wordt selectief commercieel aangeboden.",
    faq: [
      { q: "Is dit hetzelfde als een MBTI, Insights of DISC-implementatie?", a: "Methodisch overlap maar inhoudelijk dieper. JANE werkt met 27 functies (vs. 4–16 types bij andere instrumenten) en kijkt expliciet naar blinde vlek en compensatie — niet alleen naar voorkeursstijl." },
      { q: "Wat kost dit voor een organisatie?", a: "Dat hangt af van de scope: pilot bij MT, breed wervingsinstrument of organisatiebrede implementatie. Vraag een offerte op maat aan." },
      { q: "Wordt JANE ergens al organisatiebreed ingezet?", a: "JANE is in MKB selectief ingezet en bij enkele non-profit organisaties. Vraag bij intake naar de meest actuele cases." },
      { q: "Is JANE compatibel met andere HR-instrumenten?", a: "Ja. JANE-profielen worden vaak gebruikt náást standaardinstrumenten als aanvullende laag — niet als vervanging." },
    ],
    closingTitle: "Een laatste stap",
    closingText: "Mensen op hun werkelijke functie krijgen, is geen luxe maar een rendement. Plan een kennismaking met jullie directie — vrijblijvend en met scope-bepaling vooraf.",
  },
  {
    slug: "lokale-gemeentes",
    cluster: "advies",
    status: "specialistisch",
    name: "Gemeentes en kerkenraden",
    shortName: "Gemeentes",
    proposition: "Voor gemeentes en kerkenraden die toe zijn aan een gefundeerde profielschets en gemeentevisie, gebaseerd op de gaven en functies die feitelijk aanwezig zijn.",
    heroTitle: "Wie is jullie gemeente eigenlijk — en waar leidt dat heen?",
    heroSubtitle: "Voor gemeentes en kerkenraden die toe zijn aan een gefundeerde profielschets en gemeentevisie, gebaseerd op de gaven en functies die feitelijk aanwezig zijn.",
    ctaLabel: "Plan een oriëntatie met de kerkenraad",
    intro: "Een gemeentevisie schrijven zonder eerst te weten wie de gemeente is, leidt tot algemene visies waar niemand zich aan committeert. JANE biedt een methodische manier om eerst de gemeente in kaart te brengen — enquête, interviews, functie-analyse — en op basis daarvan een gemeentevisie te ontwikkelen die werkelijk past bij wie jullie zijn.",
    recognition: [
      "Jullie willen een gemeentevisie, maar weten niet waar te beginnen.",
      "Eerdere visies bleven hangen in algemeenheden of werden niet gedragen.",
      "Jullie merken dat de gemeente verandert maar weten niet precies hoe.",
      "Jullie willen een fundament onder beleidsbeslissingen.",
    ],
    whatJaneDoes: [
      { title: "Enquête onder gemeenteleden", body: "Gestandaardiseerde maar gemeente-specifiek ingerichte enquête die functies, gaven en betrokkenheid in kaart brengt." },
      { title: "Diepte-interviews met sleutelpersonen", body: "Aanvullende gesprekken met oudsten, voorganger, leiders van werkgroepen — om de getallen te duiden." },
      { title: "Profielschets-document", body: "Een gefundeerde beschrijving van wie deze gemeente is: samenstelling van functies en gaven, sterktes, blinde vlekken, ontwikkelingsruimte." },
      { title: "Visie-traject met kerkenraad", body: "Op basis van de profielschets begeleidt JANE de kerkenraad bij het ontwikkelen van een gemeentevisie die feitelijk past." },
    ],
    traject: [
      { step: "1", title: "Oriëntatie met de kerkenraad", duration: "2 uur", what: "Scope-bepaling, draagvlak, planning." },
      { step: "2", title: "Voorbereiden enquête", duration: "1 maand", what: "Op maat samenstellen, communicatie naar gemeente, uitsturen." },
      { step: "3", title: "Enquête + interviews", duration: "1,5 maand", what: "Veldwerk: enquête laten invullen, interviews voeren." },
      { step: "4", title: "Analyse en profielschets", duration: "3–4 weken", what: "Rapportage opstellen, eerste bespreking met kerkenraad." },
      { step: "5", title: "Visie-traject", duration: "2–3 sessies van een dagdeel", what: "Op basis van de profielschets bouwt de kerkenraad de gemeentevisie." },
      { step: "6", title: "Presentatie aan gemeente", duration: "1 zondag of avond", what: "Profielschets én visie worden aan de gemeente teruggegeven." },
    ],
    forWhomYes: [
      "Een gemeente met minimaal 80 betrokken leden (anders is de enquête statistisch te dun).",
      "Een kerkenraad die bereid is 6 maanden te investeren in dit traject.",
      "Bereidheid om uitkomsten serieus te nemen — ook als ze ongemakkelijk zijn.",
    ],
    forWhomNo: [
      "Gemeentes in acute conflictsituatie — los dat eerst af.",
      "Gemeentes die alleen een 'visie-document' willen voor extern gebruik.",
      "Kerkenraden die niet bereid zijn ruim 6 maanden te investeren.",
    ],
    method: "Het profielschets-traject is concreet uitgevoerd bij meerdere gemeentes, met onder andere VEG Bennekom (drie versies van profielschets) en PG Wassenaar (gemeentevisie). De methode is breder uitgewerkt via de VPE Regio Oost-enquête en de programma's 'Vrij zijn om te veranderen'.",
    faq: [
      { q: "Hoeveel respons hebben we minimaal nodig?", a: "Bij gemeentes van 80–200 leden mikken we op minimaal 60% respons. Onder die grens is het beeld onvolledig en moeten we de enquête herhalen of verbreden." },
      { q: "Wat als de profielschets iets oncomfortabels laat zien?", a: "Dat is geen falen maar juist het beoogde inzicht. JANE geeft beschrijvende inzichten en helpt de kerkenraad ze betekenisvol te interpreteren — geen oordeel." },
      { q: "Hoe wordt de privacy van individuele respondenten geborgd?", a: "De enquête is geanonimiseerd. Interviews worden vertrouwelijk gevoerd en alleen geanonimiseerd gerapporteerd. Geen persoonsherleidbare informatie verlaat het analyseproces." },
      { q: "Wat kost dit?", a: "Afhankelijk van gemeentegrootte en scope. Vraag een offerte aan — gemiddeld 8.000–18.000 euro voor het complete traject." },
    ],
    closingTitle: "Een laatste stap",
    closingText: "Een gemeentevisie die gedragen wordt, begint bij weten wie jullie zijn. Plan een oriëntatie met de kerkenraad — geheel vrijblijvend en met een concreet voorstel als vervolg.",
  },
  {
    slug: "internationaal",
    cluster: "internationaal",
    status: "slapend",
    name: "Internationaal / Engelstalig",
    shortName: "Internationaal",
    proposition: "For English speakers who want to discover their unique calling and function — using a method developed over two decades in Dutch churches and businesses.",
    heroTitle: "JANE for the English-speaking world",
    heroSubtitle: "For English speakers who want to discover their unique calling and function — using a method developed over two decades in Dutch churches and businesses.",
    ctaLabel: "Schedule a discovery call (in English)",
    intro: "JANE is een methodiek die in Nederland al meer dan twintig jaar wordt ingezet bij honderden mensen — in gemeentes, bij voorgangers, in MKB en bij teams. De Engelstalige variant is in opbouw: vertaalde 27 Jane-functies en de drie-stappen-workshop zijn beschikbaar, ondersteund door directe Engelstalige coaching.",
    recognition: [
      "You're an English speaker (expat, international, or non-Dutch) curious about your unique calling.",
      "You've taken personality tests but feel they only describe you, not direct you.",
      "You want a method with depth and history — not a marketing-driven framework.",
      "You're open to a coach speaking English directly, with Dutch-rooted methodology.",
    ],
    whatJaneDoes: [
      { title: "27 functions, translated and culture-sensitive", body: "The 27 Jane functions are translated to English, with cultural sensitivity to spiritual and secular contexts." },
      { title: "Three-step workshop in English", body: "The methodologically core workshop — Who am I not, Who am I, What's stopping me — delivered in English." },
      { title: "One-on-one coaching, in English", body: "Coaching sessions in clear English — for individuals, leaders, or sales professionals." },
      { title: "Optional: spiritual layer or business framing", body: "JANE works both as a spiritual instrument (gifts, fivefold ministry) and as a professional one (leadership, sales, career) — chosen at intake." },
    ],
    traject: [
      { step: "1", title: "Discovery call", duration: "1 hour", what: "Get to know each other, scope your question, decide if JANE fits." },
      { step: "2", title: "Step 1 — Who I am not", duration: "1.5 hours + home assignment", what: "Clarify the roles and functions that aren't really yours." },
      { step: "3", title: "Step 2 — Who I am", duration: "1.5 hours + home assignment", what: "Identify your core functions from the 27 Jane functions." },
      { step: "4", title: "Step 3 — What's stopping me", duration: "2 hours + home assignment", what: "Uncover compensation behavior and blind spots." },
      { step: "5", title: "Personal diagram", duration: "1.5 hours", what: "A visual summary you can use as a long-term reference point." },
    ],
    forWhomYes: [
      "You're an English-speaking professional, leader, or church member.",
      "You're ready for honest self-reflection.",
      "You value methodology with depth over quick personality assessments.",
    ],
    forWhomNo: [
      "You need a quick assessment for a job application.",
      "You're not open to spiritual or values-based dimensions of work and life.",
      "You're in an acute personal crisis — different support is needed first.",
    ],
    method: "JANE is a methodology developed over more than two decades by Dirk van der Schaaf, applied to hundreds of clients in Dutch churches and businesses. The English translation of the core 27 functions and the three-step methodology has been completed; international rollout is in selective onboarding phase.",
    faq: [
      { q: "Is this a Christian or secular method?", a: "Both. JANE has a spiritual root (gifts, fivefold ministry) and a professional application (leadership, sales, career). At intake you choose which layer is prominent for your trajectory." },
      { q: "How does this compare to MBTI, Enneagram, or CliftonStrengths?", a: "JANE is methodologically deeper (27 functions, not 4–16 types) and includes explicit attention to blind spots and compensation behavior — typically not present in personality assessments." },
      { q: "Can sessions be online?", a: "Yes, for individual trajectories online is the standard for international clients. Team trajectories ideally include at least one in-person day." },
      { q: "What's the cost?", a: "Pricing is per trajectory and aligned with international standards for executive coaching. Request a quote at the discovery call." },
    ],
    closingTitle: "Een laatste stap",
    closingText: "Discovering what you're made for deserves more than a test. Schedule a discovery call (in English) and explore whether JANE is your next step.",
  },
];
