import type { AudienceItem } from "./audiences";

export const audiencesEn: AudienceItem[] = [
  {
    slug: "gemeenteleden",
    cluster: "geestelijk",
    status: "kernlijn",
    name: "Church members & Christians",
    shortName: "Church members",
    proposition: "Don't just find a role in the church — find the place where you flourish.",
    heroTitle: "Discover the place God specifically intended for you",
    heroSubtitle:
      "By getting clarity on your gifts and your unique function, you don't just find a role in the church — you find the place where you flourish.",
    ctaLabel: "Schedule a no-obligation introductory conversation",
    intro:
      "JANE is a coaching journey developed for Christians who want more than to 'do something' in their church. It's not a personality test and not pastoral care — it's a structured insight instrument that shows you which spiritual function God has placed in you, and how you can live and serve from it.",
    recognition: [
      "You've been doing something in the church for years, but don't feel truly at home in it.",
      "Others see you differently than you see yourself — and you wonder which picture is right.",
      "You feel your gifts are still undiscovered, or that they aren't being seen.",
      "You want to serve from who you are, not from what turns out to be needed.",
    ],
    whatJaneDoes: [
      { title: "Insight into your spiritual gifts.", body: "Using the 35 gift texts and the fivefold ministry (Apostle, Prophet, Evangelist, Pastor, Teacher) you discover which gifts specifically belong to you." },
      { title: "Clarity about your unique function.", body: "From the 27 Jane functions you get a personal profile — not a single type label but a combination that's specific to you." },
      { title: "Recognising what holds you back.", body: "The three-step workshop exposes the behaviour you unconsciously use to avoid your true calling: your 'compensation talent' and your 'blind spot'." },
      { title: "A personal Jane diagram.", body: "At the end of the journey you have a visual summary (Jane diagram) you can keep using in your church and personal life." },
    ],
    traject: [
      { step: "1", title: "Intake conversation", duration: "1 hour", what: "A no-obligation introductory conversation in which we look at whether JANE fits you and which questions are central for you." },
      { step: "2", title: "Step 1 — Who I am not", duration: "1.5 hours + homework", what: "We mark out the contours by determining which functions and behaviours are not yours. Often surprisingly liberating." },
      { step: "3", title: "Step 2 — Who I am", duration: "1.5 hours + homework", what: "We identify your core functions from the set of 27 and link them to the gift texts." },
      { step: "4", title: "Step 3 — What holds me back", duration: "1.5 hours + homework", what: "The deepest step: discover your blind spot and the compensation behaviour you use to hide it — from yourself and from others." },
      { step: "5", title: "Conclusion & Jane diagram", duration: "1 hour", what: "A personal diagram, feedback toward your church, and concrete next steps." },
      { step: "6", title: "Optional follow-up", duration: "After 3 months", what: "One follow-up session to see how the insights land in practice." },
    ],
    forWhomYes: [
      "You are an active part of a church, or want to become one.",
      "You are open to self-reflection and willing to look honestly at behaviour you recognise.",
      "You are willing to work on assignments at home between sessions.",
      "You want to grow in serving from who you are, not from what is asked.",
    ],
    forWhomNo: [
      "You are looking for a quick fix or a fast test.",
      "You are currently in an acute crisis — pastoral or professional care comes first there.",
      "You are not open to spiritual interpretation of your life.",
    ],
    method:
      "The JANE method was developed over more than two decades by Dirk van der Schaaf and used with hundreds of people in churches such as VEG Bennekom, PG Wassenaar, Familiekerk De Fakkel, Pentecostal Church Alkmaar and Alphakerk. The method was used by the VPE umbrella as a pilot programme for church leaders and is broadly applicable across denominations.",
    faq: [
      { q: "Is this a psychological test?", a: "No. JANE is a spiritual insight instrument that combines reflection and outcome. It is not scientifically validated as a personality test, but has been used with hundreds of people in practice and found recognisable." },
      { q: "Is it useful if I'm not from an evangelical church?", a: "Yes. The method was developed from the evangelical/charismatic tradition, but works broadly across denominations. The spiritual layer (gifts, fivefold ministry) is offered in a way you can use with your own background." },
      { q: "How long does the whole journey take?", a: "Usually 6 to 8 weeks, with sessions of an hour and a half and homework in between. The pace is tuned to your situation." },
      { q: "What if I turn out not to have 'spectacular' gifts?", a: "That happens to almost everyone who has this thought. JANE shows that the 27 functions are of equal value — and that the 'invisible' gifts (such as helping, supporting, being hospitable) often carry the church's work." },
      { q: "What does a journey cost?", a: "Get in touch for a current rate. We work with a sliding scale for young people, students and church members without their own income." },
    ],
    closingTitle: "One last step",
    closingText:
      "Ready to discover what God specifically intended for you? Schedule a no-obligation 30-minute introductory conversation — after that you decide whether the journey fits you. No obligation. No sales. A first exploration.",
  },
  {
    slug: "voorgangers",
    cluster: "geestelijk",
    status: "kernlijn",
    name: "Pastors & church leaders",
    shortName: "Pastors",
    proposition: "For pastors, elders and church leaders who want to see more clearly which function is truly theirs — and which behaviour is unknowingly burdening their congregation.",
    heroTitle: "Lead from your core, not from your exhaustion",
    heroSubtitle: "For pastors, elders and church leaders who want to see more clearly which function is truly theirs — and which behaviour is unknowingly burdening their congregation.",
    ctaLabel: "Schedule a confidential exploratory conversation",
    intro: "Being a pastor is not a job but a collection of roles that get layered onto you over the years: preacher, pastor, leader, organiser, mediator, sometimes even manager. JANE helps you bring back what is truly yours, and recognise which behaviour you use to keep the rest going — behaviour that often costs more than it delivers.",
    recognition: [
      "You notice you do something 'because it has to be done' while inwardly you are not in it.",
      "You see patterns in your work where you get stuck, but you can't find the words to talk about them with colleagues.",
      "You feel that the congregation sees more of your role than of who you really are.",
      "You feel a tiredness that doesn't go away with a week's holiday.",
    ],
    whatJaneDoes: [
      { title: "Distinguishing between your function and your role.", body: "JANE reveals which of the 27 functions is genuinely yours — independent of what the congregation or your tradition expects of a pastor." },
      { title: "Recognising the blind spot.", body: "For pastors, step 3 — the compensation analysis — is often the most valuable. The behaviour you use to keep your 'role' going inevitably affects your congregation." },
      { title: "Positioning within the fivefold ministry.", body: "Are you an Apostle, Prophet, Evangelist, Pastor or Teacher — or a specific combination? This framework helps you prioritise more consciously." },
      { title: "A fully confidential journey.", body: "Unlike a congregation-wide programme, this is one-on-one and discreet. No reporting to the church council, no judgement — only your clarity." },
    ],
    traject: [
      { step: "1", title: "Confidential exploratory conversation", duration: "1 hour", what: "We look at whether the journey fits, which questions matter to you, and how we safeguard confidentiality." },
      { step: "2", title: "Step 1 — Who I am not", duration: "1.5 hours + homework", what: "We name the roles you fulfil but that are not essentially yours — often a longer list than expected." },
      { step: "3", title: "Step 2 — Who I am", duration: "1.5 hours + homework", what: "Identifying your core functions from the 27 and your position in the fivefold ministry." },
      { step: "4", title: "Step 3 — What holds me back", duration: "2 hours + homework", what: "An in-depth analysis of your compensation behaviour, with attention to its effect on your congregation." },
      { step: "5", title: "Conclusion & next-step choices", duration: "1.5 hours", what: "A personal diagram, a conversation guide for your elder team (only if you want one), and concrete next steps." },
      { step: "6", title: "Monthly guidance", duration: "6–12 months", what: "Optional: light coaching over 6 to 12 months to embed the insights." },
    ],
    forWhomYes: [
      "You are a pastor, elder, chair of the elder council or in a comparable leadership role.",
      "You are open to looking deeply at your own patterns — even when they are confronting.",
      "You are willing, in the second half of the journey, to make choices that could change your role.",
    ],
    forWhomNo: [
      "You are in the middle of a conflict in the congregation — resolve that first.",
      "You are looking for a formal assessment of your performance as a pastor.",
      "You are not willing to weigh confidential insights seriously.",
    ],
    method: "JANE has been used for pastors since 2008, beginning with the VPE pilot 'Jane instruments for church leaders'. The most fully developed coaching file is that of a pastor (published with permission as an anonymous case). The method is suitable for Pentecostal, evangelical, free evangelical and reformed pastors — wherever leadership and spiritual ministry come together.",
    faq: [
      { q: "Should my church council or elder team know about this?", a: "Not necessarily. This is a personal journey with full confidentiality. Whether and how you share insights is your choice." },
      { q: "Isn't this the same as a sabbatical?", a: "No. A sabbatical is taking distance; JANE is gaining insight. A combination can be effective — a sabbatical with a JANE journey in its first months." },
      { q: "How much time does it take alongside my regular work?", a: "Count on roughly 4–6 hours per month: a ninety-minute session + 2–4 hours of homework. The journey runs 4–6 months depending on pace." },
      { q: "Does this also work for younger or just-starting pastors?", a: "Yes, and often it's an advantage: the earlier in your ministry, the less consolidated the compensation behaviour." },
    ],
    closingTitle: "One last step",
    closingText: "An honest conversation about what is yours and what is not costs you an hour. Schedule a confidential exploratory conversation — no obligation, no reporting, no judgement.",
  },
  {
    slug: "jongeren-studiekeuze",
    cluster: "ontwikkeling",
    status: "slapend",
    name: "Young people & study choice",
    shortName: "Young people",
    proposition: "For young people between 16 and 25 who have to make study or career choices, and want more than a test that slaps a 'profile' on them.",
    heroTitle: "Not which subject fits — but which one fits you",
    heroSubtitle: "For young people between 16 and 25 who have to make study or career choices, and want more than a test that slaps a 'profile' on them.",
    ctaLabel: "Schedule an introduction for you and your parent(s)",
    intro: "A standard study-choice test sorts you into a box. JANE does something fundamentally different: it shows which function and gifts genuinely live in you, and helps you choose a direction to match — instead of choosing a direction you're supposed to 'fit into'.",
    recognition: [
      "You'll soon have to choose a study and the list seems random.",
      "Everyone around you seems to 'have it figured out' and you feel behind.",
      "You've already done a few tests, but the results don't say anything personal.",
      "You doubt whether you should choose the sensible option or what truly fits you.",
    ],
    whatJaneDoes: [
      { title: "A direction instead of a box.", body: "No profile code, but a personal description of which functions and gifts work in you — so you understand why some things give you energy and others don't." },
      { title: "Insight into why certain choices keep coming back.", body: "Many young people recognise 'the same pattern' in friends, hobbies and side jobs. JANE reveals why that pattern belongs to you." },
      { title: "A conversation between you and your parents.", body: "Optional but often requested: sharing the results with your parents, so they understand why a 'sensible' choice isn't always the right one — or actually is." },
      { title: "A personal Jane diagram.", body: "A visual summary you can keep using later in your studies or work." },
    ],
    traject: [
      { step: "1", title: "Introduction", duration: "45 min", what: "A no-obligation conversation, optionally with parent(s) present, to see whether JANE fits you." },
      { step: "2", title: "Step 1 — What I am not", duration: "1 hour + homework", what: "An adapted, visual exercise: which things just don't get you going?" },
      { step: "3", title: "Step 2 — What I am", duration: "1 hour + homework", what: "Identifying your core functions and talents — translated into fields of study and work." },
      { step: "4", title: "Step 3 — What holds me back", duration: "1 hour + homework", what: "Which patterns do you recognise that make you choose against yourself anyway?" },
      { step: "5", title: "Conclusion + conversation with parents", duration: "1.5 hours", what: "A personal diagram and direction advice. Optional: a joint conversation with your parents." },
    ],
    forWhomYes: [
      "You are between 16 and 25 and facing a study, work or direction choice.",
      "You want to look deeper than an online test.",
      "You are open to reflection — even if it sometimes feels uncomfortable.",
      "Your parents support you in this journey, or you are in charge yourself.",
    ],
    forWhomNo: [
      "You have no space to spend a few weeks on yourself.",
      "You mainly want a quick result, not reflection.",
      "You are currently in a mental crisis — that calls for other care first.",
    ],
    method: "JANE has also been applied to young people since 2009, originally through church youth workers. The method has been made available in a simplified form to connect with the language and life questions of young people — without losing the depth of content of the adult journey.",
    faq: [
      { q: "What if I have no idea what I want?", a: "That is precisely the starting point. JANE works not through 'what do you want' but through 'who are you' — and direction arises naturally from the second." },
      { q: "Can my parents be there?", a: "At the introduction and the conclusion that can work well. The intermediate steps you do under your own strength; that's the intention." },
      { q: "Does this also work if I'm not 'into' faith at all?", a: "Yes. The spiritual layer (gift texts) we can include or leave out in consultation with you — JANE also works purely on the function layer." },
      { q: "How long does it take?", a: "Usually 4 to 6 weeks." },
    ],
    closingTitle: "One last step",
    closingText: "A good choice begins with knowing who you are — not with a list of programmes. Schedule a no-obligation introduction, optionally together with your parent(s).",
  },
  {
    slug: "loopbaantransitie",
    cluster: "ontwikkeling",
    status: "kernlijn",
    name: "Career transition",
    shortName: "Career",
    proposition: "For professionals who are stuck, recovering from burnout, or sensing they took the wrong turn — and have no appetite for another round with the same patterns.",
    heroTitle: "For those who want more than to start over",
    heroSubtitle: "For professionals who are stuck, recovering from burnout, or sensing they took the wrong turn — and have no appetite for another round with the same patterns.",
    ctaLabel: "Schedule an intake conversation",
    intro: "With a career question you have two options: look for a new job that may repeat the same patterns, or look deeper at what lies beneath those patterns. JANE offers the second. It is not a work methodology, not a LinkedIn strategy, but a fundamental insight into which function and which pitfalls make you who you are — so that you then look at work with different eyes.",
    recognition: [
      "You've already had two or three jobs in a row that fell apart over something similar.",
      "You're recovering from burnout and don't want to fall into the same trap again.",
      "You wonder why you lose so much energy on things that are supposed to look good.",
      "You feel that the career coaches so far mainly gave CV advice, not self-knowledge.",
    ],
    whatJaneDoes: [
      { title: "A diagnosis, not job-application training.", body: "JANE starts not from 'what could I do' but from 'what am I' — a distinction that makes the difference between a repetition of patterns and real change." },
      { title: "Insight into patterns that travel along between jobs.", body: "Step 3 (blind spot / compensation talent) reveals why the same behaviour keeps coming back — regardless of which employer you have." },
      { title: "Translation into concrete career choices.", body: "The journey results in a Jane diagram that is directly linked to fields of work, roles and employment arrangements that genuinely suit you." },
      { title: "A foundation for follow-up conversations.", body: "Many clients use the Jane diagram later in conversations with career coaches, headhunters or managers — as a shared language." },
    ],
    traject: [
      { step: "1", title: "Intake conversation", duration: "1 hour", what: "Getting acquainted, defining the scope and clarifying your central question." },
      { step: "2", title: "Step 1 — Who I am not", duration: "1.5 hours + homework", what: "Which functions and roles have you fulfilled that weren't yours — and what did that cost you?" },
      { step: "3", title: "Step 2 — Who I am", duration: "1.5 hours + homework", what: "Identifying your core functions with a direct career translation." },
      { step: "4", title: "Step 3 — What holds me back", duration: "2 hours + homework", what: "The patterns you brought to every job, and why they keep coming back." },
      { step: "5", title: "Career translation", duration: "1.5 hours", what: "A Jane diagram + concrete career directions + a discussion with your network environment." },
      { step: "6", title: "Follow-up after 3 and 6 months", duration: "2 × 1 hour", what: "A check-in to see how the insights land in a new work situation." },
    ],
    forWhomYes: [
      "You are facing a career choice or coming out of a burnout.",
      "You already have some self-reflection behind you and now want to go a step deeper.",
      "You have the space (mentally and financially) to spend 2–3 months on yourself.",
      "You are willing to receive answers that are fundamentally different from what you expected.",
    ],
    forWhomNo: [
      "You mainly need CV advice or job-application training.",
      "You want a new job within a few weeks, not reflection.",
      "You haven't recovered sufficiently from absence yet — hold off on this for now.",
    ],
    method: "Since 2010 JANE has been explicitly applied to career questions, with its own subfolder of presentation material within the methodology (8 'Career' documents). Clients range from mid-career professionals reorienting themselves to managers after a dismissal or burnout. Clients often use the Jane diagram as a reference point for years after the journey.",
    faq: [
      { q: "Isn't this the same as an outplacement programme?", a: "No. Outplacement is aimed at a new job within a short time. JANE first goes deeper, and then provides precisely the basis that makes outplacement more effective." },
      { q: "Does JANE work together with my employer, or is this entirely personal?", a: "By default entirely personal and confidential. In some cases an employer (or the UWV) can fund a journey — that is only on your initiative and in consultation." },
      { q: "What if the outcome is that I'd be better off going independent?", a: "That happens regularly. JANE shows what works in you — what you make of that in terms of employment arrangement is your choice." },
      { q: "How long does it take?", a: "8–12 weeks for the core journey, plus follow-ups at 3 and 6 months." },
    ],
    closingTitle: "One last step",
    closingText: "A career question deserves more than a list of vacancies. Schedule an intake conversation and discover what makes the difference — for yourself and for your next step.",
  },
  {
    slug: "managers",
    cluster: "zakelijk",
    status: "kernlijn",
    name: "Managers & team leaders",
    shortName: "Managers",
    proposition: "For managers who feel that their learned style no longer fits, or who notice that their blind spot is affecting their team.",
    heroTitle: "Lead your team from who you are — not from what you learned as a manager",
    heroSubtitle: "For managers who feel that their learned style no longer fits, or who notice that their blind spot is affecting their team.",
    ctaLabel: "Schedule a confidential conversation",
    intro: "Most leadership trainings add something: more skills, more models, more feedback. JANE does the opposite — it strips away what isn't yours. What remains is your own leadership function, clearly positioned and aware of the patterns that still block you now.",
    recognition: [
      "You've had leadership training but don't really apply the models.",
      "You notice that under stress you fall back on behaviour you know doesn't work.",
      "Your team functions well, but you suspect there's more in it if you led differently.",
      "You feel that your 'manager style' isn't quite yours.",
    ],
    whatJaneDoes: [
      { title: "Distinguishing between you and your role.", body: "JANE shows which functions are yours (from the 27) and which you learned because they 'belong' to management. That distinction is liberating." },
      { title: "Insight into stress patterns.", body: "Step 3 reveals which compensation behaviour you deploy under pressure — and how that influences your team. Often the most valuable insight of the journey." },
      { title: "A leadership style that works naturally.", body: "Instead of a 'best style' you get your style: clear, recognisable, and confirmed by what works in you." },
      { title: "Optional: a team journey to follow.", body: "Many managers then bring their direct reports into a team journey (Team Life Statement) to anchor their own insights in practice." },
    ],
    traject: [
      { step: "1", title: "Exploratory conversation", duration: "1 hour", what: "A confidential conversation, optionally funded via your employer or entirely private." },
      { step: "2", title: "Step 1 — Who I am not (as a manager)", duration: "1.5 hours + homework", what: "Which roles do you fulfil that aren't yours — and where do you pay for that?" },
      { step: "3", title: "Step 2 — Who I am", duration: "1.5 hours + homework", what: "Identifying your core functions, translated into leadership." },
      { step: "4", title: "Step 3 — What holds me back", duration: "2 hours + homework", what: "Stress patterns, compensation behaviour, and impact on your team." },
      { step: "5", title: "Leadership diagram", duration: "1.5 hours", what: "A Jane diagram + action points for your role as a manager." },
      { step: "6", title: "Optional: team journey", duration: "1 day offsite", what: "An extension with your direct team — the Team Life Statement." },
    ],
    forWhomYes: [
      "You have ultimate responsibility for a team or department.",
      "You are willing to examine your own style instead of your team's.",
      "You have room for a journey of 8–10 weeks alongside your work.",
      "You are open to insights that could change your leadership.",
    ],
    forWhomNo: [
      "You mainly want to expand your toolset (models, frameworks).",
      "You expect coaching to give you 'direct handles' for tomorrow.",
      "You are not willing to discuss your own patterns seriously.",
    ],
    method: "Since 2010 JANE has been used for managers via Jane Management Consultants, with material such as 'Unique Destiny Manager' and 'Jane ACT' (Advisers, Coaches and Trainers). Clients range from SME boards to middle management in larger organisations. Journeys are often followed by a Team Life Statement with the direct team.",
    faq: [
      { q: "Will my employer reimburse this journey?", a: "Often yes, under headings such as 'leadership development' or 'personal coaching'. If desired, we provide a tidy quote." },
      { q: "Is this the same as executive coaching?", a: "There is overlap, but JANE is more methodical and delivers a more concrete end product (the diagram). Many executive coaches refer clients on for the JANE part." },
      { q: "Does this also work for middle managers, not just the top?", a: "Yes, exceptionally well even. Middle managers are often in the heaviest role ambiguity, where JANE delivers the most." },
      { q: "What if the journey makes me realise I'm not a manager?", a: "That happens to some clients. JANE then also helps prepare the conversations to reshape your role." },
    ],
    closingTitle: "One last step",
    closingText: "Good leaders know themselves sharply. Schedule a confidential exploratory conversation and see whether JANE can support your next step.",
  },
  {
    slug: "sales",
    cluster: "zakelijk",
    status: "kernlijn",
    name: "Sales professionals",
    shortName: "Sales",
    proposition: "For sales professionals who hit their targets but lose energy doing it, or who feel their role slowly no longer fits them.",
    heroTitle: "Selling from authenticity — not from a script",
    heroSubtitle: "For sales professionals who hit their targets but lose energy doing it, or who feel their role slowly no longer fits them.",
    ctaLabel: "Schedule a sales-coaching intake",
    intro: "Sales is a profession in which energy comes and goes faster than in almost any other job. JANE helps sales professionals distinguish between the learned selling style — often exhausting and target-driven — and their natural sales function. What remains is a way of selling that works for the long term and for you personally.",
    recognition: [
      "You hit your numbers but feel flatter after every quarter than the last.",
      "You have colleagues who seem to do it ‘naturally’ — and you suspect they know something you haven’t figured out.",
      "You enjoy selling, but not always the way your approach prescribes.",
      "You’ve had several sales trainings, but none of them fundamentally changed how you work.",
    ],
    whatJaneDoes: [
      { title: "Discover which sales function truly fits you.", body: "Not every sales professional is a ‘hunter’ or a ‘farmer’. JANE shows which combination of functions works within you — often surprisingly specific." },
      { title: "Recognise which compensation costs you energy.", body: "Step 3 exposes the behaviour you deploy to achieve results against your own nature — behaviour that delivers results but drains you." },
      { title: "An approach that works sustainably.", body: "The programme doesn’t produce new techniques, but insight that lets you use your existing techniques more consciously — letting some go, using others more intensively." },
      { title: "Optional: a team programme for the whole sales team.", body: "If you are a manager or a sales team, we can set up the programme collectively with a Team Life Statement." },
    ],
    traject: [
      { step: "1", title: "Intake", duration: "1 hour", what: "We discuss your role, your market and what your central question is." },
      { step: "2", title: "Step 1 — What is not selling for you", duration: "1.5 hours + homework", what: "Which parts of the sales work get in your way the most?" },
      { step: "3", title: "Step 2 — What is your selling", duration: "1.5 hours + homework", what: "Identifying your natural sales function within the 27 Jane functions." },
      { step: "4", title: "Step 3 — What drains you", duration: "2 hours + homework", what: "Patterns that cost you energy — and how to recognise them before they strike." },
      { step: "5", title: "Sales diagram", duration: "1.5 hours", what: "Jane diagram, translated into concrete sales action points." },
    ],
    forWhomYes: [
      "You work in a sales role (account, new business, channel, inside sales, etc.).",
      "You achieve results but pay more for them than you would like.",
      "You are willing to examine your approach, not just your targets.",
    ],
    forWhomNo: [
      "You are mainly looking for new sales techniques or more training.",
      "You expect coaching to raise your targets without you changing.",
      "You are in a conflict with your manager about performance — resolve that first.",
    ],
    method: "With material such as ‘Unieke Bestemming Sales 2011’ and cases like Alexport, JANE has guided sales professionals in both B2B and B2C, in SMEs and larger organisations. The sales programme is methodologically identical to other Jane programmes, but the translation into practice happens in sales language.",
    faq: [
      { q: "Does this also work if I’m in pure B2B sales (technical, complex)?", a: "Yes, JANE comes into its own particularly in complex B2B sales, because there self-direction and building trust — both function-sensitive — play a strong role." },
      { q: "Will this be reimbursed by my employer?", a: "Often yes, as ‘professional development’ or ‘sales coaching’. We provide a quote that fits the usual HR budgets." },
      { q: "How does this relate to Sandler / Spin / Challenger sales?", a: "JANE is not a sales methodology, but a personal insight instrument. These methodologies are techniques; JANE determines which techniques work for you." },
      { q: "Does this also work for sales managers?", a: "Yes, and often with added value: a sales manager with insight into their own function can carry that through to the team." },
    ],
    closingTitle: "A final step",
    closingText: "Doing sales from strength instead of from a script — that’s not a luxury but a return on investment. Schedule an intake conversation and see what it can deliver for you.",
  },
  {
    slug: "team-projectleiders",
    cluster: "zakelijk",
    status: "kernlijn",
    name: "Team and project leaders",
    shortName: "Team leaders",
    proposition: "For team and project leaders who want clarity about which leadership role fits them.",
    heroTitle: "Leading others begins with knowing yourself",
    heroSubtitle: "For team and project leaders in that curious zone between contributing, steering and being a specialist — and who want clarity about which leadership role fits them.",
    ctaLabel: "Schedule an exploratory conversation",
    intro: "Team and project leaders are rarely in a clear-cut role. You contribute, you steer, you advise, you facilitate — all at once, and often without a formal management position. JANE helps you untangle this role confusion and determines which leadership mode works naturally for you.",
    recognition: [
      "You are technically strong but feel that leading costs energy rather than giving it.",
      "Your micromanagement reflex kicks in under pressure, even though you know it doesn’t work.",
      "You have no formal power over your team but do carry responsibility for results.",
      "You wonder whether leading really suits you, or whether you’d be better off staying an expert.",
    ],
    whatJaneDoes: [
      { title: "Clarity about your role mix.", body: "JANE exposes which functions work naturally for you — contributing, steering, facilitating, advising — and in what proportion." },
      { title: "Insight into stress patterns.", body: "What do you do as a project or team leader under pressure? Micromanage, take over, or let go entirely? JANE shows why — and what goes with it." },
      { title: "Distinguishing expert from leader.", body: "An important insight for many: are you a leader who happens to know a lot, or an expert who happens to lead? Both are valid, as long as it’s conscious." },
      { title: "A diagram you can share within your team.", body: "Unlike some other coaching programmes, JANE delivers a result your colleagues can understand — handy in matrix structures." },
    ],
    traject: [
      { step: "1", title: "Exploratory conversation", duration: "1 hour", what: "What is your role, what is your question, and does this programme fit." },
      { step: "2", title: "Step 1 — What I am not", duration: "1.5 hours + homework", what: "The parts of your role that are not yours." },
      { step: "3", title: "Step 2 — What I am", duration: "1.5 hours + homework", what: "Identifying your natural leadership functions." },
      { step: "4", title: "Step 3 — What holds me back", duration: "2 hours + homework", what: "Stress patterns, micromanagement reflex, expert trap." },
      { step: "5", title: "Leadership diagram + action plan", duration: "1.5 hours", what: "A concrete plan for your role over the coming 6 months." },
    ],
    forWhomYes: [
      "You lead a team or project, formally or informally.",
      "You often work in a matrix structure or without a clear hierarchy.",
      "You are willing to put your own patterns under the microscope.",
    ],
    forWhomNo: [
      "You are looking for project management training or technique.",
      "You expect coaching to raise your authority with your team without you changing.",
    ],
    method: "With ‘Unieke Bestemming Team- of Projectleider’ (2011) and the broader materials ‘Jane Adviseurs, Coaches en Trainers’, JANE has served this specific group for more than ten years. Clients are often technically skilled professionals who rolled into a leading role without consciously choosing it.",
    faq: [
      { q: "How does this relate to PRINCE2, Agile or Scrum training?", a: "Methodology trainings teach you how to manage a project or team. JANE shows how you do that and which patterns you bring along with it — complementary, not a replacement." },
      { q: "Does this also work for scrum masters or agile coaches?", a: "Particularly well. Their role is function-driven and non-hierarchical par excellence — exactly the context in which JANE delivers a lot." },
      { q: "How long does it take?", a: "Usually 8–10 weeks." },
    ],
    closingTitle: "A final step",
    closingText: "A leader who knows themselves doesn’t need to steer hard to get results. Schedule an exploratory conversation and discover which leadership function is yours.",
  },
  {
    slug: "echtparen",
    cluster: "relaties",
    status: "slapend",
    name: "Couples",
    shortName: "Couples",
    proposition: "For couples who want to understand themselves and each other better — as individuals and as a duo. Not couples therapy, but a deeper insight into your interplay.",
    heroTitle: "Two profiles, one relationship",
    heroSubtitle: "For couples who want to understand themselves and each other better — as individuals and as a duo. Not couples therapy, but a deeper insight into your interplay.",
    ctaLabel: "Schedule an introduction for the two of you",
    intro: "Couples who have been together longer often discover: ‘we’ve been having the same conversation for years now’. JANE doesn’t offer a solution for that, but it does offer a new language. By each getting to know your own Jane profile, you discover how two functions complement each other — and how you trigger each other’s blind spot. Not to fix something, but to understand something.",
    recognition: [
      "You notice the same discussions keep coming back — with the same division of roles.",
      "What attracted you to each other at the start now sometimes feels like the very source of friction.",
      "You want to understand yourselves better, both separately and together.",
      "You aren’t looking for therapy but for depth.",
    ],
    whatJaneDoes: [
      { title: "Two individual Jane profiles.", body: "First each of you completes your own programme separately — without any fuss about the relationship. That gives each of you a full personal diagram." },
      { title: "Dynamics analysis.", body: "Then we look at how your two profiles interact: where you complement each other, where you’re at odds, and how that plays out in practice." },
      { title: "A shared diagram.", body: "The programme ends with a ‘couple diagram’ that visually shows the two of you together — handy for looking back on conversational dynamics more consciously." },
      { title: "Conversation assignments for home.", body: "Between the sessions you work on small, concrete exercises that let the insights take root in practice." },
    ],
    traject: [
      { step: "1", title: "Introduction together", duration: "1 hour", what: "Both partners present. Exploring the question and the way of working." },
      { step: "2", title: "Individual programme — partner 1", duration: "3–4 sessions", what: "Three-step workshop, entirely personal." },
      { step: "3", title: "Individual programme — partner 2", duration: "3–4 sessions", what: "The same for the other partner. Can be parallel or sequential." },
      { step: "4", title: "Dynamics session 1", duration: "1.5 hours", what: "We lay the two profiles side by side and discuss complements and tensions." },
      { step: "5", title: "Dynamics session 2", duration: "1.5 hours", what: "Translation into concrete situations in your relationship." },
      { step: "6", title: "Conclusion", duration: "1 hour", what: "Couple diagram + advice for embedding." },
    ],
    forWhomYes: [
      "You are together, not (at this time) in a divorce process.",
      "Both partners want to take part, not one under pressure from the other.",
      "You are looking for insight, not problem-solving.",
    ],
    forWhomNo: [
      "There is an acute relationship crisis or breach of trust — couples therapy comes first there.",
      "One of you is sceptical or only takes part to accommodate the other.",
      "You expect a clear-cut outcome on whether you ‘belong together’.",
    ],
    method: "Couples programmes are a growth line within JANE. The method itself is proven at the individual level with hundreds of clients; the couple application is offered selectively and is expanded further on demand. Ask at intake about the most recent cases.",
    faq: [
      { q: "Is this therapy?", a: "No. This is an insight programme. If there is underlying problematic that requires therapy, we refer you on." },
      { q: "Can we do this without sharing each other’s outcomes?", a: "The individual part stays between you and the coach. During the dynamics sessions you share what you want to share — nothing is mandatory." },
      { q: "How long does the whole programme take?", a: "With two parallel personal programmes plus the two couple sessions, you arrive at 12–16 weeks." },
      { q: "Does this also work for LGBTQ+ couples?", a: "Yes. The Jane methodology is function-oriented and therefore not conditioned by gender or relationship form." },
    ],
    closingTitle: "A final step",
    closingText: "A relationship doesn’t get better by talking about the relationship — sometimes it gets better by talking about yourself. Schedule a no-obligation introduction together.",
  },
  {
    slug: "kleine-groepen",
    cluster: "relaties",
    status: "slapend",
    name: "Small groups",
    shortName: "Small groups",
    proposition: "For home groups, groups of friends or small teams who want to get to know each other’s gifts — and want to understand why the group does what it does.",
    heroTitle: "A group that knows each other’s function works differently",
    heroSubtitle: "For home groups, groups of friends or small teams who want to get to know each other’s gifts — and want to understand why the group does what it does.",
    ctaLabel: "Schedule a mini-workshop for your group",
    intro: "In every small group its own dynamic emerges: one person automatically takes the lead in conversation, one facilitates, one is always the doubter, one arranges the practical things. Often this happens unconsciously — sometimes at the expense of whoever does not take that spot. JANE for groups helps you learn to recognise each other’s functions, so everyone can fill their spot consciously.",
    recognition: [
      "You notice the same patterns keep occurring in your conversations.",
      "One or two people carry a disproportionate amount, while others remain untapped.",
      "You want to be more than a sociable group — a group with function.",
      "You’ve known each other for longer than a few months, and are now looking for depth.",
    ],
    whatJaneDoes: [
      { title: "A three-step mini-workshop.", body: "In one or two gatherings you go through a shortened version of the Jane method together." },
      { title: "Group diagram.", body: "The result is a visual diagram that shows all functions of all participants together — handy for seeing what makes the group strong as a whole." },
      { title: "Conversation assignments for within the group.", body: "Simple assignments that you can keep using yourselves to interact with each other more consciously." },
    ],
    traject: [
      { step: "1", title: "Preparatory conversation with the group leader", duration: "1 hour", what: "Taking stock of the group and the central question." },
      { step: "2", title: "Gathering 1 — Who we are not, who we are", duration: "2.5 hours", what: "The group goes through steps 1 and 2 together." },
      { step: "3", title: "Gathering 2 — What holds us back + diagram", duration: "2.5 hours", what: "Step 3 + building the group diagram." },
      { step: "4", title: "Follow-up after 6 weeks", duration: "1 hour, optionally online", what: "A short check-in to see how the insights are landing." },
    ],
    forWhomYes: [
      "You are a fixed group of 5–10 people.",
      "You have known each other for at least several months.",
      "You want depth, not just a first introduction.",
    ],
    forWhomNo: [
      "You have only just started as a group — wait 6 months.",
      "There is acute tension within the group — resolve that first.",
    ],
    method: "The group offering is an addition to the individual JANE programmes, developed at the request of home groups within, among others, the Familiekerk De Fakkel and Vision for Life participants.",
    faq: [
      { q: "Is everyone required to take part?", a: "We advise that all regular members take part — otherwise a skewed dynamic arises. When in doubt: come first with an introductory conversation." },
      { q: "Does this cost per person or for the whole group?", a: "For the whole group. The rate is independent of group size within 5–10 people." },
      { q: "Does this also work for non-Christian groups?", a: "Yes, the spiritual layer is included or left out according to the group’s wishes." },
    ],
    closingTitle: "A final step",
    closingText: "A group is more than its members. Schedule a mini-workshop for your group and discover what the composition actually is.",
  },
  {
    slug: "teams",
    cluster: "team",
    status: "groeilijn",
    name: "Teams in business or church",
    shortName: "Teams",
    proposition: "For teams that want to understand their collective strength — and their blind spot before it affects the work.",
    heroTitle: "A team is more than the sum of its functions",
    heroSubtitle: "For teams in business or church that want to understand their collective strength — and their blind spot before it affects the work.",
    ctaLabel: "Schedule an orientation with the team leader",
    intro: "A team operates on a layer above the individual profiles: patterns emerge that don't come from one person but from the combination. Some teams have the same compensating behavior as a whole — a collective blind spot. The Team Life Statement trajectory brings that collective layer into view and produces a shared statement about who this team is.",
    recognition: [
      "Your team delivers results, but the team leader feels there's more in it.",
      "Certain conversations keep recurring without anyone being able to name why.",
      "Under pressure you fall, as a team, into patterns nobody wants — and nobody can stop.",
      "You have the individual team members clearly in view, but not the collective.",
    ],
    whatJaneDoes: [
      { title: "Individual Jane profiles", body: "Beforehand, each team member completes their own short trajectory, so the offsite begins with clear personal starting points." },
      { title: "Team Blind Spot analysis", body: "At the offsite we lay the profiles side by side and identify the collective blind spot — patterns that arise from the combination." },
      { title: "Team Life Statement", body: "The team jointly formulates a statement about who it is, what its mission is, and which behaviors belong to that — and which don't." },
      { title: "Team diagram", body: "A visual summary that you can keep using in the team conversation." },
    ],
    traject: [
      { step: "1", title: "Orientation with the team leader", duration: "1.5 hours", what: "Assessment of whether the team is ready, and how we design the offsite." },
      { step: "2", title: "Individual profiles beforehand", duration: "Per team member, 2–3 sessions", what: "Everyone brings their own profile into the offsite." },
      { step: "3", title: "Offsite day", duration: "1 day (often off-site)", what: "Three blocks: laying out profiles, analyzing the blind spot, formulating the Life Statement." },
      { step: "4", title: "Team diagram + action plan", duration: "Closing block of the offsite", what: "Visual summary and concrete follow-up agreements." },
      { step: "5", title: "Follow-up after 3 and 6 months", duration: "2 × 2 hours", what: "Check-ins with the team to safeguard embedding." },
    ],
    forWhomYes: [
      "A team of 4–12 people that has worked together for at least 6 months.",
      "A team leader who is willing to take part themselves, not just observe.",
      "Enough trust within the team to be able to be vulnerable.",
    ],
    forWhomNo: [
      "A team in acute crisis or reorganization.",
      "A team where distrust or conflicts first require a different intervention.",
      "A team leader who 'imposes the trajectory on the team' without taking part.",
    ],
    method: "The Team Life Statement trajectory was realized in fully developed form for Villa Klarendal in November 2014 — a day that produced three coherent products (Team Blind Spot, Team Life Statement, Team Diagram). The method has been directly available since then but was used selectively. Ask at intake for the most recent cases.",
    faq: [
      { q: "What is the difference from an ordinary team offsite?", a: "An offsite is often goal-driven (vision, strategy). A Team Life Statement is identity-driven: who are we as a team. The outcomes are deeper and more lasting." },
      { q: "How large can a team be?", a: "Up to 12 people. Above that size we work with a phased approach where the cells each do their own trajectory separately and then come together." },
      { q: "Can we also do this online?", a: "The individual part, yes. The offsite day is deliberately physical — the added value of a whole day together in one room is methodologically important." },
    ],
    closingTitle: "A final step",
    closingText: "A team that knows its collective strength works differently. Schedule an orientation with you as team leader — after that we decide together whether the trajectory helps your team further.",
  },
  {
    slug: "oudstenteams",
    cluster: "team",
    status: "specialistisch",
    name: "Elder teams and church boards",
    shortName: "Elder teams",
    proposition: "For elder teams, church councils, and spiritual boards that stagnate in decision-making — or sense that their gifts aren't being consciously deployed.",
    heroTitle: "Decide on gifts, not on seniority",
    heroSubtitle: "For elder teams, church councils, and spiritual boards that stagnate in decision-making — or sense that their gifts aren't being consciously deployed.",
    ctaLabel: "Schedule a confidential conversation",
    intro: "Elder teams and church boards face a specific problem: decisions often turn implicitly on seniority, voting weight, or roles built up over a long time — while the actual gifts and functions in the team aren't being consciously deployed. JANE exposes who within the team holds which function, and helps you structure decisions on the basis of that reality.",
    recognition: [
      "You make decisions the congregation doesn't always go along with — or that you reverse yourselves after a while.",
      "Certain members of the team implicitly dominate, others remain underused.",
      "You notice that old role divisions no longer fit the congregation as it is now.",
      "A collective blind spot feels recognizable but can't be named.",
    ],
    whatJaneDoes: [
      { title: "Individual profiles for all board members", body: "A personal Jane profile for each member — often surprising compared to how the team thinks it knows one another." },
      { title: "Team diagram + collective blind spot", body: "The profiles together show what kind of decisions this team naturally makes — and which decisions it systematically avoids." },
      { title: "Working session 'how do we make decisions'", body: "Concrete agreements: who has which voice on which type of decision, and how do we make the implicit dynamic explicit." },
      { title: "Confidential setting", body: "The trajectory is internal and discreet — outcomes are shared only as the team itself chooses." },
    ],
    traject: [
      { step: "1", title: "Orientation with the chair", duration: "1.5 hours", what: "Assessment of the group, support, and how we safeguard confidentiality." },
      { step: "2", title: "Individual profiles", duration: "Per member, 2–3 sessions", what: "Personal trajectory for each team member." },
      { step: "3", title: "Team day", duration: "1 day off-site", what: "Laying out profiles, recognizing the blind spot, restructuring decision-making." },
      { step: "4", title: "Decision-making framework", duration: "Closing block of the team day", what: "Concrete agreements about how decisions are made." },
      { step: "5", title: "Follow-up after 6 months", duration: "Half a day", what: "Check whether the new structure works — any adjustments." },
    ],
    forWhomYes: [
      "An elder team, church council, or spiritual board that has worked together for 6+ months.",
      "Enough board-member-to-board-member trust to be vulnerable.",
      "Willingness to re-examine existing role divisions.",
    ],
    forWhomNo: [
      "The team is in the middle of a conflict over leadership — resolve that first.",
      "One member refuses to take part or only takes part under pressure.",
      "The team wants to 'meet more efficiently' without a fundamental reorientation.",
    ],
    method: "JANE has been used since 2007 with elder teams and governance layers of congregations, the earliest example being 'the Shelter Elder Team' (2007) and 'Jane proposal EC Europoort' (2006). The trajectory is suitable for Pentecostal, evangelical, free-evangelical, and Reformed congregations.",
    faq: [
      { q: "Does the entire elder council have to take part?", a: "Yes. One missing member makes the diagram incomplete and the working session less effective." },
      { q: "How confidential is this?", a: "Completely confidential within the team. Nothing is shared with the congregation or third parties without an explicit team agreement." },
      { q: "Is this an audit?", a: "No. It is an insight trajectory without judgment or advice about individuals. The outcomes are descriptive, not evaluative." },
      { q: "How long does the whole trajectory take?", a: "From orientation to follow-up: 4–6 months." },
    ],
    closingTitle: "A final step",
    closingText: "Deciding on gifts instead of on seniority can profoundly relieve an elder team. Schedule a confidential conversation with the chair — without obligations.",
  },
  {
    slug: "bedrijven-mkb",
    cluster: "team",
    status: "groeilijn",
    name: "SME organizations",
    shortName: "Businesses",
    proposition: "For SME organizations that want to base HR on actual functions and gifts — not on generic job profiles.",
    heroTitle: "People on their function, not on their title",
    heroSubtitle: "For SME organizations that want to base HR on actual functions and gifts — not on generic job profiles.",
    ctaLabel: "Schedule an introduction with management",
    intro: "Many HR instruments work from the organization toward the person: here is a job profile, who fits into it? JANE works the other way around: what is in this person, and how does that fit into our organization. For SME companies that want to recruit, develop, and compose teams in a person-centered way, that is a fundamentally different starting point.",
    recognition: [
      "You have high turnover or disengagement in roles where people 'fit on paper'.",
      "Recruitment feels like gambling — people seem the same but function completely differently.",
      "You have people who underperform in their role, but of whom everyone knows 'they're in the wrong seat'.",
      "You want more than a personality test in the recruitment process.",
    ],
    whatJaneDoes: [
      { title: "Jane Company functions as a framework", body: "The fully developed 'book 6 company functions with competency check' offers a framework that links the 27 Jane functions to concrete company roles and competencies." },
      { title: "Applicable in recruitment", body: "JANE is used for key positions to look beyond the CV and assessment center toward the actual function fit." },
      { title: "Applicable in development", body: "Existing employees gain, through a personal JANE trajectory, insight into the direction in which they can grow sustainably — often a different direction than the organization had expected." },
      { title: "Applicable in team composition", body: "When setting up new teams or reorganizations, JANE uses the profiles to deliberately compose a function portfolio." },
    ],
    traject: [
      { step: "1", title: "Introduction with management", duration: "1.5 hours", what: "What is your HR question, and does JANE fit as an instrument." },
      { step: "2", title: "Pilot — management or MT", duration: "Per person, 3–4 sessions", what: "Start with management or the management team itself, so you experience the instrument on yourselves first." },
      { step: "3", title: "Company implementation", duration: "Tailored", what: "Deployment in recruitment, development, or team composition, depending on priority." },
      { step: "4", title: "Train-the-trainer (optional)", duration: "Separate module", what: "For organizations that want to deploy JANE structurally: training of internal HR people." },
    ],
    forWhomYes: [
      "SME organizations of 20 to 250 employees.",
      "Management teams that see HR strategically, not as administration.",
      "Companies with a specific HR question (recruitment, internal mobility, team building).",
    ],
    forWhomNo: [
      "Organizations that mainly want to introduce standard job profiles.",
      "Companies that want to use JANE as a 'one-off screening instrument' — it is too far-reaching for that.",
      "Organizations in acute crisis where HR renewal does not fit right now.",
    ],
    method: "JANE has offered a business application for more than ten years under the names 'Jane Management Consultants' and 'Jane Advisers, Coaches and Trainers'. The business framework — book 6 company functions with competency check — is fully developed but is offered commercially on a selective basis.",
    faq: [
      { q: "Is this the same as an MBTI, Insights, or DISC implementation?", a: "Methodological overlap but deeper in substance. JANE works with 27 functions (vs. 4–16 types in other instruments) and looks explicitly at blind spot and compensation — not only at preferred style." },
      { q: "What does this cost for an organization?", a: "That depends on the scope: a pilot with the management team, a broad recruitment instrument, or an organization-wide implementation. Request a tailored quote." },
      { q: "Is JANE already being used organization-wide anywhere?", a: "JANE has been used selectively in SMEs and at a few non-profit organizations. Ask at intake for the most current cases." },
      { q: "Is JANE compatible with other HR instruments?", a: "Yes. JANE profiles are often used alongside standard instruments as an additional layer — not as a replacement." },
    ],
    closingTitle: "A final step",
    closingText: "Getting people onto their actual function is not a luxury but a return on investment. Schedule an introduction with your management — without obligation and with the scope determined in advance.",
  },
  {
    slug: "lokale-gemeentes",
    cluster: "advies",
    status: "specialistisch",
    name: "Congregations and church councils",
    shortName: "Congregations",
    proposition: "For congregations and church councils ready for a well-founded profile sketch and congregational vision, based on the gifts and functions actually present.",
    heroTitle: "Who is your congregation really — and where does that lead?",
    heroSubtitle: "For congregations and church councils ready for a well-founded profile sketch and congregational vision, based on the gifts and functions actually present.",
    ctaLabel: "Schedule an orientation with the church council",
    intro: "Writing a congregational vision without first knowing who the congregation is leads to general visions that no one commits to. JANE offers a methodical way to first map the congregation — survey, interviews, function analysis — and on that basis develop a congregational vision that truly fits who you are.",
    recognition: [
      "You want a congregational vision, but don't know where to begin.",
      "Earlier visions got stuck in generalities or were not supported.",
      "You notice that the congregation is changing but don't know exactly how.",
      "You want a foundation under policy decisions.",
    ],
    whatJaneDoes: [
      { title: "Survey among congregation members", body: "A standardized but congregation-specifically configured survey that maps functions, gifts, and involvement." },
      { title: "In-depth interviews with key people", body: "Additional conversations with elders, the pastor, leaders of working groups — to interpret the numbers." },
      { title: "Profile-sketch document", body: "A well-founded description of who this congregation is: composition of functions and gifts, strengths, blind spots, room for development." },
      { title: "Vision trajectory with the church council", body: "On the basis of the profile sketch, JANE guides the church council in developing a congregational vision that actually fits." },
    ],
    traject: [
      { step: "1", title: "Orientation with the church council", duration: "2 hours", what: "Scope determination, support, planning." },
      { step: "2", title: "Preparing the survey", duration: "1 month", what: "Tailored compilation, communication to the congregation, sending it out." },
      { step: "3", title: "Survey + interviews", duration: "1.5 months", what: "Fieldwork: having the survey completed, conducting interviews." },
      { step: "4", title: "Analysis and profile sketch", duration: "3–4 weeks", what: "Drawing up the report, first discussion with the church council." },
      { step: "5", title: "Vision trajectory", duration: "2–3 half-day sessions", what: "On the basis of the profile sketch, the church council builds the congregational vision." },
      { step: "6", title: "Presentation to the congregation", duration: "1 Sunday or evening", what: "The profile sketch and vision are given back to the congregation." },
    ],
    forWhomYes: [
      "A congregation with at least 80 involved members (otherwise the survey is statistically too thin).",
      "A church council willing to invest 6 months in this trajectory.",
      "Willingness to take the outcomes seriously — even when they are uncomfortable.",
    ],
    forWhomNo: [
      "Congregations in an acute conflict situation — resolve that first.",
      "Congregations that only want a 'vision document' for external use.",
      "Church councils not willing to invest a good 6 months.",
    ],
    method: "The profile-sketch trajectory has been carried out concretely at several congregations, including VEG Bennekom (three versions of the profile sketch) and PG Wassenaar (congregational vision). The method has been further developed via the VPE Region East survey and the programs 'Free to change'.",
    faq: [
      { q: "How much response do we need at a minimum?", a: "For congregations of 80–200 members we aim for at least 60% response. Below that threshold the picture is incomplete and we have to repeat or broaden the survey." },
      { q: "What if the profile sketch shows something uncomfortable?", a: "That is not a failure but precisely the intended insight. JANE provides descriptive insights and helps the church council interpret them meaningfully — no judgment." },
      { q: "How is the privacy of individual respondents safeguarded?", a: "The survey is anonymized. Interviews are conducted confidentially and reported only in anonymized form. No personally identifiable information leaves the analysis process." },
      { q: "What does this cost?", a: "Depending on congregation size and scope. Request a quote — on average 8,000–18,000 euros for the complete trajectory." },
    ],
    closingTitle: "A final step",
    closingText: "A congregational vision that is supported begins with knowing who you are. Schedule an orientation with the church council — entirely without obligation and with a concrete proposal as a follow-up.",
  },
  {
    slug: "internationaal",
    cluster: "internationaal",
    status: "slapend",
    name: "English-speaking audience",
    shortName: "International",
    proposition: "For English speakers who want to discover their unique calling and function — using a method developed over two decades in Dutch churches and businesses.",
    heroTitle: "JANE for the English-speaking world",
    heroSubtitle: "For English speakers who want to discover their unique calling and function — using a method developed over two decades in Dutch churches and businesses.",
    ctaLabel: "Schedule a discovery call (in English)",
    intro: "JANE is a methodology that has been used in the Netherlands for more than twenty years with hundreds of people — in congregations, with pastors, in SMEs, and with teams. The English-language variant is being built up: the translated 27 Jane functions and the three-step workshop are available, supported by direct English-language coaching.",
    recognition: [
      "You're an English speaker (expat, international, or non-Dutch) curious about your unique calling.",
      "You've taken personality tests but feel they only describe you, not direct you.",
      "You want a method with depth and history — not a marketing-driven framework.",
      "You're open to a coach speaking English directly, with Dutch-rooted methodology.",
    ],
    whatJaneDoes: [
      { title: "27 functions, translated and culture-sensitive", body: "The 27 Jane functions are translated to English, with cultural sensitivity to spiritual and secular contexts." },
      { title: "Three-step workshop in English", body: "The methodologically core workshop — Who am I not, Who am I, What's stopping me — delivered in English." },
      { title: "One-on-one coaching, in English", body: "Coaching sessions in clear English — for individuals, leaders, or sales professionals." },
      { title: "Optional: spiritual layer or business framing", body: "JANE works both as a spiritual instrument (gifts, fivefold ministry) and as a professional one (leadership, sales, career) — chosen at intake." },
    ],
    traject: [
      { step: "1", title: "Discovery call", duration: "1 hour", what: "Get to know each other, scope your question, decide if JANE fits." },
      { step: "2", title: "Step 1 — Who I am not", duration: "1.5 hours + home assignment", what: "Clarify the roles and functions that aren't really yours." },
      { step: "3", title: "Step 2 — Who I am", duration: "1.5 hours + home assignment", what: "Identify your core functions from the 27 Jane functions." },
      { step: "4", title: "Step 3 — What's stopping me", duration: "2 hours + home assignment", what: "Uncover compensation behavior and blind spots." },
      { step: "5", title: "Personal diagram", duration: "1.5 hours", what: "A visual summary you can use as a long-term reference point." },
    ],
    forWhomYes: [
      "You're an English-speaking professional, leader, or church member.",
      "You're ready for honest self-reflection.",
      "You value methodology with depth over quick personality assessments.",
    ],
    forWhomNo: [
      "You need a quick assessment for a job application.",
      "You're not open to spiritual or values-based dimensions of work and life.",
      "You're in an acute personal crisis — different support is needed first.",
    ],
    method: "JANE is a methodology developed over more than two decades by Dirk van der Schaaf, applied to hundreds of clients in Dutch churches and businesses. The English translation of the core 27 functions and the three-step methodology has been completed; international rollout is in selective onboarding phase.",
    faq: [
      { q: "Is this a Christian or secular method?", a: "Both. JANE has a spiritual root (gifts, fivefold ministry) and a professional application (leadership, sales, career). At intake you choose which layer is prominent for your trajectory." },
      { q: "How does this compare to MBTI, Enneagram, or CliftonStrengths?", a: "JANE is methodologically deeper (27 functions, not 4–16 types) and includes explicit attention to blind spots and compensation behavior — typically not present in personality assessments." },
      { q: "Can sessions be online?", a: "Yes, for individual trajectories online is the standard for international clients. Team trajectories ideally include at least one in-person day." },
      { q: "What's the cost?", a: "Pricing is per trajectory and aligned with international standards for executive coaching. Request a quote at the discovery call." },
    ],
    closingTitle: "A final step",
    closingText: "Discovering what you're made for deserves more than a test. Schedule a discovery call (in English) and explore whether JANE is your next step.",
  },
];
