import type { Locale } from "@/lib/i18n";

export interface Exercise {
  slug: string;
  group: string;
  name: string;
  goal: string;
  form: string;
  duration: string;
  materials: string;
  steps: string[];
  reflection: string[];
  coachTip?: string;
}

export interface ExerciseGroup {
  id: string;
  title: string;
  subtitle: string;
}

const groupsNl: ExerciseGroup[] = [
  { id: "universeel", title: "Universele oefeningen", subtitle: "Een goede start voor vrijwel iedereen" },
  { id: "gemeenteleden", title: "Gemeenteleden", subtitle: "Geestelijke bestemming ontdekken" },
  { id: "voorgangers", title: "Voorgangers en kerkleiders", subtitle: "Leiden vanuit eigen kern" },
  { id: "jongeren", title: "Jongeren en studiekeuze", subtitle: "Richting kiezen vanuit wie je bent" },
  { id: "loopbaan", title: "Loopbaan en heroriëntatie", subtitle: "Werk dat niet uitput" },
  { id: "managers", title: "Managers en leidinggevenden", subtitle: "Leiden vanuit je kern" },
  { id: "sales", title: "Sales-professionals", subtitle: "Verkopen vanuit echtheid" },
  { id: "teamleiders", title: "Team- en projectleiders", subtitle: "Rol-mix ontwarren" },
  { id: "echtparen", title: "Echtparen", subtitle: "Twee profielen, één relatie" },
  { id: "kleine-groepen", title: "Kleine groepen en huiskringen", subtitle: "Groepsdynamiek bewust maken" },
  { id: "teams", title: "Teams", subtitle: "Team Life Statement-traject" },
  { id: "oudstenteams", title: "Oudstenteams en kerkbesturen", subtitle: "Besluiten op gaven" },
  { id: "bedrijven", title: "Bedrijven en MKB-organisaties", subtitle: "HR vanuit talent" },
  { id: "gemeentes", title: "Lokale gemeentes", subtitle: "Profielschets en visievorming" },
  { id: "international", title: "International", subtitle: "JANE for English speakers" },
];

const groupsEn: ExerciseGroup[] = [
  { id: "universeel", title: "Universal exercises", subtitle: "A good start for almost anyone" },
  { id: "gemeenteleden", title: "Church members", subtitle: "Discovering your spiritual purpose" },
  { id: "voorgangers", title: "Pastors and church leaders", subtitle: "Leading from your own core" },
  { id: "jongeren", title: "Young people and study choice", subtitle: "Choosing direction from who you are" },
  { id: "loopbaan", title: "Career and reorientation", subtitle: "Work that does not drain you" },
  { id: "managers", title: "Managers and executives", subtitle: "Leading from your core" },
  { id: "sales", title: "Sales professionals", subtitle: "Selling from authenticity" },
  { id: "teamleiders", title: "Team and project leaders", subtitle: "Untangling the role mix" },
  { id: "echtparen", title: "Couples", subtitle: "Two profiles, one relationship" },
  { id: "kleine-groepen", title: "Small groups and home groups", subtitle: "Making group dynamics conscious" },
  { id: "teams", title: "Teams", subtitle: "Team Life Statement journey" },
  { id: "oudstenteams", title: "Elder teams and church boards", subtitle: "Deciding on gifts" },
  { id: "bedrijven", title: "Companies and SMEs", subtitle: "HR from talent" },
  { id: "gemeentes", title: "Local churches", subtitle: "Profile and vision forming" },
  { id: "international", title: "International", subtitle: "JANE for English speakers" },
];

const exercisesNl: Exercise[] = [
  {
    slug: "drie-talenten-in-de-spiegel",
    group: "universeel",
    name: "Drie talenten in de spiegel",
    goal: "Eerste indicatie krijgen van je drie sterkste talenten via eigen reflectie",
    form: "Individueel",
    duration: "20-30 minuten",
    materials: "Pen + papier, lijst van 27 talenten met korte beschrijving",
    steps: ["Pak de lijst van 27 talenten erbij en lees ze één voor één rustig door.", "Per talent: vraag jezelf 'Herken ik dit in mezelf?' Markeer met +, 0 of −.", "Bekijk alleen je plussen. Schrap de plussen waar je twijfelt totdat er 5-8 overblijven.", "Schrijf voor elk overgebleven talent op: een concrete situatie uit het laatste half jaar waarin dit talent zichtbaar was.", "Kies uit de overgebleven talenten je top-3 — degene waar de meeste concrete voorbeelden bij komen."],
    reflection: ["Welke talenten waren een verrassing — die je vergeten was bij jezelf?", "Welke talenten miste je in jezelf — die je had verwacht?", "Wat zegt je top-3 over wat jou energie geeft?"],
    coachTip: "Cliënten neigen ernaar te onderschatten wat ze hebben (vooral hoogopgeleide vrouwen) en te overschatten wat ze missen. Vraag bij de tweede ronde naar concrete situaties — die maken het hard.",
  },
  {
    slug: "drie-naasten-als-talent-spiegel",
    group: "universeel",
    name: "Drie naasten als talent-spiegel",
    goal: "Externe validatie van je vermoedde talenten via mensen die je goed kennen",
    form: "Individueel + drie korte gesprekken",
    duration: "Een week, met losse momenten",
    materials: "Lijst van 27 talenten om mee te delen",
    steps: ["Kies drie mensen die jou goed kennen, uit verschillende contexten (bijvoorbeeld partner, collega, vriend uit jeugd).", "Vraag elk: 'Welke 5 talenten uit deze lijst herken je het sterkst in mij?'", "Geef ze de lijst en laat ze 24 uur de tijd. Stuur de lijst per app of mail.", "Verzamel de antwoorden in een tabel — welke talenten worden meermaals genoemd?", "Vergelijk met je eigen top-3 uit de spiegel-oefening: waar overlapt het, waar verschilt het?"],
    reflection: ["Welke talenten werden door alle drie genoemd? Dat zijn waarschijnlijk je sterksten.", "Welke talenten herkende je zelf niet maar wel anderen? Onderscha je iets?", "Welke talenten dacht je te hebben maar werden door niemand genoemd?"],
    coachTip: "Het krachtigst is wanneer drie mensen uit verschillende werelden dezelfde 2-3 talenten noemen. Die zijn dan vrijwel zeker écht aanwezig.",
  },
  {
    slug: "het-energie-dagboek",
    group: "universeel",
    name: "Het energie-dagboek",
    goal: "Praktisch in beeld brengen welke activiteiten energie geven en welke leegtrekken",
    form: "Individueel",
    duration: "Een week, paar minuten per dag",
    materials: "Klein notitieboekje of notitie-app",
    steps: ["Houd één week elke werkdag bij: welke activiteit deed je vandaag, en met welk energieniveau eindigde je (1-10).", "Markeer per activiteit met + (gaf energie), 0 (neutraal) of − (kostte energie).", "Aan het einde van de week: welke activiteiten kregen consequent een + en welke een −?", "Voor elke + activiteit: welke 1-2 talenten zat hierin? (Gebruik de 27 talenten lijst).", "Voor elke − activiteit: welk talent ontbreekt waarschijnlijk bij jou, waardoor het zoveel energie kost?"],
    reflection: ["Komt jouw + talenten-overlap overeen met je top-3 uit eerdere oefeningen?", "Welke − activiteiten zou je kunnen delegeren aan iemand met dat talent?", "Wat zou er gebeuren als je 80% van je tijd zou besteden aan + activiteiten?"],
  },
  {
    slug: "de-drie-stappen-zelfworkshop-verkort",
    group: "universeel",
    name: "De drie-stappen-zelfworkshop (verkort)",
    goal: "Een vereenvoudigde versie van het hoofdtraject doorlopen — eerste kennismaking",
    form: "Individueel",
    duration: "Drie sessies van 45 min, één per week",
    materials: "Lijst 27 talenten + lege werkbladen",
    steps: ["Sessie 1 — Wie ben ik niet: doorloop de 27 talenten en kruis 8-12 aan die níet bij jou horen. Beschrijf per uitgesloten talent een situatie waarin je het ontbreken voelde.", "Sessie 2 — Wie ben ik wel: kies uit de overgebleven 15-19 talenten je 5-8 sterksten. Beschrijf wat ze in combinatie maken.", "Sessie 3 — Wat houdt me tegen: kijk welk talent je het laagste scoort. Welk vervangend gedrag zet je daarvoor in? Hoe lang doe je dat al?", "Schrijf na elke sessie 1 alinea op over wat je hebt geleerd.", "Bewaar de drie werkbladen — ze vormen de basis voor een latere coaching met een gecertificeerde coach."],
    reflection: ["Welke stap was het moeilijkst, en waarom?", "Voelde je weerstand bij bepaalde inzichten? Bij welke?", "Wat zou je willen vragen aan een coach om dit verder uit te diepen?"],
    coachTip: "Deze verkorte versie vervangt geen volledige coaching, maar geeft een serieus eerste beeld. Goed als startpunt of als zelf-onderzoek tussen sessies.",
  },
  {
    slug: "talent-gave-koppeling",
    group: "gemeenteleden",
    name: "Talent-gave-koppeling",
    goal: "Verbinden van je natuurlijke talent met je geestelijke gave",
    form: "Individueel of in een huiskring",
    duration: "60 minuten",
    materials: "Talenten-lijst + lijst van 35 gaventeksten",
    steps: ["Begin met je 3 sterkste talenten (uit de spiegel-oefening of na een JANE-test).", "Pak de gave-koppeling-tabel erbij: A1 → gave van kennis, B1 → spreken in tongen, C1 → gave van het geven, etc.", "Lees voor elk van je 3 talenten de gekoppelde gave-tekst rustig door.", "Vraag jezelf per gave: 'Heb ik momenten ervaren waarin God dit door mij heen werkte?'", "Schrijf per gave één concrete ervaring op waar God dit gebruikte."],
    reflection: ["Welke gave herken je het sterkst — niet als ambitie maar als ervaring?", "Wat zou er anders gaan in je leven als je deze gave bewust ging inzetten?", "Wie in jouw gemeente zou jou kunnen helpen deze gave verder te ontwikkelen?"],
    coachTip: "Bij twijfel of iets een gave is: vraag mensen die jou kennen of zij God door jou hebben zien werken. Zelf-herkenning is moeilijker dan herkenning door anderen.",
  },
  {
    slug: "mijn-plek-in-dit-lichaam",
    group: "gemeenteleden",
    name: "Mijn plek in dit lichaam",
    goal: "Identificeren waar in de gemeente jouw functie het meest waardevol is",
    form: "Individueel, met optionele bespreking met oudste",
    duration: "90 minuten",
    materials: "Overzicht van werkgroepen / bedieningen in jouw gemeente",
    steps: ["Maak een lijst van alle werkgroepen, taken en bedieningen in jouw gemeente (bezoekwerk, jeugd, muziek, koffie, gebed, onderwijs, evangelisatie, etc.).", "Per werkgroep: welke 2-3 talenten zijn daar het meest nodig? Maak een matrix.", "Markeer de werkgroepen waar jouw top-3 talenten matchen met de gevraagde talenten.", "Sluit nu uit: welke werkgroepen doe je al, maar past niet bij je top-3? Overweeg waarom.", "Wat is de werkgroep waar jouw talenten het sterkst tot bloei zouden komen, maar waar je nog niet bent? Schrijf 1 stap op die je kunt zetten."],
    reflection: ["Klopt je huidige bediening met je talenten? Of doe je iets waar je weinig in zit?", "Wat houdt je tegen om de bediening op te pakken die wel bij je past?", "Wie zou je hierover kunnen aanspreken — een oudste, voorganger, of werkgroepleider?"],
  },
  {
    slug: "de-gaventekst-meditatie",
    group: "gemeenteleden",
    name: "De gaventekst-meditatie",
    goal: "Diepere reflectie op één specifieke geestelijke gave",
    form: "Individueel, met dagboek-momenten",
    duration: "Een week, dagelijks 15 minuten",
    materials: "Gaventekst voor één gekozen gave",
    steps: ["Kies één gave-tekst (a1 t/m c9) die past bij een van je top-talenten.", "Lees de tekst dag 1 en schrijf op: 'Wat herken ik hier?'", "Dag 2: 'Waar in mijn leven werkt deze gave al?'", "Dag 3: 'Waar zou ik deze gave bewuster kunnen inzetten?'", "Dag 4: 'Wat houdt me tegen om dit te doen?'", "Dag 5: 'Hoe wil ik dit komend kwartaal stap-voor-stap gaan oppakken?'", "Dag 7: vat samen wat je hebt ontdekt."],
    reflection: ["Welk concreet voornemen heeft deze week opgeleverd?", "Wie wil je hier vandaag of deze week mee in gesprek over?"],
  },
  {
    slug: "mijn-geestelijke-biografie",
    group: "gemeenteleden",
    name: "Mijn geestelijke biografie",
    goal: "Patronen in je geestelijke leven herkennen die hoe God je heeft gevormd",
    form: "Individueel — schrijfoefening",
    duration: "120 minuten",
    materials: "Pen + papier, rustige plek",
    steps: ["Verdeel je leven in 4-5 fases (kindertijd, jeugd, vroege volwassenheid, etc.).", "Schrijf per fase: 'Wat deed ik graag? Waar kwam ik tot bloei? Waar voelde ik me niet thuis?'", "Identificeer per fase de 1-2 talenten die in die fase zichtbaar waren.", "Welke talenten lopen door alle fases heen? Dat zijn waarschijnlijk je kerntalenten.", "Schrijf één paragraaf over: 'De rode draad in mijn leven, wat God daarmee deed, en waar dit naartoe lijkt te leiden.'"],
    reflection: ["Was de rode draad een verrassing of wist je hem al?", "Welke fasen had je nodig om de huidige bestemming te ontdekken?", "Wat zou de volgende fase kunnen zijn? kern Voor voorgangers, oudsten en kerkleiders. Het accent ligt op stap 3 (blinde vlek), op de vraag wat van jouw rol echt van jou is en wat aangeleerd is, en op de vijfvoudige bediening als positioneringskader."],
  },
  {
    slug: "aangeleerd-versus-eigen-de-voorganger-spiegel",
    group: "voorgangers",
    name: "Aangeleerd versus eigen — de voorganger-spiegel",
    goal: "Onderscheiden welke delen van je voorgangersrol bij je passen en welke aangeleerd zijn",
    form: "Individueel, vertrouwelijk",
    duration: "90 minuten",
    materials: "Pen + papier, lege agenda van vorige week",
    steps: ["Maak een lijst van alle taken die je vorige week deed (predikatie, pastorale gesprekken, vergaderingen, administratie, etc.).", "Markeer per taak: + (gaf energie), 0 (neutraal), − (kostte veel energie).", "Schrijf voor elke − taak op: 'Vanuit welke verwachting doe ik dit? Van mezelf, de gemeente, of de traditie?'", "Welke − taken doe je omdat je vindt dat een 'goede voorganger dat hoort te doen' — niet omdat ze bij jou passen?", "Voor elke − taak: wie in jouw netwerk of gemeente heeft dit talent wel, en zou dit kunnen oppakken?"],
    reflection: ["Hoeveel procent van je tijd ging vorige week naar + activiteiten?", "Welke − activiteit zou je het meest willen loslaten — en wat houdt je tegen?", "Wat zou je gemeente merken als je 80% van je tijd uit je sterktes werkte?"],
    coachTip: "Voor voorgangers is dit vaak de meest bevrijdende oefening. Het vraagt om vertrouwen dat het delegeren mag — en mogelijk om een gesprek met de oudsten over taakverdeling.",
  },
  {
    slug: "vijfvoudige-bediening-waar-zit-jij",
    group: "voorgangers",
    name: "Vijfvoudige bediening — waar zit jij?",
    goal: "Helder krijgen of je primair apostel, profeet, evangelist, herder of leraar bent",
    form: "Individueel + bespreking met geestelijk begeleider",
    duration: "120 minuten",
    materials: "Beschrijving van de vijfvoudige bediening (Efeze 4)",
    steps: ["Lees rustig de 5 functies door: apostel (pionier), profeet (richtingaanwijzer), evangelist (boodschapper), herder (zorgdrager), leraar (uitdiepiger).", "Voor elke functie: waar herken je jezelf 'hoog', waar 'laag'?", "Welke functie kost je het minst moeite en geeft je natuurlijk energie? Dat is waarschijnlijk je primaire bediening.", "Welke combinatie maakt jou? Bijna niemand is puur één — meeste zijn een combinatie van twee.", "Welke functie krijg je in je gemeente vooral toegewezen? Klopt dat met je natuurlijke?"],
    reflection: ["Als je primair pioneer bent maar pastoraal werk moet doen — waar trekt dat?", "Welke functie misnen anderen in de gemeente, die jij wel hebt?", "Welke functie heeft je gemeente nodig die niemand vervult?"],
  },
  {
    slug: "mijn-blinde-vlek-als-voorganger",
    group: "voorgangers",
    name: "Mijn blinde vlek als voorganger",
    goal: "Onderzoeken welk compensatiegedrag je inzet en hoe dat de gemeente beïnvloedt",
    form: "Individueel, optioneel met supervisor",
    duration: "Vier sessies van 1 uur, één per week",
    materials: "Coach-dossier (vertrouwelijk)",
    steps: ["Sessie 1 — Identificatie: kijk naar je 27-talenten-profiel. Welk talent scoor je het laagste? Welke score had je verwacht?", "Sessie 2 — Compensatie: welk overmatig gedrag zet je in als dit talent ontbreekt? Vraag 2-3 vertrouwde mensen om hierop te reflecteren.", "Sessie 3 — Effect op gemeente: welke patronen in de gemeente zijn (mogelijk) het gevolg van jouw compensatie?", "Sessie 4 — Wie zou jou kunnen aanvullen? Identificeer 1-2 mensen die jouw blinde vlek- talent wel sterk hebben. Wat zou structureel overleg met hen kunnen opleveren?"],
    reflection: ["Was de blinde vlek een verrassing of wist je hem al?", "Welke specifieke situatie zou je willen onderzoeken als 'aha-moment'?", "Wat zou de gemeente winnen als jij je blinde vlek erkende en aanvulde?"],
    coachTip: "Voor voorgangers is supervisie hier extra belangrijk. De blinde vlek is een vertrouwelijk gegeven dat niet zomaar in de oudstenraad bespreekbaar moet zijn — eerst persoonlijk verwerken.",
  },
  {
    slug: "de-5b-score-jouw-leiderschapsindex",
    group: "voorgangers",
    name: "De 5b-score — jouw leiderschapsindex",
    goal: "Berekenen van je natuurlijke leiderschapsbasis (Dirk's 5b-score)",
    form: "Individueel, na een JANE-test",
    duration: "30 minuten",
    materials: "JANE-testresultaten",
    steps: ["Pak je scores op deze vijf talenten: B5 Contact, C3 Uitleg (Docent), B3 Argumentatie, C5 Correctie, A7 Route.", "Tel ze op en bereken het gemiddelde. Dit is je 5b-score.", "Hoge score (>70%) = sterke natuurlijke leiderschapsbasis. Lage score (<50%) = leiderschap kost je structureel meer energie dan een ander.", "Welke van de 5 zit het hoogst? En welke het laagst? Dat bepaalt jouw leiderschapsstijl.", "Spiegel met de vijfvoudige bediening: hoog Contact + hoog Correctie → vaak herders/leraars. Hoog Argumentatie + hoog Route → vaak apostelen/evangelisten."],
    reflection: ["Klopt je 5b-score met hoe leiderschap voor jou voelt — energiegevend of vermoeiend?", "Als één van de 5 laag is, wie in je oudstenteam of gemeente heeft dat wel?", "Hoe zou jouw leiderschap zich ontwikkelen als je bewust met je hoogste twee zou werken? je bent Voor jongeren tussen 16 en 25 die studie- of werkkeuzes moeten maken. Lichte, visuele werkvormen die aansluiten bij jongere taalveld en levensvraag."],
  },
  {
    slug: "talent-jachtfoto",
    group: "jongeren",
    name: "Talent-jachtfoto",
    goal: "Op een visuele manier je sterkste talenten ontdekken via momenten",
    form: "Individueel — visueel",
    duration: "60 minuten",
    materials: "Telefoon met fotorol, of oude foto's",
    steps: ["Scroll terug in je fotorol en kies 10 foto's die een moment vastleggen waarin jij echt 'aan' was — energiek, betrokken, jezelf.", "Per foto: welke activiteit was dat? Wat deed je precies? (sport, met vrienden, een project, helpen, presenteren, etc.)", "Per activiteit: welk talent uit de 27 zit hierin? Schrijf het op de achterkant of in een lijst.", "Welke talenten komen meermaals voor over je 10 foto's? Dat zijn waarschijnlijk je top-3.", "Vraag een vriend of ouder: 'Herken je deze top-3 in mij?' Bespreek de antwoorden."],
    reflection: ["Welk talent kwam vaker terug dan je had verwacht?", "Welke situaties zou je vaker willen opzoeken?", "Wat zegt dit over wat voor studie of werk bij je zou passen?"],
  },
  {
    slug: "vakken-vs-talenten-matrix",
    group: "jongeren",
    name: "Vakken-vs-talenten-matrix",
    goal: "Studierichting kiezen vanuit talent in plaats van vanuit vak",
    form: "Individueel + bespreking met ouder/mentor",
    duration: "90 minuten",
    materials: "Lijst van mogelijke studierichtingen (max 10)",
    steps: ["Maak een lijst van 5-10 studierichtingen of werkvelden die in je hoofd hebben gespeeld.", "Maak een matrix: jouw top-5 talenten in de kolommen, studierichtingen in de rijen.", "Per studierichting: hoeveel van jouw top-5 talenten worden in die studie/dat werk gebruikt? Geef een score 0-5.", "Studies met score 4-5 zijn potentiële goede matches. Studies met score 0-1 zullen je leegtrekken, ook al klinken ze interessant.", "Voor je top-3 matches: zoek 1 persoon op die deze studie doet/dit werk heeft. Vraag in een gesprek welke 5 talenten zij dagelijks gebruiken."],
    reflection: ["Welke studie had je in je hoofd maar bleek minder dan een 3-match?", "Welke studie had je niet bedacht maar bleek een 4-5 match?", "Wat is je volgende concrete stap?"],
    coachTip: "Voor ouders: niet meteen je eigen verwachtingen erop loslaten. Laat je kind zelf de matches benoemen en wees luisteraar, niet richter.",
  },
  {
    slug: "jezelf-interviewen-in-10-jaar",
    group: "jongeren",
    name: "Jezelf interviewen in 10 jaar",
    goal: "Toekomstige bestemming verkennen vanuit verlangen",
    form: "Individueel — schrijfoefening",
    duration: "45 minuten",
    materials: "",
    steps: ["Stel je voor: het is over 10 jaar. Je hebt een leven dat helemaal bij je past.", "Schrijf vrij — niet zoeken naar 'het juiste antwoord' — op: 'Waar woon ik? Wat doe ik dagelijks? Met wie? Wat geeft me energie?'", "Lees terug. Welke talenten zou je op 28-30 jarige leeftijd het sterkst inzetten?", "Welke kleine eerste stap zou je morgen kunnen zetten in die richting?", "Schrijf de stap concreet op (niet 'oriënteren' maar bijvoorbeeld 'volgende dinsdag bel ik X')."],
    reflection: ["Was er iets in je toekomstbeeld dat je verraste?", "Welk talent kwam erin terug dat je nu nog niet veel gebruikt?", "Welke obstakels zie je tussen nu en die toekomst?"],
  },
  {
    slug: "het-ouder-gesprek",
    group: "jongeren",
    name: "Het ouder-gesprek",
    goal: "Ouders meekrijgen in een talent-gerichte (in plaats van studie-gerichte) benadering",
    form: "Gezamenlijk gesprek met ouder(s)",
    duration: "90 minuten",
    materials: "Resultaten van eerdere oefeningen + lijst 27 talenten",
    steps: ["Begin het gesprek met: 'Ik wil mijn keuze niet maken vanuit welke studie verstandig is, maar vanuit welke talenten echt bij me horen.'", "Deel je top-3 talenten en de concrete voorbeelden die je daarbij hebt gevonden.", "Vraag je ouder(s): 'Herkennen jullie deze talenten in mij? Welke andere talenten zien jullie?'", "Bespreek samen je vakken-vs-talenten-matrix. Welke matches zien je ouders die jij niet hebt gemaakt?", "Sluit af met: 'Welke 1 stap zou ik komende maand moeten zetten?'"],
    reflection: ["Wat verraste je in wat je ouders zeiden?", "Wat botste — en hoe gaan jullie daarmee om?", "Wat is jullie gezamenlijk volgende moment?"],
    coachTip: "Voor de coach: bereid de jongere voor op mogelijk teleurstelling als ouders niet meegaan. Dat hoort erbij; het talent-gesprek hoeft niet meteen consensus op te leveren. Voor mensen in loopbaanvragen, post-burnout, of carrière-heroriëntatie. De oefeningen zijn delen van het vijfsessie loopbaantraject 'Vind je beste functie'.",
  },
  {
    slug: "patroon-analyse-vorige-banen",
    group: "loopbaan",
    name: "Patroon-analyse vorige banen",
    goal: "De rode draad vinden in waarom eerdere banen wel of niet werkten",
    form: "Individueel — schrijfoefening",
    duration: "120 minuten",
    materials: "Eigen CV + 2 uur rust",
    steps: ["Maak een tijdlijn van alle banen die je hebt gehad (ook bijbanen).", "Per baan: '+ als ik er met plezier aan terugdenk, − als het pijn deed, 0 als neutraal.'", "Per + baan: welke 2-3 elementen maakten het werk? (autonomie? mensen? complexiteit? structuur?)", "Per − baan: welke 2-3 elementen maakten dat het niet werkte?", "Kijk naar het patroon: welke elementen komen terug bij + en welke bij −?", "Vertaal elk patroon-element naar 1-2 talenten uit de 27."],
    reflection: ["Welke talenten heb je consequent niet gebruikt in je − banen?", "Welke talenten waren wel sterk aanwezig in + banen?", "Wat is het patroon dat bepaald heeft of je werk wel of niet werkte?"],
    coachTip: "Vaak ontdekt iemand dat het probleem niet de sector was maar de werkstijl-elementen. Iemand kan in dezelfde functie wel of niet bloeien afhankelijk van wie de baas is.",
  },
  {
    slug: "talent-matrix-per-functietype",
    group: "loopbaan",
    name: "Talent-matrix per functietype",
    goal: "Concrete functies in beeld brengen die bij jouw talenten passen",
    form: "Individueel",
    duration: "90 minuten",
    materials: "Lijst van 27 Jane-functies (per cluster Lijn/Project/Verander)",
    steps: ["Pak het overzicht van de 27 functies. Per functie staat het talent-DNA: welke 6 talenten zijn nodig.", "Streep door functies waar 3+ van jouw top-talenten ontbreken — die zijn geen match.", "Markeer functies waar 3+ van jouw top-talenten in voorkomen — die zijn potentiële matches.", "Voor je top-3 functies: zoek 1 persoon die deze functie heeft en plan een koffie-gesprek van 30 min.", "Vraag in dat gesprek: 'Welke talenten gebruik je dagelijks? Wat geeft je energie? Wat trekt je leeg?'"],
    reflection: ["Welke functie verraste je positief?", "Welke functie had je in je hoofd, maar bleek geen match?", "Wat is je volgende concrete stap?"],
  },
  {
    slug: "cultuur-fit-bepaling",
    group: "loopbaan",
    name: "Cultuur-fit-bepaling",
    goal: "Bepalen of je beter past in een Lijn-, Project- of Veranderfunctie",
    form: "Individueel",
    duration: "45 minuten",
    materials: "Beschrijving 3 organisatieculturen",
    steps: ["Lees de drie cultuur-beschrijvingen rustig door: Lijn (continuïteit, vaste team), Project (verbetering, deadlines, wisselende teams), Verander (groei, lange termijn, diverse gesprekspartners).", "Per cultuur: scoor op een schaal 1-10 hoe je je daarbij thuis voelt.", "Per cultuur: schrijf op welke baan-situatie uit je verleden in die cultuur paste — en hoe je je daar voelde.", "Identificeer de cultuur waar je je het meeste thuis voelt en waarom.", "Combineer met je talent-matrix: in welke cultuur passen je top-functies?"],
    reflection: ["Heb je tot nu toe in de juiste cultuur gewerkt voor jouw type?", "Welke verandering qua cultuur zou meer energie geven dan dezelfde baan in een andere context?"],
  },
  {
    slug: "vijfsessie-loopbaantraject-zelfstudie",
    group: "loopbaan",
    name: "Vijfsessie loopbaantraject (zelfstudie)",
    goal: "De officiele loopbaan-methodiek 'Vind je beste functie' zelf doorlopen",
    form: "Individueel, vijf sessies",
    duration: "Vijf weken, 1.5 uur per week",
    materials: "Werkbladen voor elke sessie",
    steps: ["Sessie 1 — Programma-introductie: definieer je centrale loopbaanvraag in één zin.", "Sessie 2 — Vind je beste functie: gebruik talent-matrix om 3-5 passende functies te identificeren.", "Sessie 3 — Identificeer passende organisaties: per functie 3 typen organisaties / sectoren matchen.", "Sessie 4 — CV en marktbenadering: herschrijf je CV vanuit je talenten (niet vanuit je werkervaring).", "Sessie 5 — Loopbaanactieplan: 5 concrete stappen voor de komende 3 maanden."],
    reflection: ["Welke sessie leverde de belangrijkste inzichten op?", "Welke aanname over jezelf is in dit traject gesneuveld?", "Wat is je nieuwe formuleer-zin voor jezelf: 'Ik ben iemand die...' ?"],
    coachTip: "Voor een coach: dit zelfstudie-traject kan ook in 5 sessies van 90 minuten met een coach worden gedaan. Dat geeft snellere voortgang en betere reflectie tussen sessies. Voor leidinggevenden die hun aangeleerde managementstijl willen afstropen en naar hun eigen leiderschapsfunctie willen — en die willen herkennen welke blinde vlek hun team beïnvloedt.",
  },
  {
    slug: "manager-rol-spiegel",
    group: "managers",
    name: "Manager-rol-spiegel",
    goal: "Onderscheiden welke onderdelen van je managerrol bij je passen en welke aangeleerd zijn",
    form: "Individueel, vertrouwelijk",
    duration: "75 minuten",
    materials: "Agenda van vorige twee weken",
    steps: ["Maak een lijst van alle managementtaken die je in de afgelopen twee weken hebt gedaan (1- op-1's, meetings leiden, beoordelingen, strategieverhalen, etc.).", "Per taak: + (gaf energie), 0, − (kostte veel).", "Voor elke − taak: 'Doe ik dit omdat het bij mij past, of omdat ik vind dat een manager dit hoort te doen?'", "Voor elke − taak: welk talent zou nodig zijn om dit met plezier te doen — en heb je dat?", "Welke − taken kun je delegeren of anders inrichten?"],
    reflection: ["Welk percentage van je managementtijd ging naar + activiteiten?", "Welke aangeleerde rol kost je het meeste — en wat zou er gebeuren als je hem losliet?", "Welke 'best practice' uit je opleiding past eigenlijk niet bij je natuur?"],
    coachTip: "Veel managers ontdekken dat 30-40% van hun tijd naar aangeleerde rolinvulling gaat. Dat is geen falen — het is een teken dat een herontwerp van de rol mogelijk is.",
  },
  {
    slug: "stress-patronen-identificatie",
    group: "managers",
    name: "Stress-patronen identificatie",
    goal: "Erkennen welk compensatiegedrag je inzet onder druk en welke impact het op je team heeft",
    form: "Individueel, daarna 360-feedback",
    duration: "Drie weken",
    materials: "Notitieboek + 3 vertrouwde teamleden",
    steps: ["Week 1 — Zelf-observatie: noteer dagelijks situaties waarin je je 'gespannen' of 'overweldigd' voelde. Wat deed je toen?", "Week 1 — Patroon: kijk na 5 dagen of er een herhalend gedragspatroon is. Hoe heet dat patroon in jouw eigen woorden?", "Week 2 — 360: vraag 3 teamleden afzonderlijk: 'Wat doe ik systematisch onder druk? Welk effect heeft dat op het team?'", "Week 2 — Vergelijk: komt jouw zelf-observatie overeen met wat het team ziet?", "Week 3 — Plan: schrijf 1 zin op voor jezelf wanneer je het patroon weer voelt opkomen ('In plaats van X ga ik Y proberen')."],
    reflection: ["Was je stress-patroon nieuw voor jou, of wist je hem al?", "Welk effect had jouw patroon op het team dat je niet eerder zag?", "Wat zou er veranderen in het team als jij je patroon kunt onderbreken?"],
  },
  {
    slug: "team-life-statement-gefaseerd",
    group: "managers",
    name: "Team Life Statement (gefaseerd)",
    goal: "Met je directe team de collectieve sterkte en blinde vlek in kaart brengen",
    form: "Team-traject (4-12 personen)",
    duration: "Voorbereiding 4 weken + 1 offsite-dag + 2 follow-up sessies",
    materials: "Individuele JANE-resultaten + offsite-locatie",
    steps: ["Voorbereiding: elk teamlid doorloopt een persoonlijk JANE-traject (4-6 weken).", "Offsite-dag — Blok 1 (ochtend): individuele profielen worden naast elkaar gelegd. Wat valt op aan de combinatie?", "Offsite-dag — Blok 2 (middag): identificeer de collectieve blinde vlek — welke talenten ontbreken in het team?", "Offsite-dag — Blok 3 (avond): formuleer een Team Life Statement: wie zijn we als team, wat is onze opdracht, welke gedragingen horen daarbij?", "Follow-up na 3 maanden: leeft de Team Life Statement nog? Wat is er gerealiseerd?", "Follow-up na 6 maanden: definitief verankerd of bijstellen?"],
    reflection: ["Welke collectieve sterkte was een verrassing?", "Welke collectieve blinde vlek herken je nu in patronen die het team al jaren laat zien?", "Wat zou er voor het team veranderen als de blinde vlek wordt aangevuld?"],
    coachTip: "Dit traject vraagt een externe facilitator — een JANE Coach met team-specialisatie. Het kan niet door de teamleider zelf worden geleid zonder verlies van veiligheid.",
  },
  {
    slug: "talent-portfolio-van-je-directe-rapporteurs",
    group: "managers",
    name: "Talent-portfolio van je directe rapporteurs",
    goal: "Bewust maken van wie in je team welke talenten heeft en welke ontbreken",
    form: "Individueel — analyse",
    duration: "60 minuten",
    materials: "Lijst directe rapporteurs + 27 talenten",
    steps: ["Maak een matrix: je teamleden in de kolommen, de 27 talenten in de rijen.", "Per teamlid: markeer 5 talenten waarvan je vermoedt dat ze sterk zijn.", "Som per talent op: hoeveel teamleden hebben dit talent sterk?", "Welke talenten zijn collectief sterk in je team? Welke ontbreken bij iedereen?", "Voor de ontbrekende talenten: wat is het effect op het team-functioneren?"],
    reflection: ["Welke talenten ontbreken die het team echt mist?", "Welk talent heb jij maar niemand anders — waardoor jij onmisbaar lijkt?", "Welke wervingscriteria zou je voor de volgende aanstelling toepassen op basis hiervan? Voor sales-professionals die targets halen maar er energie aan kwijtraken. Oefeningen om je natuurlijke sales-functie te ontdekken en compensatiegedrag te herkennen."],
  },
  {
    slug: "sales-energie-dagboek",
    group: "sales",
    name: "Sales-energie-dagboek",
    goal: "Per type sales-activiteit zien wat je energie geeft en wat je leegtrekt",
    form: "Individueel — twee weken",
    duration: "Twee weken, 5 minuten per dag",
    materials: "Notitie-app",
    steps: ["Twee weken lang: noteer dagelijks per sales-activiteit het type (koud bellen, klantbezoek, offerte schrijven, presentatie, etc.) en je energie aan het einde (1-10).", "Markeer + / 0 / − per activiteit.", "Aan het einde van twee weken: welke activiteiten waren consequent +, welke −?", "Per + activiteit: welke 1-2 talenten zat hier in?", "Per − activiteit: welk talent ontbreekt waarschijnlijk bij jou?"],
    reflection: ["Welk type sales geeft jou meeste energie — relationeel, transactioneel, conceptueel?", "Welk type kost je structureel teveel?", "Wat zou er gebeuren als je 80% van je tijd uit + activiteiten zou werken?"],
    coachTip: "Sales-professionals dragen vaak een rol die niet bij hen past omdat 'het werkt'. Deze oefening maakt zichtbaar wat het kost — en wat er mogelijk is.",
  },
  {
    slug: "mijn-sales-stijl-typering",
    group: "sales",
    name: "Mijn sales-stijl-typering",
    goal: "Identificeren of je een hunter, farmer, consultant of evangelist bent",
    form: "Individueel",
    duration: "60 minuten",
    materials: "Beschrijving van 4 sales-types + JANE-profiel",
    steps: ["Lees de 4 sales-types: Hunter (nieuwe klanten winnen — Doorbraak + Exploitatie), Farmer (bestaande klanten verdiepen — Contact + Inleving), Consultant (oplossingen verkopen — Analyse + Uitleg), Evangelist (visie verkopen — Argumentatie + Etaleer).", "Per type: scoor op een schaal 1-10 hoe het bij je past.", "Welke combinatie talenten heb jij volgens je profiel? Welke sales-type past daarbij?", "Kijk naar je huidige functie: welk type ben je officieel? Wat klopt er, wat niet?", "Schrijf 1 zin op: 'Mijn natuurlijke sales-stijl is X, en het lukt me het best wanneer ik...'"],
    reflection: ["Klopt je natuurlijke type met wat je nu doet?", "Wat zou er veranderen als je vrij was om in je natuurlijke type te werken?", "Welk type kost je het meeste en wat zou je daar over willen zeggen tegen je manager?"],
  },
  {
    slug: "compensatie-in-sales-wat-trek-ik-leeg",
    group: "sales",
    name: "Compensatie in sales — wat trek ik leeg?",
    goal: "Herkennen welk overmatig gedrag je inzet onder targetdruk",
    form: "Individueel + 1 vertrouwde collega",
    duration: "45 minuten",
    materials: "",
    steps: ["Denk aan een recente periode met hoge targetdruk. Wat deed je in die periode meer dan normaal?", "Welk gedrag was duidelijk 'overmatig' — dat je achteraf kon zien?", "Vraag een vertrouwde collega: 'Wat zie jij me doen onder druk dat ik zelf niet zie?'", "Vergelijk hun antwoord met jouw zelf-analyse.", "Identificeer: welk talent ontbreekt mogelijk, waardoor je compensatiegedrag inzet?"],
    reflection: ["Wat is je vermoeide-patroon dat altijd terugkomt?", "Wat zou een collega met dat ontbrekende talent kunnen overnemen?", "Hoe ga je dit met je manager bespreken? Voor team- en projectleiders die in de zone tussen meewerken, sturen en specialist zijn werken. Oefeningen om helder te krijgen welke leidersrol bij jou natuurlijk werkt."],
  },
  {
    slug: "mijn-rollen-cirkeldiagram",
    group: "teamleiders",
    name: "Mijn rollen-cirkeldiagram",
    goal: "Visueel in kaart brengen welke rollen je vervult en welke energie ze geven",
    form: "Individueel",
    duration: "60 minuten",
    materials: "Lege cirkel op A4 + kleuren",
    steps: ["Teken een cirkel op A4 en verdeel hem in segmenten — één per rol die je in een week vervult (meewerker, sturer, faciliteerder, adviseur, specialist, etc.).", "Maak de segmenten groot in verhouding tot hoeveel tijd je eraan besteedt.", "Kleur per segment: groen = geeft energie, geel = neutraal, rood = trekt leeg.", "Welke kleur domineert? Welke rol kost je het meeste?", "Schrijf één 'zonde-zin' op: 'Als ik vandaag morgen wakker werd, zou ik 80% van mijn tijd in [groene rol] willen zitten in plaats van [rode rol].'"],
    reflection: ["Welke rol heeft je het verraste — meer of minder dan je dacht?", "Welke rode rol zou je kunnen delegeren of anders inrichten?", "Wie in je team zou de rode rol misschien graag oppakken?"],
  },
  {
    slug: "expert-versus-leider-waar-zit-ik",
    group: "teamleiders",
    name: "Expert versus leider — waar zit ik?",
    goal: "Bepalen of je primair expert bent die leidt of leider die toevallig veel weet",
    form: "Individueel + 1 mentor-gesprek",
    duration: "75 minuten",
    materials: "",
    steps: ["Schrijf 5 momenten op uit het laatste half jaar waarin je echt 'aan' was als teamleider.", "Per moment: was je vooral aan het sturen (leiderschap) of aan het inhoudelijk meedenken (expertise)?", "Tel: hoeveel momenten waren primair leiding, hoeveel expertise?", "Vraag je mentor of een ervaren collega: 'Hoe zie jij me — meer expert die leidt, of leider die kennis heeft?'", "Conclusie: wat is jouw primaire pet en hoe wil je daarmee omgaan?"],
    reflection: ["Heb je tot nu toe in de juiste pet gewerkt voor je type?", "Wat zou veranderen als je daarover open was met je team?", "Welke functie zou voor jou over 2 jaar meer passen — expert-leider of pure leider?"],
    coachTip: "Veel scrum masters en agile coaches zijn expert-leiders die als pure leider zijn gepositioneerd. De erkenning dat expertise hun primaire pet is, geeft enorm veel rust.",
  },
  {
    slug: "mijn-micromanagement-trigger",
    group: "teamleiders",
    name: "Mijn micromanagement-trigger",
    goal: "Herkennen wanneer en waarom je vervalt in micromanagement",
    form: "Individueel — twee weken observeren",
    duration: "Twee weken",
    materials: "",
    steps: ["Twee weken: noteer momenten waarop je merkte dat je 'te dichtbij' kwam op een teamlid (controles, vragen, sturen).", "Per moment: wat was de trigger? Stress? Onzekerheid over het resultaat? Specifieke persoon?", "Welk patroon zie je? In welke situaties slaat het toe?", "Welk talent of welke ondersteuning ontbreekt op die momenten?", "Schrijf één 'als-dan' afspraak met jezelf: 'Als ik X voel, dan ga ik Y doen in plaats van controleren.'"],
    reflection: ["Was de trigger waarvan je dacht 'dat ik beste-bedoeld doe' eigenlijk angst?", "Welk effect heeft jouw micromanagement op het zelfsturend vermogen van je team?", "Wat verandert er als jij je trigger leert herkennen? Voor stellen die zichzelf en elkaar beter willen begrijpen. Oefeningen die werken met twee individuele Jane-profielen en de dynamiek ertussen."],
  },
  {
    slug: "dubbel-profiel-naast-elkaar",
    group: "echtparen",
    name: "Dubbel-profiel naast elkaar",
    goal: "De combinatie van beide talent-profielen visueel ervaren",
    form: "Samen, beide partners aanwezig",
    duration: "90 minuten",
    materials: "Beide JANE-resultaten + groot vel papier",
    steps: ["Beide partners hebben hun JANE-traject gedaan. Print of teken beide profielen naast elkaar.", "Markeer per persoon je top-5 sterkste en je 5 zwakste talenten.", "Identificeer de aanvullingen: waar de één sterk is, is de ander zwak.", "Identificeer de gedeelde sterktes: waar zijn beiden sterk?", "Identificeer de gedeelde zwakke gebieden: waar zijn beiden zwak? Daar zit jullie collectieve blinde vlek."],
    reflection: ["Welke aanvulling was een verrassing — een talent waar je je partner sterk in zag?", "Welke gedeelde sterkte verklaart wat goed gaat in jullie?", "Welke gedeelde zwakte verklaart welke onderwerpen jullie vermijden?"],
    coachTip: "Sommige stellen ontdekken dat hun gedeelde blinde vlek (bv. concrete doelen stellen) de bron is van hun terugkerende discussies over toekomstplannen.",
  },
  {
    slug: "de-communicerende-vaten-analyse",
    group: "echtparen",
    name: "De communicerende vaten-analyse",
    goal: "Begrijpen hoe jullie elkaars blinde vlek triggeren",
    form: "Samen, na de dubbel-profiel-oefening",
    duration: "75 minuten",
    materials: "",
    steps: ["Identificeer de blinde vlek van partner A. Welk compensatiegedrag zet die in?", "Identificeer wat partner B doet wanneer A in compensatiegedrag schiet. Welke reactie?", "Doe hetzelfde omgekeerd: blinde vlek B, reactie A.", "Herken je dit patroon in een recent voorbeeld? Beschrijf de situatie samen.", "Schrijf samen één 'als-dan' afspraak: 'Wanneer A in [compensatie] schiet, zal B niet [reactie] maar [andere actie].'"],
    reflection: ["Welke patroon is jullie meest terugkerende?", "Wat zou er veranderen in jullie relatie als beide patronen onderbroken werden?", "Hoe bespreken jullie elkaar zonder het oude patroon te triggeren?"],
    coachTip: "Dit is gevoelig werk. Een externe coach kan helpen om de dynamiek bespreekbaar te maken zonder dat het uitloopt op verwijten.",
  },
  {
    slug: "het-koppel-diagram",
    group: "echtparen",
    name: "Het koppel-diagram",
    goal: "Een visuele samenvatting maken die jullie als referentie gebruiken",
    form: "Samen — creatief",
    duration: "60 minuten",
    materials: "A3 papier, kleurpotloden",
    steps: ["Teken een groot diagram met aan de linkerkant partner A's top-5 talenten, aan de rechterkant partner B's top-5.", "Verbind talenten die elkaar aanvullen met een lijn.", "Markeer de gedeelde sterktes (in een gemeenschappelijk vlak in het midden).", "Markeer de gedeelde zwaktes (in een gemeenschappelijke 'aandachtszone').", "Hang het ergens zichtbaar op (slaapkamer of werkkamer) — als referentie voor wanneer een patroon opkomt."],
    reflection: ["Hoe voelt het om jullie relatie zo visueel te zien?", "Wat in het diagram herkenden jullie het meest?", "Welke afspraak willen jullie er meteen aan koppelen? bewust maken Voor groepen van 5-10 personen die elkaars talenten willen leren herkennen en willen begrijpen waarom de groep doet wat hij doet."],
  },
  {
    slug: "groepsdiagram-opstellen",
    group: "kleine-groepen",
    name: "Groepsdiagram opstellen",
    goal: "Zichtbaar maken welke talenten in de groep aanwezig zijn",
    form: "Groep van 5-10 personen",
    duration: "2,5 uur",
    materials: "Groot vel papier + JANE-talentenlijst",
    steps: ["Ieder vertelt kort zijn of haar top-3 talenten (van een eerdere JANE-test of self-assessment).", "Maak op een groot vel een matrix: namen in de kolommen, 27 talenten in de rijen.", "Markeer per persoon hun 3 sterksten met een groene stip.", "Tel per talent: hoeveel groene stippen? Welke talenten zijn collectief sterk in deze groep?", "Welke talenten ontbreken in de groep? Dat zijn de collectieve blinde vlekken."],
    reflection: ["Wat is de gedeelde sterkte van deze groep?", "Welk talent ontbreekt en welk effect heeft dat op de groep?", "Wie zou de groep kunnen aanvullen — een nieuwe deelnemer met die talenten?"],
  },
  {
    slug: "wie-ben-jij-volgens-ons",
    group: "kleine-groepen",
    name: "Wie ben jij volgens ons",
    goal: "Per groepslid herkenning krijgen van talenten vanuit de groep",
    form: "Groep, ronde",
    duration: "5 minuten per persoon × aantal leden",
    materials: "",
    steps: ["Eén persoon zit centraal, alle anderen geven om de beurt: 'Bij jou zie ik vooral het talent X, omdat...'", "De centrale persoon noteert wat er wordt gezegd, zonder te reageren.", "Na de ronde mag de centrale persoon één vraag stellen of één observatie delen.", "Volgende persoon in het midden.", "Na alle rondes: bespreek wat er was — wat verraste, wat klopte, wat botste?"],
    reflection: ["Welk talent werd consequent door de groep bij jou gezien?", "Welk talent had je zelf benoemd dat niemand zag?", "Wat doet de groep nu met deze observaties?"],
    coachTip: "Deze oefening werkt alleen in een veilige groep met onderling vertrouwen. Niet op een nieuwe groep loslaten.",
  },
  {
    slug: "roltoekenning-binnen-de-groep",
    group: "kleine-groepen",
    name: "Roltoekenning binnen de groep",
    goal: "Expliciet maken wie welke rol natuurlijk pakt in de groep",
    form: "Groep, dialoog",
    duration: "75 minuten",
    materials: "",
    steps: ["Bespreek samen: wie pakt in onze groep meestal de leiding? Wie faciliteert? Wie houdt tegen? Wie haalt iedereen weer aan boord?", "Per rol: kom je gezamenlijk uit op één naam, of wisselt het?", "Match per rol met een talent: leider → Route + Argumentatie, faciliteerder → Harmonie + Contact, criticus → Correctie + Onderscheid, etc.", "Welke rollen zijn niet vertegenwoordigd in jullie groep?", "Bespreek: voor de ontbrekende rol — hoe lossen jullie het op?"],
    reflection: ["Was er een rol-toekenning die de groep verraste?", "Welke rol wil iemand graag oppakken die hij nu niet pakt?", "Welke rol-verdeling willen jullie expliciter maken? Voor teams van 4-12 personen in bedrijf of kerk die hun collectieve sterkte en blinde vlek willen begrijpen. Dit is het officiele Team Life Statement-traject."],
  },
  {
    slug: "voorbereiding-individuele-profielen",
    group: "teams",
    name: "Voorbereiding individuele profielen",
    goal: "Iedereen heeft een persoonlijk JANE-profiel klaar voor de offsite",
    form: "Individueel, vooraf",
    duration: "Per teamlid 4-6 weken",
    materials: "JANE-test + persoonlijke coach",
    steps: ["Iedereen doorloopt een persoonlijk JANE-traject (drie-stappen-workshop).", "Iedereen levert een persoonlijk Jane-diagram op.", "Iedereen schrijft één paragraaf over: 'Mijn 3 sterkste talenten + mijn blinde vlek + mijn compensatiegedrag.'", "Deze paragrafen worden anoniem verzameld door de facilitator.", "Op de offsite wordt het materiaal samen besproken."],
    reflection: ["(Geen — dit is voorbereidende fase, reflectie volgt op de offsite zelf)"],
  },
  {
    slug: "team-blinde-vlek-analyse-offsite-blok-2",
    group: "teams",
    name: "Team blinde vlek-analyse (offsite-blok 2)",
    goal: "De collectieve patronen identificeren die uit de combinatie van profielen ontstaan",
    form: "Team-offsite, ochtendblok",
    duration: "3 uur",
    materials: "Alle individuele profielen op A3 + post-its",
    steps: ["Leg alle profielen naast elkaar op een grote tafel.", "Per profiel-laag: kijk naar welke talenten collectief sterk zijn (bv. 8 van 10 hebben Analyse hoog).", "Kijk naar welke talenten collectief zwak zijn (bv. niemand heeft Etaleer hoog).", "Bespreek: welke patronen in het team zijn (mogelijk) het gevolg van deze collectieve sterkte / zwakte?", "Identificeer de top-3 collectieve blinde vlekken — talenten die geen enkel teamlid sterk heeft."],
    reflection: ["Welke gemeenschappelijke sterkte was een verrassing?", "Welke collectieve blinde vlek verklaart een patroon dat al jaren in het team zit?", "Hoe zou een nieuwe persoon met die blinde-vlek-talenten het team kunnen aanvullen?"],
    coachTip: "Dit is methodisch de kern van de Team Life Statement. De facilitator moet senior JANE- Coach zijn — niet iemand uit het team zelf.",
  },
  {
    slug: "team-life-statement-formuleren-offsite-blok-3",
    group: "teams",
    name: "Team Life Statement formuleren (offsite-blok 3)",
    goal: "Een gezamenlijke verklaring opstellen over wie het team is",
    form: "Team-offsite, middagblok",
    duration: "3 uur",
    materials: "Whiteboard + structuurformulier",
    steps: ["Beantwoord samen vier vragen: Wie zijn we als team? Wat is onze opdracht? Wat doen we wel? Wat doen we niet?", "Schrijf per vraag eerst individueel, dan deel je het in tweetallen, dan in viertallen, en tot slot in plenaire vorm.", "Voor de blinde vlek: 'We weten dat we als team niet sterk zijn in X. Hoe gaan we dit als team opvangen?'", "Formuleer één Team Life Statement van max 5 zinnen die alles samenvat.", "Test het: voelt elk teamlid zich erin terug?"],
    reflection: ["Welke zin in de Statement was het moeilijkst om gezamenlijk vast te leggen?", "Wat zou er veranderen als deze Statement leidend werd voor team-besluiten?", "Hoe gaan we de Statement levend houden?"],
  },
  {
    slug: "follow-up-leeft-de-statement-nog",
    group: "teams",
    name: "Follow-up: leeft de Statement nog?",
    goal: "Na 3 en 6 maanden checken of het werkt",
    form: "Team-bijeenkomst",
    duration: "2 uur",
    materials: "",
    steps: ["Bespreek per teamlid: 'Hoe heeft de Team Life Statement jouw werk de afgelopen maanden beïnvloed?'", "Bespreek concrete besluiten: 'Welke besluiten hebben we anders genomen door de Statement?'", "Bespreek de blinde vlek: 'Hoe hebben we hem opgevangen? Wat werkte, wat niet?'", "Wat moet aangepast worden aan de Statement?", "Plan de volgende follow-up."],
    reflection: ["Heeft de Statement écht effect, of is hij gestoffd?", "Welk teamlid heeft de Statement geleefd? Wat kunnen de anderen leren?", "Welke nieuwe inzichten over het team zijn er ontstaan? Voor oudstenteams, kerkenraden en geestelijke besturen. Oefeningen om besluitvorming te structureren op basis van gaven in plaats van anciënniteit."],
  },
  {
    slug: "bestuur-gaven-mapping",
    group: "oudstenteams",
    name: "Bestuur-gaven-mapping",
    goal: "Helder krijgen welke gaven in het bestuur aanwezig zijn",
    form: "Team, met individuele voorbereiding",
    duration: "Voorbereiding 4 weken + 3 uur bijeenkomst",
    materials: "Individuele Jane-profielen + lijst geestelijke gaven",
    steps: ["Voorbereiding: ieder bestuurslid doorloopt een persoonlijk JANE-traject.", "Op de bijeenkomst: leg alle profielen naast elkaar. Welke talenten zijn collectief aanwezig?", "Match per talent met de gekoppelde geestelijke gave (A1 → kennis, B1 → tongen, C1 → het geven, etc.).", "Welke gaven zijn aanwezig in het bestuur? Welke ontbreken volledig?", "Bespreek: welk effect heeft een ontbrekende gave op de gemeente?"],
    reflection: ["Welke gave hadden we niet verwacht maar bleek aanwezig?", "Welke gave mist het bestuur en wat zien we daarvan in onze besluitvorming?", "Moeten we naar uitbreiding van het bestuur kijken? Met wie?"],
  },
  {
    slug: "hoe-nemen-wij-besluiten-protocol-werksessie",
    group: "oudstenteams",
    name: "Hoe nemen wij besluiten — protocol-werksessie",
    goal: "Expliciet maken wie welke stem heeft bij welk type besluit",
    form: "Team-werksessie",
    duration: "Halve dag",
    materials: "Whiteboard + lijst recente besluiten",
    steps: ["Maak een lijst van 10 typen besluiten die het bestuur regelmatig neemt (financieel, pastoraal, strategie, personeel, etc.).", "Per type besluit: wie in het bestuur heeft de gave / het talent die daarbij hoort?", "Per type besluit: wie heeft een 'eerste stem' en wie 'volgt'?", "Schrijf een protocol op: 'Bij type X is Y de eerste stem en Z heeft een vetorecht op grond van het talent dat daar nodig is.'", "Test het protocol aan 3 recente besluiten: zou het anders zijn gelopen?"],
    reflection: ["Welke besluiten gaan we van nu af aan anders nemen?", "Wat doet dit met de impliciete machtsbalans in het bestuur?", "Hoe maken we dit bespreekbaar zonder dat het persoonlijk wordt?"],
    coachTip: "Dit kan spannend zijn voor lang-zittende leden die voorheen impliciet veel invloed hadden. De facilitator moet hier sensitief in zijn.",
  },
  {
    slug: "collectieve-blinde-vlek-van-het-bestuur",
    group: "oudstenteams",
    name: "Collectieve blinde vlek van het bestuur",
    goal: "Patronen herkennen die het bestuur al jaren vertoont",
    form: "Team, eerlijk gesprek",
    duration: "2,5 uur",
    materials: "",
    steps: ["Bespreek: welke onderwerpen worden in dit bestuur consequent niet opgelost?", "Welke besluiten zijn de afgelopen jaren teruggedraaid? Waarom?", "Welk gedrag herhaalt zich in elk overleg?", "Match: welk talent ontbreekt bij iedereen, dat deze patronen zou kunnen doorbreken?", "Formuleer één concrete actie om dit aan te pakken (extra lid? extern advies? rolverdeling?)."],
    reflection: ["Wat is voor jou persoonlijk het pijnlijkste inzicht?", "Wat moeten we de gemeente erover vertellen — en wanneer?", "Welk volgend besluit wordt onze test? Voor MKB-organisaties die hun HR willen baseren op werkelijke talenten in plaats van op functieprofielen. Oefeningen voor directie, MT en HR."],
  },
  {
    slug: "mt-talent-portfolio",
    group: "bedrijven",
    name: "MT-talent-portfolio",
    goal: "Helder krijgen wat het MT collectief heeft en mist",
    form: "Team — MT/directie",
    duration: "Voorbereiding 4 weken + halve dag bijeenkomst",
    materials: "Individuele Jane-profielen van alle MT-leden",
    steps: ["Voorbereiding: alle MT-leden doorlopen een persoonlijk JANE-traject.", "Leg de profielen naast elkaar. Wat is collectief sterk? Wat ontbreekt?", "Match per talent met de bedrijfsfunctie die het meest nodig heeft (Analyse = Operationeel Manager, Argumentatie = Sales Manager, etc.).", "Voor ontbrekende talenten: welke functie binnen het MT mist daardoor een sterk profiel?", "Bespreek: heeft het MT de juiste talenten voor de strategische richting van het bedrijf?"],
    reflection: ["Welke ontbrekende talenten verklaren waarom bepaalde initiatieven niet van de grond komen?", "Wat zou er gebeuren als we het MT zouden aanvullen met X?", "Hoe vertalen we dit naar wervingscriteria voor volgende vacatures?"],
  },
  {
    slug: "wervings-match-oefening",
    group: "bedrijven",
    name: "Wervings-match-oefening",
    goal: "Sollicitanten matchen op talent in plaats van op functieprofiel",
    form: "HR-traject — per vacature",
    duration: "Per vacature 90 minuten",
    materials: "Vacature + 6 sollicitanten",
    steps: ["Bepaal voor de vacature de 5-6 belangrijkste Jane-talenten (gebruik Jane Functie Rapport).", "Per sollicitant: laat hen een verkorte JANE-zelfevaluatie doen of doe een gesprekstest.", "Score per sollicitant op de 5-6 vereiste talenten.", "Top-3: degenen met de hoogste talent-match.", "Voer met de top-3 een 2e gesprek dat zich richt op concrete voorbeelden van die talenten in actie."],
    reflection: ["Was er een sollicitant die op papier sterk leek maar op talent niet matchte?", "Wat heeft deze methode opgeleverd dat een normale procedure niet had?", "Hoe verwerken we dit structureel in het wervingsbeleid?"],
  },
  {
    slug: "organisatiecultuur-bepaling",
    group: "bedrijven",
    name: "Organisatiecultuur-bepaling",
    goal: "Helder krijgen of het bedrijf primair een Lijn-, Project- of Veranderorganisatie is",
    form: "MT + HR",
    duration: "2 uur",
    materials: "Beschrijving 3 culturen",
    steps: ["Per cultuur (Lijn/Project/Verander): scoor op 1-10 hoe sterk deze in het bedrijf aanwezig is.", "Per afdeling: welke cultuur domineert daar?", "Identificeer mismatches: medewerkers die op verkeerde cultuur zitten voor hun talenten.", "Bespreek: moet het bedrijf doorgroeien naar een dominante cultuur, of bewust meerdere combineren?", "Maak een concreet HR-implicatieplan: wervingsfocus, doorstroming, ontwikkeling."],
    reflection: ["Klopt onze cultuur-bepaling met hoe we het bedrijf naar buiten profileren?", "Welke afdeling functioneert beter dan verwacht door cultuur-match? Welke minder?", "Wat is onze volgende stap richting bewust cultuurmanagement? Voor gemeentes en kerkenraden die een gefundeerde profielschets en gemeentevisie willen. Een meer-maands traject met enquête, interviews en visiebijeenkomsten."],
  },
  {
    slug: "gemeente-enquete-voorbereiden",
    group: "gemeentes",
    name: "Gemeente-enquête voorbereiden",
    goal: "Een gemeente-brede enquête opzetten om de talenten in kaart te brengen",
    form: "Kerkenraad + facilitator",
    duration: "1 maand voorbereiding",
    materials: "Vragen-template + kanaal voor uitsturen",
    steps: ["Bespreek met de kerkenraad: wat willen we weten over onze gemeente?", "Stel een enquête samen die per gemeentelid de top-3 talenten meet (vereenvoudigde JANE).", "Voeg vragen toe over betrokkenheid, beschikbaarheid en interesse-velden.", "Communiceer naar de gemeente: waarom doen we dit, wat doen we met de resultaten.", "Stuur uit, met deadline 4 weken."],
    reflection: ["Hoe hoog wordt de respons? Streef naar 60%+.", "Welke vragen leveren de meeste no-respons op?", "Wat zegt het responspatroon zelf al over de gemeente?"],
    coachTip: "Een gemeente van 80-200 leden heeft minimaal 60% respons nodig voor een statistisch betekenisvolle profielschets. Bij lagere respons: verleng de termijn of doe een nabel-actie.",
  },
  {
    slug: "diepte-interviews-met-sleutelpersonen",
    group: "gemeentes",
    name: "Diepte-interviews met sleutelpersonen",
    goal: "De getallen uit de enquête duiden met kwalitatief inzicht",
    form: "Een-op-een interviews",
    duration: "10-15 interviews × 60 minuten",
    materials: "Vraag-template",
    steps: ["Selecteer 10-15 mensen die de gemeente goed kennen: oudsten, voorganger, werkgroepleiders.", "Per interview: vraag 'Welke talenten zie je collectief sterk in onze gemeente?' en 'Welke missen?'", "Vraag naar concrete voorbeelden — geen abstracties.", "Vraag: 'Wat is een patroon in onze gemeente dat al jaren terugkomt?'", "Verzamel alle interviews en kijk naar patronen in antwoorden."],
    reflection: ["Welke observaties keren bij meerdere interviewers terug?", "Welke verschillen tussen interviewers verraden iets?", "Wat geven de interviews dat de enquête niet liet zien?"],
  },
  {
    slug: "profielschets-opstellen",
    group: "gemeentes",
    name: "Profielschets opstellen",
    goal: "De gemeente in kaart brengen op 4-6 pagina's",
    form: "Facilitator + kerkenraad-review",
    duration: "3-4 weken",
    materials: "Enquête-resultaten + interviews",
    steps: ["Schrijf op basis van enquête + interviews een conceptprofielschets: samenstelling van talenten, sterktes, blinde vlekken, ontwikkelingsruimte.", "Voeg concrete cijfers toe (talent-distributie, betrokkenheid).", "Voeg citaten uit interviews toe.", "Laat de kerkenraad reviewen — wat herkennen ze, wat botst?", "Eindversie 4-6 pagina's, opgesteld in heldere taal."],
    reflection: ["Wat in de profielschets is voor de kerkenraad een nieuwe inzicht?", "Wat in de profielschets is voor de gemeente onbedoeld confronterend?", "Welke visie-vragen worden door deze schets opgeroepen?"],
  },
  {
    slug: "visie-traject-met-kerkenraad",
    group: "gemeentes",
    name: "Visie-traject met kerkenraad",
    goal: "Op basis van de profielschets een gemeentevisie ontwikkelen",
    form: "Kerkenraad — 2-3 sessies",
    duration: "3 dagdelen verspreid over 2 maanden",
    materials: "",
    steps: ["Sessie 1 — Begrip: wat zegt de profielschets ons over wie we zijn?", "Sessie 2 — Richting: gegeven wie we zijn, waar wil God ons heen brengen?", "Sessie 3 — Concrete vertaling: welke 3-5 prioriteiten volgen hieruit voor het komende jaar?", "Tussen sessies: kerkenraad-leden denken individueel na en bespreken in deel- vergaderingen.", "Eindresultaat: één pagina gemeentevisie + 5 concrete prioriteiten."],
    reflection: ["Welke visie is gegroeid uit deze sessies dat we niet eerder hadden?", "Wat moeten we als gemeente loslaten?", "Wat is onze eerste publieke presentatie van deze visie?"],
    coachTip: "De visie moet voortkomen uit wie de gemeente is — niet uit wat de kerkenraad zou willen dat ze was. Dat is het verschil tussen een talent-gerichte en een wens-gerichte visie. For English-speaking professionals and church members. Exercises adapted for English language and international context.",
  },
  {
    slug: "the-3-talents-mirror-english",
    group: "international",
    name: "The 3-talents mirror (English)",
    goal: "First indication of your top 3 talents through self-reflection",
    form: "Individual",
    duration: "20-30 minutes",
    materials: "List of 27 talents (English translation)",
    steps: ["Take the list of 27 talents and read them one by one carefully.", "For each talent: ask yourself 'Do I recognize this in myself?' Mark with +, 0 or −.", "Look only at your +s. Cross out those where you doubt until 5-8 remain.", "For each remaining talent, write down: a concrete situation from the last six months in which this talent was visible.", "Pick your top 3 — those with the most concrete examples."],
    reflection: ["Which talents were a surprise — ones you had forgotten about yourself?", "Which talents did you miss in yourself — ones you had expected?", "What does your top 3 say about what gives you energy?"],
    coachTip: "For international clients, cultural context matters. A talent like 'Argumentation' may be valued differently in Dutch direct culture than in Japanese consensus culture.",
  },
  {
    slug: "cross-cultural-talent-translation",
    group: "international",
    name: "Cross-cultural talent translation",
    goal: "Understand how your talents express differently in different cultural contexts",
    form: "Individual + 1-2 conversations",
    duration: "60 minutes",
    materials: "",
    steps: ["Identify your top 3 talents.", "For each talent: how is it perceived in your home culture? (e.g., direct vs indirect, individual vs collective)", "For each talent: how would it be perceived in another culture where you've worked or lived?", "Identify situations where your talent was misread by colleagues from another culture.", "Write one strategy for each talent: how to adjust expression without losing essence."],
    reflection: ["Which talent has been most often misunderstood across cultures?", "Which talent gives you the most leverage in international settings?", "What is your next step? —"],
  },
];

/** English overrides per slug; any field not present falls back to the Dutch base. */
const exercisesEnOverrides: Record<string, Partial<Exercise>> = {
  "drie-talenten-in-de-spiegel": {
    name: "Three talents in the mirror",
    goal: "Get a first indication of your three strongest talents through self-reflection",
    form: "Individual",
    duration: "20-30 minutes",
    materials: "Pen + paper, list of the 27 talents with short descriptions",
    steps: ["Take the list of 27 talents and read them one by one, calmly.", "For each talent ask yourself 'Do I recognise this in myself?' Mark it with +, 0 or −.", "Look only at your pluses. Cross out the ones you doubt until 5-8 remain.", "For each remaining talent, write down a concrete situation from the last six months in which it was visible.", "From the remaining talents, pick your top 3 — the ones with the most concrete examples."],
    reflection: ["Which talents were a surprise — ones you had forgotten in yourself?", "Which talents did you miss in yourself — ones you had expected?", "What does your top 3 say about what gives you energy?"],
    coachTip: "Clients tend to underestimate what they have (especially highly educated women) and overestimate what they lack. In the second round, ask for concrete situations — those make it solid.",
  },
  "drie-naasten-als-talent-spiegel": {
    name: "Three close ones as a talent mirror",
    goal: "External validation of your suspected talents through people who know you well",
    form: "Individual + three short conversations",
    duration: "A week, in spare moments",
    materials: "List of the 27 talents to share",
    steps: ["Choose three people who know you well, from different contexts (e.g. partner, colleague, childhood friend).", "Ask each: 'Which 5 talents from this list do you most strongly recognise in me?'", "Give them the list and 24 hours. Send it by app or email.", "Collect the answers in a table — which talents are named more than once?", "Compare with your own top 3 from the mirror exercise: where does it overlap, where does it differ?"],
    reflection: ["Which talents were named by all three? Those are probably your strongest.", "Which talents did you not recognise yourself but others did? Are you underrating something?", "Which talents did you think you had but nobody named?"],
    coachTip: "It is most powerful when three people from different worlds name the same 2-3 talents. Those are then almost certainly truly present.",
  },
  "het-energie-dagboek": {
    name: "The energy diary",
    goal: "Map practically which activities give energy and which drain it",
    form: "Individual",
    duration: "A week, a few minutes a day",
    materials: "A small notebook or notes app",
    steps: ["For one week, note each workday: which activity you did, and the energy level you ended on (1-10).", "Mark each activity with + (gave energy), 0 (neutral) or − (cost energy).", "At the end of the week: which activities consistently got a + and which a −?", "For each + activity: which 1-2 talents were in it? (Use the 27-talents list.)", "For each − activity: which talent is probably missing in you, making it cost so much energy?"],
    reflection: ["Does your + talent overlap match your top 3 from earlier exercises?", "Which − activities could you delegate to someone with that talent?", "What would happen if you spent 80% of your time on + activities?"],
  },
  "de-drie-stappen-zelfworkshop-verkort": {
    name: "The three-step self-workshop (short)",
    goal: "Work through a simplified version of the main journey — a first introduction",
    form: "Individual",
    duration: "Three 45-minute sessions, one per week",
    materials: "List of 27 talents + blank worksheets",
    steps: ["Session 1 — Who I am not: go through the 27 talents and tick 8-12 that do not fit you. For each excluded talent, describe a situation where you felt its absence.", "Session 2 — Who I am: from the remaining 15-19 talents, choose your 5-8 strongest. Describe what they create in combination.", "Session 3 — What holds me back: look at the talent you score lowest. What substitute behaviour do you use for it? How long have you done so?", "After each session, write one paragraph about what you learned.", "Keep the three worksheets — they form the basis for later coaching with a certified coach."],
    reflection: ["Which step was the hardest, and why?", "Did you feel resistance to certain insights? Which ones?", "What would you want to ask a coach to explore this further?"],
    coachTip: "This short version does not replace full coaching, but gives a serious first picture. Good as a starting point or as self-inquiry between sessions.",
  },
};

export const exerciseGroups = groupsNl;
export const exercises = exercisesNl;

export function getExerciseGroups(locale: Locale): ExerciseGroup[] {
  return locale === "nl" ? groupsNl : groupsEn;
}

export function getExercises(locale: Locale): Exercise[] {
  if (locale === "nl") return exercisesNl;
  return exercisesNl.map((e) => ({ ...e, ...exercisesEnOverrides[e.slug] }));
}

export function getExercisesByGroup(locale: Locale, groupId: string): Exercise[] {
  return getExercises(locale).filter((e) => e.group === groupId);
}
