import type { Locale } from "@/lib/i18n";

export interface Talent {
  number: number;
  slug: string;
  name: string;
  description: string;
}

const nl: Talent[] = [
  { number: 1, slug: "analyse", name: "Analyse", description: "Het analysetalent (door Dirk ook 'kennisproductietalent' genoemd) zoekt de kern van een probleem op in plaats van alleen de symptomen te bestrijden. Zoals je een appel doormidden snijdt om het klokhuis te zien, maakt dit talent zichtbaar wat er werkelijk speelt. Het verwerkt ruwe data tot zinvolle informatie en analyse, en voorziet zo in de behoefte aan een oplossing die hout snijdt. Wie het mist, blijft aan de buitenkant hangen en lost problemen op met kostbaar trial-and-error." },
  { number: 2, slug: "formulering", name: "Formulering", description: "Het formuleringstalent (ook 'kennisformuleringstalent') brengt geanalyseerde kennis over in de taal van de ander, zodat die zich het kan eigen maken. Het stemt de boodschap af op de ontvanger — financiële mensen, de werkvloer of grote klanten krijgen elk hun eigen vertaling. Daardoor ontstaat het eerste vertrouwen: de ander merkt 'ja, dat is precies wat ik bedoel'. Wie het sterk heeft, kan zich zo soepel aanpassen dat het soms gladjes overkomt." },
  { number: 3, slug: "investering", name: "Investering", description: "Het investeringstalent (ook 'kennisinvesteringstalent') herkent patronen in de markt en trekt die door naar de toekomst, waardoor het ontwikkelingen als het ware kan voorspellen. Zo weet iemand wanneer een product vervangen moet worden of welke research nu al nodig is. Hetzelfde patroongevoel werkt ook in de levens van mensen, bij het inschatten van iemands bestemming. Het steekt anderen aan om in het juiste te investeren en is gericht op verantwoorde groei." },
  { number: 4, slug: "onderscheiding", name: "Onderscheiding", description: "Het onderscheidingstalent ziet in het hier en nu meteen welke middelen relevant zijn om een probleem op te lossen, zonder eindeloos alle kennis op tafel te leggen. Het maakt mensen slagvaardig en to the point: ze zien direct wat er nodig is en doen het ook. In een vergadering houden zij agendapunten netjes uit elkaar. Wie het mist, haalt punten door elkaar of pakt zaken minder doelgericht aan." },
  { number: 5, slug: "inleving", name: "Inleving", description: "Het inlevingstalent verplaatst zich volledig in de belevingswereld van de ander om te begrijpen hoe die iets ervaart, en stemt de omgeving daarop af. Pas als je weet hoe iemand dingen beleeft, kun je je kennis en ervaring goed overbrengen; dat schept ook vertrouwen. Mensen voelen zich gehoord en kunnen alles kwijt. Wie veel inlevingsvermogen heeft, kan de last van de ander echter meedragen en moet die soms bewust van zich afschudden." },
  { number: 6, slug: "combinatie", name: "Combinatie", description: "Het combinatietalent beschikt over een enorm reservoir aan ideeën en koppelt die aan iemands identiteit en bestemming, niet alleen aan de situatie of de persoon. Het produceert vrijwel automatisch een stroom van mogelijkheden om dat unieke plan tot zijn recht te laten komen. Zo komen soms ideeën naar boven die ver van het gangbare denken liggen. Het maakt iemand inventief en creatief in het bedenken van wat ergens bij past." },
  { number: 7, slug: "routine", name: "Routine", description: "Het routinetalent geeft de natuurlijke aanleg en motivatie om op een ingeslagen weg door te gaan, net zolang tot het resultaat zichtbaar wordt. Het zorgt voor doorzettingsvermogen en discipline bij het uitvoeren van een gekozen strategie. Wie het sterk heeft, kan echter ook te lang vasthouden aan een oude aanpak en moeilijk omschakelen. Anderen zonder dit talent worden al snel als ongedisciplineerd of ongeduldig ervaren." },
  { number: 8, slug: "argumentatie", name: "Argumentatie", description: "Het argumentatietalent motiveert en overtuigt mensen met argumenten waarom een bepaalde werkwijze of routine nodig is. Het maakt duidelijk waaróm iets op een bepaalde manier moet gebeuren, of dat nu naar medewerkers of naar klanten is. Het richt zich vooral op overtuiging op de korte termijn. Het gevaar is dat iemand zijn overtuigingskracht gaat gebruiken om anderen te manipuleren of voor zijn karretje te spannen." },
  { number: 9, slug: "uitleg", name: "Uitleg", description: "Het uitlegtalent (door Dirk 'docenttalent' genoemd) draait om het foutloos overbrengen van kennis of een werkwijze, zodat mensen weten wat ze precies moeten doen. Zoals lesstof via de docent de klas in gaat: één fout vooraan wordt dertig keer verkeerd doorgegeven, en daarom hecht dit talent sterk aan integriteit en kwaliteit op lange termijn. Wie het heeft, vereenzelvigt zich met zijn taak en is daardoor extra gevoelig voor kritiek. Een nieuw vraagstuk laat het van alle kanten 'rondcirkelen' voordat er een doordachte reactie komt." },
  { number: 10, slug: "helpen", name: "Helpen", description: "Het helptalent (vroeger 'servicetalent') verleent graag en bekwaam assistentie bij een grote verscheidenheid aan vragen. Het wacht tot iemand om hulp vraagt en springt dan zelf bij — niet doorschuiven, maar zelf de mouwen opstropen. Het is een belangrijke pijler in de servicegerichtheid van een organisatie: de klant belt, wij antwoorden. Wie het weinig heeft, helpt alleen op het eigen vakgebied en laat de rest aan een ander over." },
  { number: 11, slug: "signaleren", name: "Signaleren", description: "Het signaleertalent (door Dirk 'ontfermtalent' genoemd) pikt behoeftesignalen vroeg op en anticipeert erop, vaak nog voordat de ander iets gevraagd heeft. Het heeft gevoel voor timing op de middellange termijn: je belt iemand net op het moment dat hij ook aan jou dacht. In plaats van zelf de taak uit te voeren schakelt dit talent de juiste persoon in om het te laten gebeuren. Het maakt dat mensen zich alert en attent geholpen voelen." },
  { number: 12, slug: "etaleren", name: "Etaleren", description: "Het etaleertalent richt zich erop hoe aantrekkelijk een organisatie of aanbod zich in de markt presenteert. Het zorgt voor een uitnodigende uitstraling via middelen als folders, brochures en websites, zodat mensen vanzelf worden aangetrokken. Het vormt samen met helpen en signaleren een pijler van het waardesysteem van een onderneming. Een goede balans betekent dat de aantrekkelijke presentatie in verhouding staat tot het daadwerkelijk helpen en oppikken van behoeften." },
  { number: 13, slug: "vertrouwen", name: "Vertrouwen", description: "Het vertrouwenstalent (door Dirk 'brontalent' genoemd) durft mensen in te zetten en te betrekken bij het werk, omdat het erop vertrouwt dat zij iets kunnen — ook zonder dat alles al bewezen is. Als een herder die zijn schapen een onbekende weide in leidt, durft het met vertrouwen te ondernemen. Daardoor krijgen mensen ruimte om zich te ontwikkelen en hun talenten te benutten. Wie het sterk heeft, kan naïef overkomen; wie het mist, is eerder wantrouwend en houdt de kat uit de boom." },
  { number: 14, slug: "contact", name: "Contact", description: "Het contacttalent zoekt voortdurend contact met mensen en weet daardoor goed wat er onder hen leeft. Door veel te overleggen en bij te praten ontdekt het wat er in mensen zit, zodat de juiste persoon op de juiste opdracht kan worden gezet. Dirk vergelijkt het met een batterij: bij weinig contacttalent is die na een paar uur leeg en heeft iemand behoefte om zich terug te trekken. Wie het veel heeft, kan in de ogen van anderen soms te veel praten." },
  { number: 15, slug: "corrigeren", name: "Corrigeren", description: "Het correctietalent is sterk op feiten gericht en herinnert anderen daaraan, zodat zij bijgestuurd of getraind kunnen worden. Een correctie op basis van feiten ('je komt elke meeting een half uur te laat') landt, terwijl een correctie op gevoel dat niet doet. Het is nodig om mensen goed te kunnen blijven inzetten en relaties te verdiepen. Dirk beschrijft het als antennes die meer op feiten dan op sfeer en emotie zijn afgestemd." },
  { number: 16, slug: "doorbraak", name: "Doorbraak", description: "Het doorbraaktalent (door Dirk 'incasseer-', 'knok-' of 'vechttalent' genoemd) richt zich op het doorbreken van barrières en blokkades, zodat de workflow door kan gaan en het werk niet blijft liggen. Het laat zich niet ophouden: als iemand even weg is, wordt diegene meteen gebeld zodat anderen niet stil komen te staan. Het kan flink incasseren en zet net zo lang door tot de klus geklaard is. Daardoor maakt het ook een team sterker, al levert het soms 'gele kaarten' op." },
  { number: 17, slug: "beheersen", name: "Beheersen", description: "Het beheerstalent grijpt op de middellange termijn in zodra dreigt dat de afgesproken kwaliteitsnorm niet wordt gehaald. Het bewaakt vooraf aan welke normen het resultaat moet voldoen en houdt in de gaten of iedereen op schema ligt. Dirk beschrijft een soort automatisch klokje of wekkertje in het hoofd dat aanslaat als iets uit de pas dreigt te lopen. Het ingrijpen kan soms dominant overkomen, maar voorkomt dat de gezamenlijke uitkomst onder de maat blijft." },
  { number: 18, slug: "vertalen", name: "Vertalen", description: "Het vertaaltalent licht zaken toe met voorbeelden en instructie, zodat een ander precies begrijpt hoe iets moet worden uitgevoerd. Het zet kennis of een werkwijze om in heldere, toegankelijke aanwijzingen — in een leersituatie maakt het de stof concreet en behapbaar. Het komt sterk naar voren wanneer mensen een nieuwe werkwijze of nieuwe machines onder de knie moeten krijgen en daarbij veel uitleg en herhaling nodig hebben. Zo zorgt het ervoor dat iets daadwerkelijk wordt uitgevoerd zoals het bedoeld is." },
  { number: 19, slug: "route", name: "Route", description: "Het routetalent geeft een automatisch gevoel voor de juiste richting en koers in het hier en nu. Mensen met dit talent pionieren graag, ontdekken dingen liever zelf en hebben moeite met regels en handboeken. Ze komen zelfstandig en authentiek over en hechten sterk aan wat echt en origineel is. Daardoor kunnen ze lastig te managen zijn en met hun gedachten al in de toekomst bezig zijn terwijl ze fysiek aanwezig zijn." },
  { number: 20, slug: "structuur", name: "Structuur", description: "Het structuurtalent houdt vast aan een afgesproken structuur en heeft veel gevoel voor efficiency op de middellange termijn. Het wijst erop dat steeds afwijken van afspraken alle efficiëntie ondermijnt, en houdt van een transparante, toegankelijke aanpak. Klanten waarderen het dat dingen efficiënt en voorspelbaar verlopen. Het nadeel is dat anderen het soms inflexibel of radicaal vinden, omdat het moeite heeft met het sluiten van compromissen op dit punt." },
  { number: 21, slug: "harmonie", name: "Harmonie", description: "Het harmonietalent blijft in overleg en contact met anderen en voelt daardoor op lange termijn aan welke richting eraan zit te komen. Door af te stemmen weet het wat er verandert — groei, afstoting of nieuwe opdrachten — en kan het veel verschillende mensen en klanten aan. De kern is de bereidheid om te ondergaan en op te nemen wat een ander te bieden heeft. Wie het weinig heeft, vindt dat iemand met veel harmonietalent te veel wil overleggen." },
  { number: 22, slug: "rotatie", name: "Rotatie", description: "Het rotatietalent brengt de omgeving in beweging en houdt graag vaart en tempo in de dingen. Het werkt en denkt snel en kan een doorslaggevende rol spelen waar snelheid telt. Mensen met dit talent kunnen moeilijk stilzitten en worden ongeduldig als het te traag gaat of als ze moeten wachten. Wie langzamer werkt, wordt door hen al gauw als traag ervaren." },
  { number: 23, slug: "exploitatie", name: "Exploitatie", description: "Het exploitatietalent ziet mogelijkheden en wil die ook daadwerkelijk benutten. Waar een ander snel één kopje koffie inschenkt, merkt dit talent op dat er ook glazen staan die meteen gevuld kunnen worden. Het is erop gericht beschikbare middelen en kansen optimaal te gebruiken. Het hoort bij de 'drijftalenten' die op zichzelf al een sterke drive aan iemands leven geven." },
  { number: 24, slug: "export", name: "Export", description: "Het exporttalent gaat nog een stap verder in het zoeken en benutten van mogelijkheden dan exploitatie en kijkt steeds naar de volgende kans om iets in te zetten. Het is sterk gedreven en geeft, samen met de andere drijftalenten, een grote energie en stuwkracht aan iemands handelen. Die gedrevenheid kan zo sterk zijn dat iemand zich in golven helemaal geeft en daarna weer flink moet uitrusten. Het blijft uitkijken naar nieuwe toepassingen en bestemmingen voor wat er is." },
  { number: 25, slug: "geven", name: "Geven", description: "Het geeftalent is in staat veel te geven en te investeren zonder meteen een direct rendement of resultaat te eisen. Het ziet de contouren van iets nieuws en doet graag mee aan ontwikkelingen waar pas later iets uitkomt — handig bij nieuwe producten en markten die tijd vragen. Dirk verbindt het met het manna-principe: vasthouden bederft, terwijl er steeds opnieuw mag worden ontvangen. Wie het weinig heeft, is eerder een spaarder of verzamelaar die moeilijk dingen kan loslaten." },
  { number: 26, slug: "bestuur", name: "Bestuur", description: "Het bestuurstalent stelt realistische doelen en maakt ze concreet, haalbaar, meetbaar en navolgbaar voor anderen. Het helpt om jezelf en anderen stap voor stap ergens naartoe te coachen en te sturen, met tussendoelen onderweg. Te hoge doelen ontmoedigen en te lage doelen zijn niet spannend genoeg; dit talent vindt de juiste maat. Zo helpt het om een bestemming of plan daadwerkelijk te realiseren in plaats van het te laten verzanden." },
  { number: 27, slug: "scope", name: "Scope", description: "Het scopetalent bepaalt hoe breed iemand zijn omgeving gelijktijdig kan waarnemen. Bij een brede scope neem je veel signalen tegelijk waar en zie je snel het verband daartussen; bij een smalle, gerichte scope kijk je als door een tunnel en werk je zeer geconcentreerd. Een gerichte scope maakt het makkelijker je af te sluiten van de omgeving, maar moeilijker om alle losse signalen te integreren en hun samenhang te zien. Zo bepaalt dit talent of iemand vooral overzicht heeft of juist diepe focus." },
];

const en: Talent[] = [
  { number: 1, slug: "analyse", name: "Analysis", description: "The analysis talent (which Dirk also calls the 'knowledge production' talent) seeks out the core of a problem instead of merely fighting the symptoms. Just as you cut an apple in half to see its core, this talent reveals what is really going on. It turns raw data into meaningful information and analysis, and so meets the need for a solution that truly cuts to the heart of the matter. Whoever lacks it stays on the surface and solves problems through costly trial and error." },
  { number: 2, slug: "formulering", name: "Formulation", description: "The formulation talent (also the 'knowledge formulation' talent) conveys analysed knowledge in the other person's language, so they can make it their own. It tailors the message to the recipient — finance people, the shop floor or major clients each get their own translation. This is how the first trust arises: the other person feels 'yes, that is exactly what I meant'. Those who have it strongly can adapt so smoothly that it sometimes comes across as slick." },
  { number: 3, slug: "investering", name: "Investment", description: "The investment talent (also the 'knowledge investment' talent) recognises patterns in the market and extends them into the future, so it can as it were predict developments. This lets someone sense when a product needs replacing or which research is already needed now. The same feel for patterns also works in people's lives, when gauging someone's destiny. It inspires others to invest in the right things and is geared towards responsible growth." },
  { number: 4, slug: "onderscheiding", name: "Discernment", description: "The discernment talent immediately sees, in the here and now, which means are relevant to solve a problem, without endlessly laying out all available knowledge. It makes people decisive and to the point: they see at once what is needed and act on it. In a meeting they keep agenda items neatly apart. Whoever lacks it mixes points up or tackles things less purposefully." },
  { number: 5, slug: "inleving", name: "Empathy", description: "The empathy talent fully puts itself in the other person's world of experience to understand how they feel about something, and tunes the environment to that. Only once you know how someone experiences things can you convey your knowledge and experience well; this also builds trust. People feel heard and can share everything. Those with strong empathy can, however, carry the other's burden home with them and must sometimes consciously shake it off." },
  { number: 6, slug: "combinatie", name: "Combination", description: "The combination talent has an enormous reservoir of ideas and links them to someone's identity and destiny, not just to the situation or the person. It produces an almost automatic stream of possibilities to let that unique plan come into its own. This sometimes brings up ideas that lie far from conventional thinking. It makes someone inventive and creative in devising what fits a given purpose." },
  { number: 7, slug: "routine", name: "Routine", description: "The routine talent gives the natural aptitude and motivation to keep going on a chosen path until the result becomes visible. It provides perseverance and discipline in carrying out a chosen strategy. Those who have it strongly can, however, also cling too long to an old approach and find it hard to switch. Others who lack this talent are quickly seen as undisciplined or impatient." },
  { number: 8, slug: "argumentatie", name: "Argumentation", description: "The argumentation talent motivates and persuades people with arguments about why a certain method or routine is needed. It makes clear why something must happen in a particular way, whether towards employees or clients. It is aimed mainly at persuasion in the short term. The danger is that someone uses their persuasive power to manipulate others or rope them into their own agenda." },
  { number: 9, slug: "uitleg", name: "Explanation", description: "The explanation talent (which Dirk calls the 'teacher' talent) is about conveying knowledge or a method flawlessly, so that people know exactly what to do. Just as lesson material passes through the teacher into the class: one mistake at the front is passed on wrongly thirty times, which is why this talent cares deeply about integrity and long-term quality. Those who have it identify with their task and are therefore extra sensitive to criticism. A new question is left to 'circle around' from all sides before a well-considered response comes." },
  { number: 10, slug: "helpen", name: "Helping", description: "The helping talent (formerly the 'service' talent) gladly and capably provides assistance across a wide variety of questions. It waits until someone asks for help and then steps in personally — not passing it on, but rolling up its own sleeves. It is an important pillar of an organisation's service orientation: the client calls, we answer. Those who have little of it help only within their own field and leave the rest to someone else." },
  { number: 11, slug: "signaleren", name: "Signalling", description: "The signalling talent (which Dirk calls the 'caring' or 'compassion' talent) picks up signals of need early and anticipates them, often before the other person has even asked. It has a feel for timing in the medium term: you call someone just when they were thinking of you too. Instead of carrying out the task itself, this talent brings in the right person to make it happen. It makes people feel helped in an alert and attentive way." },
  { number: 12, slug: "etaleren", name: "Displaying", description: "The displaying talent focuses on how attractively an organisation or offering presents itself in the market. It creates an inviting image through means such as flyers, brochures and websites, so that people are naturally drawn in. Together with helping and signalling it forms a pillar of a company's value system. A good balance means the attractive presentation is in proportion to actually helping and picking up on needs." },
  { number: 13, slug: "vertrouwen", name: "Trust", description: "The trust talent (which Dirk calls the 'source' talent) dares to deploy people and involve them in the work, because it trusts that they are capable — even before everything has been proven. Like a shepherd leading his sheep into an unfamiliar pasture, it dares to undertake things with confidence. This gives people room to develop and to use their talents. Those who have it strongly can come across as naive; those who lack it are more distrustful and hold back to see how things unfold." },
  { number: 14, slug: "contact", name: "Contact", description: "The contact talent constantly seeks contact with people and therefore knows well what is going on among them. By talking and consulting a lot it discovers what is in people, so the right person can be placed on the right task. Dirk compares it to a battery: with little contact talent it is drained after a few hours and someone needs to withdraw. Those who have a lot of it can, in others' eyes, sometimes talk too much." },
  { number: 15, slug: "corrigeren", name: "Correction", description: "The correction talent is strongly focused on facts and reminds others of them, so they can be steered or trained. A correction based on facts ('you are half an hour late to every meeting') lands, whereas one based on feeling does not. It is needed to keep deploying people well and to deepen relationships. Dirk describes it as antennae tuned more to facts than to mood and emotion." },
  { number: 16, slug: "doorbraak", name: "Breakthrough", description: "The breakthrough talent (which Dirk calls the 'absorb', 'fight' or 'combat' talent) focuses on breaking through barriers and blockages, so the workflow can continue and work does not pile up. It refuses to be held up: if someone is briefly away, they are called at once so others do not grind to a halt. It can take a lot of knocks and keeps pushing until the job is done. This also makes a team stronger, even if it sometimes earns a few 'yellow cards'." },
  { number: 17, slug: "beheersen", name: "Control", description: "The control talent intervenes in the medium term as soon as the agreed quality standard threatens not to be met. It sets out in advance which standards the result must meet and keeps an eye on whether everyone is on schedule. Dirk describes a kind of automatic clock or alarm in the head that goes off when something threatens to drift off course. The intervention can sometimes come across as dominant, but it prevents the joint outcome from falling short." },
  { number: 18, slug: "vertalen", name: "Translation", description: "The translation talent explains things with examples and instruction, so that another person understands exactly how something should be carried out. It turns knowledge or a method into clear, accessible directions — in a learning situation it makes the material concrete and manageable. It comes strongly to the fore when people have to master a new method or new machines and need a lot of explanation and repetition. In this way it ensures that something is actually done as intended." },
  { number: 19, slug: "route", name: "Route", description: "The route talent gives an automatic feel for the right direction and course in the here and now. People with this talent like to pioneer, prefer to discover things for themselves, and struggle with rules and manuals. They come across as independent and authentic and care strongly about what is real and original. As a result they can be hard to manage and may already be living in the future in their minds while physically present." },
  { number: 20, slug: "structuur", name: "Structure", description: "The structure talent holds on to an agreed structure and has a strong feel for efficiency in the medium term. It points out that constantly deviating from agreements undermines all efficiency, and it likes a transparent, accessible approach. Clients appreciate that things run efficiently and predictably. The downside is that others sometimes find it inflexible or rigid, because it struggles to compromise on this point." },
  { number: 21, slug: "harmonie", name: "Harmony", description: "The harmony talent stays in consultation and contact with others and therefore senses, in the long term, which direction is coming. By tuning in it knows what is changing — growth, divestment or new assignments — and it can handle many different people and clients. At its core is the willingness to undergo and take in what another has to offer. Those who have little of it find that someone with a lot of harmony talent wants to consult too much." },
  { number: 22, slug: "rotatie", name: "Rotation", description: "The rotation talent sets its surroundings in motion and likes to keep up pace and tempo. It works and thinks quickly and can play a decisive role where speed matters. People with this talent find it hard to sit still and become impatient when things go too slowly or when they have to wait. Those who work more slowly are soon seen by them as sluggish." },
  { number: 23, slug: "exploitatie", name: "Exploitation", description: "The exploitation talent sees possibilities and wants to actually make use of them. Where someone else quickly pours a single cup of coffee, this talent notices that there are also glasses standing ready to be filled at once. It is geared towards making optimal use of available means and opportunities. It belongs to the 'drive talents' that in themselves already give a strong drive to someone's life." },
  { number: 24, slug: "export", name: "Export", description: "The export talent goes one step further in seeking and using possibilities than exploitation, always looking for the next opportunity to put something to use. It is strongly driven and, together with the other drive talents, gives great energy and momentum to someone's actions. That drive can be so strong that someone gives everything in waves and then has to rest considerably afterwards. It keeps looking out for new applications and destinations for what is available." },
  { number: 25, slug: "geven", name: "Giving", description: "The giving talent is able to give and invest a great deal without immediately demanding a direct return or result. It sees the outlines of something new and likes to take part in developments that only pay off later — useful for new products and markets that take time. Dirk links it to the manna principle: hoarding spoils it, while there is always something new to receive. Those who have little of it are more of a saver or collector who finds it hard to let things go." },
  { number: 26, slug: "bestuur", name: "Governance", description: "The governance talent sets realistic goals and makes them concrete, achievable, measurable and traceable for others. It helps to coach and steer yourself and others step by step towards something, with milestones along the way. Goals that are too high discourage and goals that are too low are not exciting enough; this talent finds the right measure. In this way it helps to actually realise a destiny or plan instead of letting it fizzle out." },
  { number: 27, slug: "scope", name: "Scope", description: "The scope talent determines how broadly someone can perceive their surroundings simultaneously. With a broad scope you take in many signals at once and quickly see the connection between them; with a narrow, focused scope you look as if through a tunnel and work with great concentration. A focused scope makes it easier to shut out the environment, but harder to integrate all the separate signals and see how they hang together. In this way this talent determines whether someone mainly has overview or rather deep focus." },
];

export function getTalents(locale: Locale): Talent[] {
  return locale === "nl" ? nl : en;
}
