import type { Locale } from "@/lib/i18n";

export interface Talent {
  number: number;
  slug: string;
  name: string;
  description: string;
  /** Jane diagram code, e.g. A1, B5, C9. */
  code?: string;
  /** Talent category column: Werkproces / Zekerheid / Bestemming (NL). */
  column?: string;
  alias?: string;
  quote?: string;
  definition?: string;
  skills?: string;
  blindSpot?: string;
  compensation?: string;
  example?: string;
  hulpvraag?: string;
  schakelvraag?: string;
  dirkWords?: string;
}

const nl: Talent[] = [
  {
    number: 1,
    slug: "analyse",
    name: "Analyse",
    code: "A1",
    column: "Werkproces",
    alias: "Kennisproductietalent",
    quote: "Ik wil graag precies weten waar het in de kern om gaat",
    description: "Het analysetalent (door Dirk ook 'kennisproductietalent' genoemd) zoekt de kern van een probleem op in plaats van alleen de symptomen te bestrijden. Zoals je een appel doormidden snijdt om het klokhuis te zien, maakt dit talent zichtbaar wat er werkelijk speelt. Het verwerkt ruwe data tot zinvolle informatie en analyse, en voorziet zo in de behoefte aan een oplossing die hout snijdt. Wie het mist, blijft aan de buitenkant hangen en lost problemen op met kostbaar trial-and-error.",
    definition: "Analysetalent dringt snel door tot de essentie. Natuurlijke aanleg en motivatie om snel en makkelijk door te dringen tot de kern van iets. Voorziet in de behoefte van anderen om te weten waar het nu in de kern om gaat.",
    skills: "analytisch, oog voor details (detail georienteerd), nieuwsgierigheid, fijngevoelig, precies. Ook expliciet gekoppeld in handboek: Aandacht voor details, Analyseren/Focussen, Luisteren.",
    blindSpot: "Je vergeet door te dringen tot de kern van je behoefte. Je dringt niet goed door tot de kern van je behoefte. Hierdoor kun je niet goed vaststellen of iets jou verder helpt en stel je dingen aangaande jezelf uit.",
    compensation: "Je compenseert door steeds alles te moeten analyseren.",
    example: "Controllers binnen de organisatie die management-informatie geven; marketing managers die marktgegevens analyseren en een zinvol marketingadvies opleveren; wetenschappers die systematisch (delen van) Gods schepping onderzoeken en daar een zinvolle analyse van maken.",
    hulpvraag: "Houdt u ervan om iets te analyseren? Vertel daar eens iets over?",
    schakelvraag: "Wat is volgens jou de kern van mijn behoefte?",
    dirkWords: "Iemand met kennisproductietalent zegt: jongens, we trekken dat putje hier in die oceaan eruit, dan loopt het water weg en kunnen we samen zien hoe die ijsberg eruitziet. Dan weten we ook wat er werkelijk aan de hand is, zodat we geen symptomen bestrijden, maar echt de oorzaak van het probleem boven water tillen. Het produceert kennis: van ruwe data naar informatie naar analyse — dit is een appel, dat is zinvolle informatie.",
  },
  {
    number: 2,
    slug: "formulering",
    name: "Formulering",
    code: "B1",
    column: "Zekerheid",
    alias: "Formuleringtalent (Jane® officieel)",
    quote: "Ik doorzie de bedoelingen van anderen snel en formuleer deze helder en duidelijk",
    description: "Het formuleringstalent (ook 'kennisformuleringstalent') brengt geanalyseerde kennis over in de taal van de ander, zodat die zich het kan eigen maken. Het stemt de boodschap af op de ontvanger — financiële mensen, de werkvloer of grote klanten krijgen elk hun eigen vertaling. Daardoor ontstaat het eerste vertrouwen: de ander merkt 'ja, dat is precies wat ik bedoel'. Wie het sterk heeft, kan zich zo soepel aanpassen dat het soms gladjes overkomt.",
    definition: "Formuleringtalent drukt wensen en bedoelingen helder en duidelijk uit. Natuurlijke aanleg en motivatie om gedachten, wensen of bedoelingen passend en precies tot uitdrukking te brengen. Voorziet in de behoefte van anderen aan scherpe verwoording van hun eigen gedachten en gevoelens, begrepen te worden en in hun eigen 'taal' te kunnen spreken.",
    skills: "uitdrukkingsvaardig, communicatief, beargumenteren, reflecteren, aanpassingsvermogen. Ook: Conflict hanteren, Mondeling communiceren, Reflecteren.",
    blindSpot: "Je vergeet je eigen verlangens onder woorden te brengen. Je brengt je verlangens niet goed onder woorden. Hierdoor kun je ze niet goed eigen maken en delen met anderen. Hierdoor weten anderen niet wat jij wilt.",
    compensation: "Je compenseert door alle verlangens onder woorden te moeten brengen.",
    example: "Tegen financiële mensen moet je marktinformatie anders brengen dan tegen de jongens op de werkvloer die leiding geven aan de productie. Aan grote klanten in de markt vertel je dingen anders dan aan standaardgebruikers van producten en diensten. Reclame.",
    hulpvraag: "Let u erop hoe u iets onder woorden brengt? Waarom is dat zo?",
    schakelvraag: "Hoe zou jij mijn verlangens onder woorden brengen?",
    dirkWords: "Iemands verbale aanleg zou je kunnen beschrijven als een soort schijf, een computerschijf. Je kunt er een programma op zetten — een redeneerprogramma, Windows, Word — maar je gebruikt hem ook als geheugen, want hier staan Word-documenten. Bij mensen met een lage score op kennisformuleringstalent gebruiken ze hun schijf meer als geheugen — het redeneerprogramma is dan niet zo groot.",
  },
  {
    number: 3,
    slug: "investering",
    name: "Investering",
    code: "C1",
    column: "Bestemming",
    alias: "Kennisinvesteringstalent",
    quote: "Ik anticipeer graag op zaken en investeer graag energie in de juiste dingen",
    description: "Het investeringstalent (ook 'kennisinvesteringstalent') herkent patronen in de markt en trekt die door naar de toekomst, waardoor het ontwikkelingen als het ware kan voorspellen. Zo weet iemand wanneer een product vervangen moet worden of welke research nu al nodig is. Hetzelfde patroongevoel werkt ook in de levens van mensen, bij het inschatten van iemands bestemming. Het steekt anderen aan om in het juiste te investeren en is gericht op verantwoorde groei.",
    definition: "Investeringstalent doorziet en haakt aan op patronen in de omgeving. Natuurlijke aanleg en motivatie om een patroon te zien, te begrijpen en daarop in te haken. Voorziet in de behoefte van anderen aan het ontdekken van het unieke en eigen van zichzelf en dit te ontwikkelen.",
    skills: "anticiperen, initiatief nemen, reflecteren, patronen herkennen, slagvaardig handelen. Ook: Anticiperen, Authenticiteit, Inlevingsvermogen.",
    blindSpot: "Je vergeet het patroon te zien in je ervaring en haar betekenis. Je ziet geen patroon of trend in je kennis, ervaring en talenten. Hierdoor investeer je niet altijd in precies datgene waar je kracht en bijzondere waarde ligt.",
    compensation: "Je compenseert door altijd een bepaald patroon in iets te moeten zien.",
    example: "Marketing managers en marketing directors die patronen in de markt herkennen en zeggen: dat product moeten we misschien snel gaan vervangen, want je ziet ontwikkelingen, je ziet patronen. We moeten alvast research doen, want over anderhalf jaar moeten we met een nieuw product komen en het andere afbouwen. Professionele beleggers — niet iedereen die belegt heeft dat talent. Ook: iemand bij de EO die het patroon zag in de levens van mensen die werden aangenomen — 'die moet je doen of die moet je niet doen, dat wordt nooit wat' — bingo bleek hij telkens te hebben.",
    hulpvraag: "Herkent u snel een bepaald patroon of een trend in dingen die u ziet?",
    schakelvraag: "Welke trend zie jij in mijn kennis, ervaring en talenten?",
    dirkWords: "Stel dat je een behangetje ziet: bloemetje, steeltje, bloemetje, steeltje. Trek je het er vanaf — wat komt hier nou? Daar is een bloemetje, dan zal daar wel een steeltje, daar weer een hè. Dus als je het patroon ziet, kun je voorspellen — tussen aanhalingstekens — aangeven hoe dat patroon zich doorzet. Dat is kennisinvesteringstalent.",
  },
  {
    number: 4,
    slug: "onderscheiding",
    name: "Onderscheiding",
    code: "A2",
    column: "Werkproces",
    quote: "Ik ben to-the-point en denk graag in hoofd- en bijzaken",
    description: "Het onderscheidingstalent ziet in het hier en nu meteen welke middelen relevant zijn om een probleem op te lossen, zonder eindeloos alle kennis op tafel te leggen. Het maakt mensen slagvaardig en to the point: ze zien direct wat er nodig is en doen het ook. In een vergadering houden zij agendapunten netjes uit elkaar. Wie het mist, haalt punten door elkaar of pakt zaken minder doelgericht aan.",
    definition: "Onderscheidingstalent onderscheidt snel wat wel en niet relevant is. Natuurlijke aanleg en motivatie om snel en makkelijk te onderscheiden wat wel en niet relevant is in situaties. Voorziet in de behoefte van anderen om bezig te zijn met relevante zaken, geen symptomen te bestrijden en oplossingen.",
    skills: "oplossingsgericht, to-the-point, onderscheidingsvermogen, analytisch, aanpassingsvermogen. Ook: Analyseren/Focussen, Besluitvaardig, Commercieel inzicht, Conflict hanteren, Initiatief, Luisteren.",
    blindSpot: "Je vergeet vast te stellen wat relevant is voor jouw behoefte. Je weet niet wat relevant is voor je behoefte. Daardoor stel je keuzes uit om in een bepaalde behoefte te voorzien.",
    compensation: "Je compenseert door alleen maar te reageren als het relevant lijkt.",
    example: "Matthijs die binnenkomt waar iedereen worstelt met de koffiepotten, ziet anderhalve seconde aan, zegt 'ga maar even van de kant', regelt het en iedereen heeft koffie. In vergaderingen: iemand met onderscheidingstalent houdt de agenda zuiver bij punt C — degenen zonder halen B er weer bij of trekken D ervoor.",
    hulpvraag: "Soms weiden mensen uit en zijn ze niet to-the-point. Wat vind u daarvan?",
    schakelvraag: "Wat is volgens jou nodig gezien mijn behoefte?",
    dirkWords: "Onderscheidingstalent is in het hier en nu, wat is nu relevant voor deze situatie. Vandaar dat mensen met onderscheidingstalent heel erg to the point kunnen zijn, slagvaardig in het hier en nu. Matthijs komt binnen, ziet dat anderhalve seconde aan en zegt: ga maar even van de kant. Pats, geregeld. Een talent wil graag gebruikt worden.",
  },
  {
    number: 5,
    slug: "inleving",
    name: "Inleving",
    code: "B2",
    column: "Zekerheid",
    quote: "Ik verplaats me makkelijk in de schoenen van een ander",
    description: "Het inlevingstalent verplaatst zich volledig in de belevingswereld van de ander om te begrijpen hoe die iets ervaart, en stemt de omgeving daarop af. Pas als je weet hoe iemand dingen beleeft, kun je je kennis en ervaring goed overbrengen; dat schept ook vertrouwen. Mensen voelen zich gehoord en kunnen alles kwijt. Wie veel inlevingsvermogen heeft, kan de last van de ander echter meedragen en moet die soms bewust van zich afschudden.",
    definition: "Inlevingstalent leeft zich makkelijk in de belevingswereld van anderen in. Natuurlijke aanleg en motivatie om me makkelijk en snel mee te laten nemen in de beleving van anderen. Voorziet in de behoefte van anderen aan iemand die zich kan inleven in hun situatie, een luisterend oor kan bieden en het juiste begrip toepast.",
    skills: "inlevingsvermogen, luistervaardigheid, sensitiviteit, empathie, reflecteren. Ook: Afstand bewaren (laag), Beinvloeden, Coachen, Commercieel inzicht, Diversiteit hanteren, Empathie, Inlevingsvermogen, Luisteren, Reflecteren, Samenwerking.",
    blindSpot: "Je vergeet je in te leven in jezelf. Je staat niet stil bij hoe je iets van binnen ervaart en beleeft. Hierdoor kun je je verlangen niet matchen met wat er in je zit en leidt je verlangen niet tot actie.",
    compensation: "Je compenseert door alleen maar naar anderen te moeten luisteren.",
    example: "Mensen met een therapeutische rol of beroep: maatschappelijk werkers, sommige psychologen. Ze kunnen die last meenemen naar huis: 'ik moet het echt even van me afschudden, ik moet me even uit die belevingswereld van die ander weer halen, want het was nu mooi genoeg geweest'. Een product presenteren bij een zorginstelling met teveel commerciële begrippen — 'wij zijn niet zo commercieel hoor'.",
    hulpvraag: "Hoe verplaatst u zich in anderen? Geef een voorbeeld?",
    schakelvraag: "Hoe ervaar en beleef jij mij?",
    dirkWords: "Je duikt in de belevingswereld van de ander, je wilt weten hoe beleef jij dat nou? Ik laat me helemaal meenemen in de manier waarop je dat ook vertelt — met geuren en kleuren — oh, dus zo beleef je dat. Vertel dat nog eens. Het is heel belangrijk om je te verplaatsen in de ander: hoe beleeft, hoe ervaart hij dat?",
  },
  {
    number: 6,
    slug: "combinatie",
    name: "Combinatie",
    code: "C2",
    column: "Bestemming",
    quote: "Ik ben creatief, ga graag voor een aanpak op maat en wil dat zaken goed uit de verf komen",
    description: "Het combinatietalent beschikt over een enorm reservoir aan ideeën en koppelt die aan iemands identiteit en bestemming, niet alleen aan de situatie of de persoon. Het produceert vrijwel automatisch een stroom van mogelijkheden om dat unieke plan tot zijn recht te laten komen. Zo komen soms ideeën naar boven die ver van het gangbare denken liggen. Het maakt iemand inventief en creatief in het bedenken van wat ergens bij past.",
    definition: "Combinatietalent brengt het unieke van iets of iemand naar voren. Natuurlijke aanleg en motivatie om het unieke van iets of iemand uit de verf te laten komen. Voorziet in de behoefte van anderen aan ideeen, oplossingen en vernieuwingen die op maat zijn en passen bij de unieke identiteit.",
    skills: "creatief denken, oplossingsgerichtheid, observeren, ideeen aandragen, klantgerichtheid. Ook: Creativiteit, Innovativiteit.",
    blindSpot: "Je vergeet het unieke van jezelf uit de verf te laten komen. Je vermijdt ideeën die het unieke van jou uit de verf kunnen halen. Hierdoor hebben anderen niet goed zicht op jouw bijzondere waarde.",
    compensation: "Je compenseert door aldoor met nieuwe ideeën te moeten komen.",
    example: "Einstein. Sollicitaties: je zoekt een flexibel persoon die ook inventief is, of een creatief iemand. Ja, maar hij moet wel wat structuur hebben hoor, Dirk. Combinatie van talenten — niet extreem.",
    hulpvraag: "Komt u snel met ideeen als iemand met een probleem zit?",
    schakelvraag: "Hoe kan het unieke, het bijzondere van mezelf beter uit de verf komen?",
    dirkWords: "Combinatietalent gaat over: wat is niet relevant voor die persoon, maar wat is relevant voor zijn identiteit, voor zijn bestemming. Vandaar dat combinatietalent over een enorm groot reservoir van ideeën beschikt — misschien honderden miljarden, om nog meer. Druk je op die knop, dan gaat die machine allemaal ideeën produceren, die komen allemaal vanzelf naar boven, een paar per seconde.",
  },
  {
    number: 7,
    slug: "routine",
    name: "Routine",
    code: "A3",
    column: "Werkproces",
    quote: "Ik zie effectieve routines als een belangrijke basis voor een goed resultaat",
    description: "Het routinetalent geeft de natuurlijke aanleg en motivatie om op een ingeslagen weg door te gaan, net zolang tot het resultaat zichtbaar wordt. Het zorgt voor doorzettingsvermogen en discipline bij het uitvoeren van een gekozen strategie. Wie het sterk heeft, kan echter ook te lang vasthouden aan een oude aanpak en moeilijk omschakelen. Anderen zonder dit talent worden al snel als ongedisciplineerd of ongeduldig ervaren.",
    definition: "Routinetalent volhardt in een specifieke werkwijze. Natuurlijke aanleg en motivatie om in routines te werken die een stabiele kwaliteit leveren. Voorziet in de behoefte van anderen om door te zetten en vast te houden aan een succesvolle werkwijze, effectieve processen en stabiele output.",
    skills: "routinematigheid, discipline, geduld, ordenen, bedachtzaamheid. Ook: Accuraat/Zorgvuldig, Discipline, Doelen stellen.",
    blindSpot: "Je vergeet routines te maken die in jouw behoefte voorzien. Je hebt geen routines die ingaan op wat jij nodig hebt. Dit gaat ten koste van een goede zorg voor jezelf.",
    compensation: "Je compenseert door door te moeten blijven gaan op je routines.",
    example: "Een directeur van een vissersvloot met extreem hoog routinetalent (bij managers vind je dat doorgaans niet zo gigantisch hoog); medewerkers bij McDonald's die diezelfde routine elke keer opnieuw uitvoeren; bidden: net zolang doorgaan tot er resultaat komt.",
    hulpvraag: "Houdt u van het werken met routines? Waarom eigenlijk?",
    schakelvraag: "Welke routines zijn nodig gezien mijn behoefte?",
    dirkWords: "Routinetalent is een natuurlijke aanleg en motivatie om op een bepaalde ingeslagen weg door te gaan. We hebben besloten om die strategie uit te voeren — nou, we gaan gewoon door, net zolang tot het resultaat zichtbaar wordt. Met gebed is het ook zo: we gaan net zolang doorbidden tot er resultaat komt. Eén dag gebeden, werkt het niet — dat klopt niet, die routine werkt niet hoor.",
  },
  {
    number: 8,
    slug: "argumentatie",
    name: "Argumentatie",
    code: "B3",
    column: "Zekerheid",
    quote: "Ik wil graag van invloed zijn en weet mijn ideeen goed over te brengen",
    description: "Het argumentatietalent motiveert en overtuigt mensen met argumenten waarom een bepaalde werkwijze of routine nodig is. Het maakt duidelijk waaróm iets op een bepaalde manier moet gebeuren, of dat nu naar medewerkers of naar klanten is. Het richt zich vooral op overtuiging op de korte termijn. Het gevaar is dat iemand zijn overtuigingskracht gaat gebruiken om anderen te manipuleren of voor zijn karretje te spannen.",
    definition: "Argumentatietalent beredeneert en verdedigt de wil voor iets. Natuurlijke aanleg en motivatie om zaken te beredeneren en van invloed te zijn op de omgeving. Voorziet in de behoefte van anderen aan de juiste argumenten, om overgehaald en bewogen te worden.",
    skills: "analyseren, argumenteren, adviseren, rationeel/kritisch denken, beinvloeden. Ook: Argumenteren/Discussieren/Overtuigen, Beinvloeden, Coachen, Reflecteren.",
    blindSpot: "Je vergeet jezelf van iets te overtuigen om iets te willen. Je overtuigt jezelf niet met motieven en argumenten om iets te willen. Hierdoor wordt je verlangen niet omgezet in iets wat je wilt en blijft dit op de achtergrond.",
    compensation: "Je compenseert door anderen van iets te moeten overtuigen.",
    example: "Medewerker bij McDonald's: 'we kunnen die broodjes toch ook wel anders maken? Ik heb zelf broodjes meegenomen van thuis, kun je toch ook voorzetten?' Dat wordt killing voor zo'n vestiging — je moet mensen overtuigen waarom ze die routines zo moeten uitvoeren.",
    hulpvraag: "Hoe motiveert en overtuigt u anderen? Voorbeeld? Was dat altijd zo bij u?",
    schakelvraag: "Welke argumenten zijn volgens jou doorslaggevend als ik dit of dat wil?",
    dirkWords: "Een strategie is mooi, die routines hebben we, maar we moeten mensen vertellen en motiveren waarom ze die routines moeten uitvoeren. Waarom moet dat dan? Je kan het toch ook zo? Dat is de functie van het argumentatietalent. Je moet dingen gewoon met argumenten over kunnen brengen. Het gevaar is dat hij denkt: ik kan anderen wel voor mijn karretje spannen — kan in die val trappen.",
  },
  {
    number: 9,
    slug: "uitleg",
    name: "Uitleg",
    code: "C3",
    column: "Bestemming",
    alias: "Docenttalent",
    quote: "Ik neem graag de tijd mogelijke risico",
    description: "Het uitlegtalent (door Dirk 'docenttalent' genoemd) draait om het foutloos overbrengen van kennis of een werkwijze, zodat mensen weten wat ze precies moeten doen. Zoals lesstof via de docent de klas in gaat: één fout vooraan wordt dertig keer verkeerd doorgegeven, en daarom hecht dit talent sterk aan integriteit en kwaliteit op lange termijn. Wie het heeft, vereenzelvigt zich met zijn taak en is daardoor extra gevoelig voor kritiek. Een nieuw vraagstuk laat het van alle kanten 'rondcirkelen' voordat er een doordachte reactie komt.",
    definition: "Uitlegtalent rekent nauwkeurig mogelijke consequenties door. Natuurlijke aanleg en motivatie om te anticiperen op mogelijke scenario's en fouten te voorkomen. Voorziet in de behoefte van anderen aan een zorgvuldige analyse en voorbereiding met het doel risico's te vermijden.",
    skills: "zorgvuldigheid, anticiperen, beinvloeden, voorstellingsvermogen, beredeneren. Ook: Aandacht voor details, Accuraat, Durf (laag).",
    blindSpot: "Je vergeet planmatig aan je droom te werken. Je hebt geen planmatige aanpak om het unieke van jezelf tot verdere ontwikkeling te brengen. Dit belemmert het realiseren van je unieke bestemming.",
    compensation: "Je compenseert door stringent vast te moeten houden aan jouw plan.",
    example: "Een docent die instructie geeft, voorbeelden gebruikt, leerlingen overtuigt waarom de stof belangrijk is. Medewerkers in de productie die een nieuwe processtraat krijgen — veel uitleg, training, herhaling, om te zorgen dat het wordt uitgevoerd zoals oorspronkelijk bedoeld.",
    hulpvraag: "Broed u wel eens op iets? Geef een voorbeeld. Hoe komt dat?",
    schakelvraag: "Hoe zou jij mijn unieke waarde op een planmatige wijze verder ontwikkelen?",
    dirkWords: "De essentie van docenttalent is dat die lesstof als het ware door de docent heen de klas in gaat. En als de docent één keer een foutje maakt, dan gaat het daar 30 keer fout. Vervang het woord lesstof door baan of mijn functie — dan identificeren mensen zich daar heel sterk mee. Kritiek op hoe ze hun functie uitvoeren is hetzelfde als kritiek op mijn persoonlijkheid — een pijl die vol recht in mijn lichaam komt.",
  },
  {
    number: 10,
    slug: "helpen",
    name: "Helpen",
    code: "A4",
    column: "Werkproces",
    quote: "Ik zet me makkelijk in voor anderen",
    description: "Het helptalent (vroeger 'servicetalent') verleent graag en bekwaam assistentie bij een grote verscheidenheid aan vragen. Het wacht tot iemand om hulp vraagt en springt dan zelf bij — niet doorschuiven, maar zelf de mouwen opstropen. Het is een belangrijke pijler in de servicegerichtheid van een organisatie: de klant belt, wij antwoorden. Wie het weinig heeft, helpt alleen op het eigen vakgebied en laat de rest aan een ander over.",
    definition: "Helptalent reageert alert op de hulpsignalen in de omgeving. Natuurlijke aanleg en motivatie om alert op de hulpsignalen van anderen in mijn omgeving te reageren. Voorziet in de behoefte van anderen om verder geholpen te worden.",
    skills: "hulpvaardig, sociaal, collegialiteit, benaderbaarheid, servicegericht. Ook: Betrokkenheid, Coachen/Feedback, Conflict hanteren, Inlevingsvermogen, Samenwerking.",
    blindSpot: "Je vergeet je eigen wensen goed vast te stellen. Je geeft geen aandacht aan je persoonlijke wensen. Een wens is een voorkeur om iets op een bepaalde manier te doen die past bij jouw persoonlijkheid.",
    compensation: "Je compenseert door op de hulpvragen van anderen te moeten ingaan.",
    example: "De telefoon van een onderneming: 'als mensen bellen, hoe graag wordt er dan geholpen?' Het is een belangrijke pijler in het value systeem van een organisatie: u belt, wij antwoorden.",
    hulpvraag: "Als iemand een beroep doet op uw hulp hoe reageert u dan? Voorbeeld?",
    schakelvraag: "Welke manier past bij mij zoals je me kent?",
    dirkWords: "Helptalent is de essentie: God heeft het zo gemaakt dat iemand met helptalent capaciteit heeft om in een veelsoortigheid van vragen gewoon assistentie te verlenen. Als ik vol met mijn tijd zit en iemand komt direct toch helpen, maar ik zeg nee — dan zegt iemand met helptalent: oh joh, vind ik dit nou jammer, ik zit er echt mee dat ik niet kan helpen.",
  },
  {
    number: 11,
    slug: "signaleren",
    name: "Signaleren",
    code: "B4",
    column: "Zekerheid",
    alias: "Ontfermtalent",
    quote: "Ik heb vrij snel en makkelijk door waar iemand of de situatie om vraagt",
    description: "Het signaleertalent (door Dirk 'ontfermtalent' genoemd) pikt behoeftesignalen vroeg op en anticipeert erop, vaak nog voordat de ander iets gevraagd heeft. Het heeft gevoel voor timing op de middellange termijn: je belt iemand net op het moment dat hij ook aan jou dacht. In plaats van zelf de taak uit te voeren schakelt dit talent de juiste persoon in om het te laten gebeuren. Het maakt dat mensen zich alert en attent geholpen voelen.",
    definition: "Signaleertalent reageert alert op de behoeftesignalen in de omgeving. Natuurlijke aanleg en motivatie om sensitief te zijn op signalen in mijn omgeving en hier alert op te reageren. Voorziet in de behoefte van anderen aan de reactie op het juiste moment.",
    skills: "besluitvaardigheid, aanpassingsvermogen, omgevingssensitiviteit, instinctief handelen, initiatief nemen. Ook: Anticiperen, Besluitvaardig, Collegialiteit, Empathie, Initiatief, Inlevingsvermogen.",
    blindSpot: "Je vergeet om te reageren op je eigen behoeftesignalen. Je negeert je eigen behoeftesignalen. Hierdoor vertaal je datgene wat je wilt niet naar een beslissing of initiatief.",
    compensation: "Je compenseert door te moeten reageren op behoeftesignalen van anderen.",
    example: "'Ik zal die club nog eens bellen, kijken hoe het gaat.' Of bij koffie: 'jongens, hier hebben we te weinig koffie, ik bel even, ik zorg dat het gebracht wordt — ik heb me ontfermd, ik pak het op, ik ga niet zelf koffie brengen, maar ik zorg dat het gebeurt, ik schakel iemand anders in.'",
    hulpvraag: "Hoe neemt u beslissingen? Waarom zo snel of waarom zo langzaam?",
    schakelvraag: "Welk initiatief moet ik volgens jou nemen als ik dit of dat wil?",
    dirkWords: "Ontfermtalent is: ik zal die club nog eens bellen, kijken hoe het gaat. Heel vaak als jij mensen belt zeggen ze: goh, is ook toevallig, je belt op het goede moment, je stond bij mij ook op het lijstje. Dat is een gevoel voor timing op de middellange termijn. Helpen is: de klant belt, wij antwoorden. Ontfermen is: u hoeft niet te bellen, want op het juiste moment bellen wij u.",
  },
  {
    number: 12,
    slug: "etaleren",
    name: "Etaleren",
    code: "C4",
    column: "Bestemming",
    alias: "Presentatietalent",
    quote: "Ik vestig graag op een aantrekkelijke wijze de aandacht voor zaken en waardeer stijl en presentatie",
    description: "Het etaleertalent richt zich erop hoe aantrekkelijk een organisatie of aanbod zich in de markt presenteert. Het zorgt voor een uitnodigende uitstraling via middelen als folders, brochures en websites, zodat mensen vanzelf worden aangetrokken. Het vormt samen met helpen en signaleren een pijler van het waardesysteem van een onderneming. Een goede balans betekent dat de aantrekkelijke presentatie in verhouding staat tot het daadwerkelijk helpen en oppikken van behoeften.",
    definition: "Etaleertalent profileert zich op een aantrekkelijke wijze aan de omgeving. Natuurlijke aanleg en motivatie om op een aantrekkelijke manier aandacht te vragen voor het unieke van iets of iemand. Voorziet in de behoefte van anderen om zich te identificeren en aan een aantrekkelijke (re)presentatie van iets of iemand.",
    skills: "presenteren, profileren, tact hebben, creativiteit, assertiviteit. Ook: Ambitieus, Mondeling communiceren, Profileren/Presenteren.",
    blindSpot: "Je vergeet jouw unieke waarde zichtbaar te maken. Je vermijdt dat jouw unieke waarde teveel zichtbaar wordt. Hierdoor weten anderen niet wat jij hebt te bieden.",
    compensation: "Je compenseert door steeds op de voorgrond aanwezig te moeten zijn.",
    example: "Een onderneming met een budget van een kwart miljoen aan folders, brochures en websites — dat is etaleertalent. Soms zit er onbalans in de organisatie: 'we helpen wel als ze bellen, maar pakken niet zo alert een behoeftesignaal op, maar we doen wel veel — we hebben wel een budget voor een kwart miljoen aan folders en brochures en aan websites.'",
    hulpvraag: "Vindt u het belangrijk dat u goed voor de dag komt? Waarom is dat zo?",
    schakelvraag: "Hoe zou jij mijn unieke waarde op een aantrekkelijke wijze presenteren?",
    dirkWords: "Hoe aantrekkelijk presenteren jullie jezelf in de markt? Dan vind je wel eens onbalans tussen: we helpen wel als ze bellen, maar pakken niet zo alert een behoeftesignaal op, maar we doen wel veel — we hebben wel een budget voor een kwart miljoen aan folders en brochures en aan websites.",
  },
  {
    number: 13,
    slug: "vertrouwen",
    name: "Vertrouwen",
    code: "A5",
    column: "Werkproces",
    alias: "Brontalent",
    quote: "Ik ga er graag van uit dat anderen capabel zijn en wil dit ook benutten",
    description: "Het vertrouwenstalent (door Dirk 'brontalent' genoemd) durft mensen in te zetten en te betrekken bij het werk, omdat het erop vertrouwt dat zij iets kunnen — ook zonder dat alles al bewezen is. Als een herder die zijn schapen een onbekende weide in leidt, durft het met vertrouwen te ondernemen. Daardoor krijgen mensen ruimte om zich te ontwikkelen en hun talenten te benutten. Wie het sterk heeft, kan naïef overkomen; wie het mist, is eerder wantrouwend en houdt de kat uit de boom.",
    definition: "Vertrouwtalent zet talent, kennis en ervaring van anderen in. Natuurlijke aanleg en motivatie om anderen in mijn omgeving in te schakelen. Voorziet in de behoefte van anderen om de kans, de ruimte en vertrouwen te krijgen om zichzelf te zijn, te laten zien en te ontwikkelen.",
    skills: "ontvankelijkheid, collegialiteit, instinctief, zelfverzekerd, delegeren. Ook: Beinvloeden, Collegialiteit, Delegeren, Diversiteit hanteren, Samenwerking.",
    blindSpot: "Je vergeet te vertrouwen dat je eigen wensen uitvoerbaar zijn. Je gelooft niet dat jouw wensen uitvoerbaar zijn. Dit bemoeilijkt het nemen van stappen om je wensen om te zetten in actie of initiatieven.",
    compensation: "Je compenseert door te moeten blijven vertrouwen dat alles goed komt.",
    example: "Een relatie van Dirk met bijna 100% brontalent, kreeg een idee van God en moest naar Noord-Korea. Geen visum, geen paspoort, alleen een creditcard. De stewardessen waren er klaar mee, zetten hem op het vliegtuig, en bij aankomst zei hij: ja, ik ben hier om jullie land te helpen — komt u maar mee. Ook: een manager die iemand zonder diploma toch op een afdeling zet om marketing te leren.",
    hulpvraag: "Schakelt u anderen gemakkelijk in bij uw werk? Waarom wel/niet?",
    schakelvraag: "Geloof jij dat deze wens uitvoerbaar is? Hoe dan?",
    dirkWords: "Als je niet eh mensen vertrouwt — in de zin dat je mensen vertrouwen geeft dat zij iets kunnen — dan straal je dat geloof niet uit als manager of ondernemer. Dan durf je ze ook niet zomaar in te zetten. Ik zie meestal een herder die met schaapjes rustig de weide intrekt waar hij nog nooit geweest is en zegt: hier moet toch ook lekker gras groeien, let's go schaapjes.",
  },
  {
    number: 14,
    slug: "contact",
    name: "Contact",
    code: "B5",
    column: "Zekerheid",
    quote: "Ik hou van de dagelijkse uitwisseling van gedachten, ervaringen of kennis met anderen",
    description: "Het contacttalent zoekt voortdurend contact met mensen en weet daardoor goed wat er onder hen leeft. Door veel te overleggen en bij te praten ontdekt het wat er in mensen zit, zodat de juiste persoon op de juiste opdracht kan worden gezet. Dirk vergelijkt het met een batterij: bij weinig contacttalent is die na een paar uur leeg en heeft iemand behoefte om zich terug te trekken. Wie het veel heeft, kan in de ogen van anderen soms te veel praten.",
    definition: "Contacttalent is in continue interactie met de omgeving. Natuurlijke aanleg en motivatie om in verbinding met mijn omgeving te zijn. Voorziet in de behoefte van anderen om gestimuleerd te worden om dingen te 'bespreken' en in verbinding te zijn. (Let op: 'Het delen heeft een functie, en het gaat dus niet zozeer om de koetjes en kalfjes'.)",
    skills: "verbindend, contactueel, luistervaardigheid, communicatief, collegialiteit. Ook: Argumenteren, Assertiviteit, Betrokkenheid, Coachen, Collegialiteit, Conflict hanteren, Diversiteit hanteren, Empathie, Luisteren, Mondeling communiceren, Profileren/Presenteren, Samenwerking.",
    blindSpot: "Je vergeet te delen wat je zoal meemaakt. Je deelt te weinig met anderen wat je meemaakt. Hierdoor is er minder zicht op jouw behoeftes, wensen en verlangens en hoe ze jou het beste kunnen inzetten.",
    compensation: "Je compenseert door alles te moeten vertellen wat je zoal meemaakt.",
    example: "Iemand die de hele dag 'even bij je zit te praten, even joh hoe gaat het hier' — daardoor weet je wat er speelt bij mensen en kun je de juiste talenten op de juiste opdracht zetten. Een man die thuis komt en zich terugtrekt, lezen of achter de PC — 'mijn vrouw vindt me asociaal'. Dan moet je de vrouw ook eens testen.",
    hulpvraag: "Deelt u veel van de dingen die u zoal meemaakt met anderen?",
    schakelvraag: "Hoe deel jij dingen die je meemaakt met anderen?",
    dirkWords: "Je hebt iemand die de hele dag even bij je zit te praten — even joh, hoe gaat het hier — en daardoor enorm goed op de hoogte is met wat er speelt bij mensen. Ik gebruik wel eens een plaatje: een batterij. 90% maximum, 10% minimum. Mijn contactbatterij is al op.",
  },
  {
    number: 15,
    slug: "corrigeren",
    name: "Corrigeren",
    code: "C5",
    column: "Bestemming",
    quote: "Ik hou het graag bij de feiten en laat me niet enkel leiden door een eerste indruk of emoties",
    description: "Het correctietalent is sterk op feiten gericht en herinnert anderen daaraan, zodat zij bijgestuurd of getraind kunnen worden. Een correctie op basis van feiten ('je komt elke meeting een half uur te laat') landt, terwijl een correctie op gevoel dat niet doet. Het is nodig om mensen goed te kunnen blijven inzetten en relaties te verdiepen. Dirk beschrijft het als antennes die meer op feiten dan op sfeer en emotie zijn afgestemd.",
    definition: "Correctietalent corrigeert de subjectieve beleving met objectieve feiten. Natuurlijke aanleg en motivatie om uit te gaan van de feiten versus een emotionele indruk. Voorziet in de behoefte van anderen om gewezen te worden op de feitelijke kant van zaken, zeker wanneer er veel emoties in het spel zijn.",
    skills: "stressbestendigheid, rationeel denken, adviseren, geduld, zelfbeheersing. Ook: Adviseren, Afstand bewaren/Stress hanteren, Authenticiteit.",
    blindSpot: "Je vergeet anderen te herinneren aan je unieke betekenis. Je herinnert anderen niet aan het bijzondere van wat jij hebt te bieden. Hierdoor wordt jij niet voldoende benut.",
    compensation: "Je compenseert door anderen steeds te moeten corrigeren.",
    example: "'Joh, je functioneert niet goed op kantoor, want je hebt steeds de verkeerde das aan' — dat landt niet, dat is geen feit. Maar: 'je komt steeds een half uur te laat op elke meeting die we plannen' — dat is een feit, dat kunnen we samen meten, dan heb ik een punt.",
    hulpvraag: "Ziet u snel hoe iets beter kan? Corrigeert u dan de ander? Voorbeeld?",
    schakelvraag: "Hoe kan ik anderen herinneren aan het bijzondere van wat ik heb te bieden?",
    dirkWords: "Iemand corrigeert een ander op basis niet van feiten, maar op basis van een subjectief gegeven of een gevoel — dat landt natuurlijk niet bij de ander. Als ik zeg 'je functioneert niet goed op kantoor, want je hebt steeds de verkeerde das aan', landt dat niet echt. Maar als ik zeg 'je komt steeds een half uur te laat op elke meeting' — dan heb ik een punt, want dat is een feit dat we samen kunnen meten. Waarom heeft God je zo feitelijk gemaakt? Omdat God je wil gebruiken om anderen aan feiten te herinneren.",
  },
  {
    number: 16,
    slug: "doorbraak",
    name: "Doorbraak",
    code: "A6",
    column: "Werkproces",
    alias: "Incasseertalent",
    quote: "Ik kan veel hebben van anderen en doe er makkelijk nog een schepje bovenop",
    description: "Het doorbraaktalent (door Dirk 'incasseer-', 'knok-' of 'vechttalent' genoemd) richt zich op het doorbreken van barrières en blokkades, zodat de workflow door kan gaan en het werk niet blijft liggen. Het laat zich niet ophouden: als iemand even weg is, wordt diegene meteen gebeld zodat anderen niet stil komen te staan. Het kan flink incasseren en zet net zo lang door tot de klus geklaard is. Daardoor maakt het ook een team sterker, al levert het soms 'gele kaarten' op.",
    definition: "Doorbraaktalent incasseert en doorbreekt barrieres om te overwinnen. Natuurlijke aanleg en motivatie om door te zetten, te incasseren of ergens een schepje bovenop te doen. Voorziet in de behoefte van anderen om de ruimte te krijgen en samen er een schepje bovenop te doen.",
    skills: "doorzettingsvermogen, geduldig, oplossingsgericht, incasseervermogen, creatief. Ook: Aanpassingsvermogen, Ambitieus, Assertiviteit (laag), Durf.",
    blindSpot: "Je vergeet de barrières die je wensen tegenhouden op te ruimen. Als het gaat om je wensen laat jij je snel tegenhouden door onverwachte barrières of hindernissen. Dit bemoeilijkt het realiseren van je wensen.",
    compensation: "Je compenseert door alles te moeten incasseren wat er te incasseren is.",
    example: "Voetballer Edgar Davids; ook: een team waar Jan even weg is — 'nee, we moeten nu door, bel hem op zijn 06, anders blijft het werk liggen, anders kunnen vijf mensen een half uur niks doen'. En als het al over tijd is en een klant op alle laat nog iets extra's wil: jongens, zetten we even een uurtje ertegenaan, zorgen we dat de job afkomt.",
    hulpvraag: "Kunt u veel hebben van mensen als ze vervelend of lastig zijn? Hoezo?",
    schakelvraag: "Hoe zou jij deze barrières uit de weg ruimen?",
    dirkWords: "Incasseertalent richt zich op het penetreren, doorbreken van barrières en blokkades in haar omgeving. Mensen willen zorgen dat die workflow doorkan, laten zich niet ophouden. Ja, maar Jan is er even niet — bel hem pas over een half uur. Nee, we moeten nu door. Bel hem op zijn 06. Anders blijft het werk liggen, anders kunnen vijf mensen een half uur niks doen. Dan komt die knok om de hoek.",
  },
  {
    number: 17,
    slug: "beheersen",
    name: "Beheersen",
    code: "B6",
    column: "Zekerheid",
    quote: "Ik hou van duidelijke normen en handhaaf deze graag als ik zie dat dit misgaat",
    description: "Het beheerstalent grijpt op de middellange termijn in zodra dreigt dat de afgesproken kwaliteitsnorm niet wordt gehaald. Het bewaakt vooraf aan welke normen het resultaat moet voldoen en houdt in de gaten of iedereen op schema ligt. Dirk beschrijft een soort automatisch klokje of wekkertje in het hoofd dat aanslaat als iets uit de pas dreigt te lopen. Het ingrijpen kan soms dominant overkomen, maar voorkomt dat de gezamenlijke uitkomst onder de maat blijft.",
    definition: "Beheerstalent legt de lat, bewaakt deze en grijpt in bij afwijking daarvan. Natuurlijke aanleg en motivatie om een bepaalde kwaliteit of norm te stellen en te bewaken. Voorziet in de behoefte van anderen om zichzelf en anderen serieus te nemen, ergens voor te staan en dit te beschermen.",
    skills: "overwicht uitoefenen, aansturen, betrokkenheid, aanspreken op gedrag, assertiviteit. Ook: Accuraat, Beinvloeden, Besluitvaardig, Betrokkenheid, Coachen.",
    blindSpot: "Je vergeet vooraf duidelijke (kwaliteits)normen te stellen. Je stelt niet vast waar je prestatie aan moet voldoen. Hierdoor doe je of te veel of te weinig.",
    compensation: "Je compenseert door (kwaliteits)normen te moeten controleren bij anderen.",
    example: "Een team waar een klant om 5 uur het product komt halen, om 4 uur moet alles af zijn. Het is nu al bijna 3 uur en Pietje zag ik net koffie drinken — dan grijp je in. Sorry, sorry, sorry, maar we willen toch wel… misschien kom ik nu dominant over.",
    hulpvraag: "Grijpt u in als u ziet dat iets dreigt mis te gaan? Voorbeeld? Waarom?",
    schakelvraag: "Waar moet mijn prestatie aan voldoen?",
    dirkWords: "Organiseren op middellange termijn is dat je van tevoren aangeeft aan welke kwaliteitsnormen de uitkomst van onze gezamenlijke inspanningen moet voldoen. Jantje doet dit, Pietje doet dat, om 4 uur kunnen we dat hebben. Maar het is nu al bijna 3 uur en Pietje zag ik net koffie drinken — dan grijp je in. Mensen met beheerstalent hebben een soort automatisch wekkertje in hun hoofd, kijken af en toe naar de klok.",
  },
  {
    number: 18,
    slug: "vertalen",
    name: "Vertalen",
    code: "C6",
    column: "Bestemming",
    quote: "Ik maak zaken graag simpel en toegankelijk voor mezelf en anderen met behulp van instructies",
    description: "Het vertaaltalent licht zaken toe met voorbeelden en instructie, zodat een ander precies begrijpt hoe iets moet worden uitgevoerd. Het zet kennis of een werkwijze om in heldere, toegankelijke aanwijzingen — in een leersituatie maakt het de stof concreet en behapbaar. Het komt sterk naar voren wanneer mensen een nieuwe werkwijze of nieuwe machines onder de knie moeten krijgen en daarbij veel uitleg en herhaling nodig hebben. Zo zorgt het ervoor dat iets daadwerkelijk wordt uitgevoerd zoals het bedoeld is.",
    definition: "Vertaaltalent vereenvoudigt en vertaalt complexiteit door simpele instructie. Natuurlijke aanleg en motivatie om dingen toegankelijk te maken voor mezelf en anderen. Voorziet in de behoefte van anderen om zaken simpel en toegankelijk te maken.",
    skills: "rationeel denken, reflectief, adviseren, demonstreren, instructies geven. Ook: Accuraat, Afstand bewaren, Analyseren/Focussen, Authenticiteit, Reflecteren.",
    blindSpot: "Je vergeet te vertellen hoe anderen jou kunnen benutten. Je maakt niet duidelijk hoe wij jouw unieke waarde het beste kunnen benutten.",
    compensation: "Je compenseert door anderen steeds te moeten instrueren.",
    example: "Een docent die zegt: 'ik licht wat dingen toe, ik gebruik wat voorbeelden, ik geef instructie — ik heb vertaaltalent.' Zo gaan kinderen het boek wel lezen.",
    hulpvraag: "Bent u van nature optimistisch? Hoe instrueert u anderen?",
    schakelvraag: "Hoe moet ik anderen instrueren om mijn unieke waarde te benutten?",
    dirkWords: "Ik licht wat dingen toe, ik gebruik wat voorbeelden, ik geef instructie — ik heb vertaaltalent.",
  },
  {
    number: 19,
    slug: "route",
    name: "Route",
    code: "A7",
    column: "Werkproces",
    quote: "Ik ben expressief en wil de dingen graag op mijn eigen manier doen",
    description: "Het routetalent geeft een automatisch gevoel voor de juiste richting en koers in het hier en nu. Mensen met dit talent pionieren graag, ontdekken dingen liever zelf en hebben moeite met regels en handboeken. Ze komen zelfstandig en authentiek over en hechten sterk aan wat echt en origineel is. Daardoor kunnen ze lastig te managen zijn en met hun gedachten al in de toekomst bezig zijn terwijl ze fysiek aanwezig zijn.",
    definition: "Routetalent onderzoekt, ziet en bepaalt de juiste richting voor zichzelf. Natuurlijke aanleg en motivatie om zelfstandig te pionieren in het vinden van de juiste route voor mezelf en anderen. Voorziet in de behoefte van anderen om richting te ontvangen maar ook geinspireerd te worden in hun eigen zelfstandigheid en expressiviteit.",
    skills: "zelfstandig, loyaliteit, onafhankelijk, verantwoordelijkheidsgevoel, creatief. Ook: Ambitieus, Authenticiteit, Besluitvaardig, Coachen, Discipline (laag), Initiatief.",
    blindSpot: "Je vergeet expressie te geven aan je diepere verlangens. Je geeft geen expressie aan diepere verlangens. Dit bemoeilijkt het vaststellen van de juiste richting waarin jouw verlangens de ruimte krijgen.",
    compensation: "Je compenseert door alles op je eigen houtje te moeten doen.",
    example: "Mensen die in sollicitatiegesprekken sterk overkomen vanwege hun originaliteit en authenticiteit; cowboy-achtige types die zelfstandig opereren; planning in het hier en nu: hoe moet ik over 5 seconden plannen?",
    hulpvraag: "Werkt u graag zelfstandig? Geef een voorbeeld. Was dat altijd al zo?",
    schakelvraag: "Hoe zou ik meer expressie kunnen geven aan diepere verlangens?",
    dirkWords: "Mensen met routetalent willen graag pionieren, hebben moeite met regels en handboeken — ze kunnen zich daar gewoon niet aan houden. Ze komen zelfstandig over, stralen dat ook uit. 'Heb je helemaal geen handboek nodig?' Hoezo? Ik ontdek het liever zelf. Het aantrekkelijke zit in het gevoel voor het originele en het authentieke.",
  },
  {
    number: 20,
    slug: "structuur",
    name: "Structuur",
    code: "B7",
    column: "Zekerheid",
    quote: "Ik hou van overzicht en efficiency en ik ben daardoor makkelijk beschikbaar voor anderen",
    description: "Het structuurtalent houdt vast aan een afgesproken structuur en heeft veel gevoel voor efficiency op de middellange termijn. Het wijst erop dat steeds afwijken van afspraken alle efficiëntie ondermijnt, en houdt van een transparante, toegankelijke aanpak. Klanten waarderen het dat dingen efficiënt en voorspelbaar verlopen. Het nadeel is dat anderen het soms inflexibel of radicaal vinden, omdat het moeite heeft met het sluiten van compromissen op dit punt.",
    definition: "Structuurtalent brengt structuur en ordening aan in de omgeving. Natuurlijke aanleg en motivatie om overzicht, orde en structuur aan te brengen in mijn omgeving. Voorziet in de behoefte van anderen aan iemand die beschikbaar is en structuur, orde en overzicht brengt met het oog op efficiency.",
    skills: "organiseren, structureren/ordenen, plannen, doelmatig werken, zelfstandigheid. Ook: Aanpassingsvermogen, Accuraat, Discipline, Doelen stellen.",
    blindSpot: "Je vergeet systematisch ervaring met jezelf op te doen. Je doet niet systematisch ervaring op met je talenten. Hierdoor krijg je niet goed zicht op alles wat in potentie in je zit.",
    compensation: "Je compenseert door vast te moeten houden aan een bepaalde structuur.",
    example: "'Maar we hebben toch afgesproken? Het is toch efficiënt om het zo te doen — en nou wijken jullie daar weer vanaf? Hoe kan dit?'",
    hulpvraag: "Houdt u vast aan een bepaalde structuur of wisselt dat bij u? Voorbeeld?",
    schakelvraag: "Hoe kan ik systematisch ervaring opdoen met mijn talenten?",
    dirkWords: "Routetalent heeft veel gevoel voor de juiste cursus op korte termijn — en wie heeft nou veel gevoel voor structuur op de middellange termijn? Het structuurtalent. 'Want we hebben toch afgesproken? Dat is toch efficiënt om het zo te doen. En nou wijken jullie daar weer vanaf — hoe kan dit?",
  },
  {
    number: 21,
    slug: "harmonie",
    name: "Harmonie",
    code: "C7",
    column: "Bestemming",
    quote: "Ik stem graag af en grijp in wanneer iets of iemand uit balans dreigt te raken",
    description: "Het harmonietalent blijft in overleg en contact met anderen en voelt daardoor op lange termijn aan welke richting eraan zit te komen. Door af te stemmen weet het wat er verandert — groei, afstoting of nieuwe opdrachten — en kan het veel verschillende mensen en klanten aan. De kern is de bereidheid om te ondergaan en op te nemen wat een ander te bieden heeft. Wie het weinig heeft, vindt dat iemand met veel harmonietalent te veel wil overleggen.",
    definition: "Harmonietalent zoekt continue naar de balans met de omgeving. Natuurlijke aanleg en motivatie om de balans te zoeken en te bewaken in mijn omgeving, voor mezelf en anderen. Voorziet in de behoefte van anderen dat er rekening met ze wordt gehouden en betrokken te worden middels afstemmen en klankborden.",
    skills: "afstemmen, kritisch denken, sensitiviteit, assertiviteit, betrokkenheid. Ook: Conflict hanteren, Diversiteit hanteren, Reflecteren, Samenwerking.",
    blindSpot: "Je vergeet jouw waarde op die van anderen af te stemmen. Je stemt je droom niet af op die van anderen. Dit bemoeilijkt het realiseren daarvan.",
    compensation: "Je compenseert door steeds te moeten afstemmen op wat anderen doen.",
    example: "'Als ik overleg en in contact blijf met mijn klanten, weet ik wat er op lange termijn aan zit te komen qua opdrachten, veranderingen, mutaties. Oh, ze gaan groeien, of nee, ze gaan afstoten.' Daardoor kun je ook veel soorten klanten aan.",
    hulpvraag: "Hoe overlegt u met anderen? Hoe belangrijk is overleg? Voorbeeld?",
    schakelvraag: "Hoe kan ik mijn droom afstemmen op die van jou?",
    dirkWords: "Op lange termijn gevoel voor richting: de mensen met harmonietalent. Als ik overleg en in contact blijf met mijn klanten, dan weet ik wat er op lange termijn aan zit te komen qua opdrachten, veranderingen, mutaties. Net zoals Jezus de bediening van Johannes de Doper wilde ondergaan, zo wil iemand met harmonietalent ook ondergaan wat een ander te bieden heeft.",
  },
  {
    number: 22,
    slug: "rotatie",
    name: "Rotatie",
    code: "A8",
    column: "Werkproces",
    quote: "Ik hou graag het tempo erin bij mijn denken, doen en laten",
    description: "Het rotatietalent brengt de omgeving in beweging en houdt graag vaart en tempo in de dingen. Het werkt en denkt snel en kan een doorslaggevende rol spelen waar snelheid telt. Mensen met dit talent kunnen moeilijk stilzitten en worden ongeduldig als het te traag gaat of als ze moeten wachten. Wie langzamer werkt, wordt door hen al gauw als traag ervaren.",
    definition: "Rotatietalent brengt anderen en zichzelf snel in beweging. Natuurlijke aanleg en motivatie om in een vrij hoog tempo te denken en te handelen. Voorziet in de behoefte van anderen om een snelle reactie te krijgen, aan energie en aan iemand die inzet toont voor hen.",
    skills: "werktempo, servicegerichtheid, energiek, leergierigheid, inzet tonen. Ook: Besluitvaardig, Commercieel inzicht.",
    blindSpot: "Je vergeet je verlangens in beweging te brengen. Je vermijdt dat diepere verlangens een rol gaan spelen in wat je dagelijks doet. Hierdoor komen ze niet in beweging en blijven ze onzichtbaar voor jezelf en anderen.",
    compensation: "Je compenseert door steeds in beweging te moeten zijn.",
    example: "Snel praten, snel denken. Ongeduldig als je in de rij moet staan wachten: 'ja, kan het niet wat sneller, en die logistieken zitten maar te babbelen, ja, hallo'.",
    hulpvraag: "Hoe hoog is uw werktempo normaal? Waarom?",
    schakelvraag: "Hoe kan ik mijn verlangens volgens jou meer in beweging brengen?",
    dirkWords: "Rotatietalent richt zich op het in beweging brengen van haar omgeving. Mannen aan de slag, zweetje, knallo knallo. Daarom houdt het van een zekere vaart in dingen — snelheid. Het brengt mensen in beweging, kan een doorslaggevende rol spelen. Kijk maar naar de McDrive.",
  },
  {
    number: 23,
    slug: "exploitatie",
    name: "Exploitatie",
    code: "B8",
    column: "Zekerheid",
    quote: "Ik ben best competitief aangelegd en ga graag ergens voor",
    description: "Het exploitatietalent ziet mogelijkheden en wil die ook daadwerkelijk benutten. Waar een ander snel één kopje koffie inschenkt, merkt dit talent op dat er ook glazen staan die meteen gevuld kunnen worden. Het is erop gericht beschikbare middelen en kansen optimaal te gebruiken. Het hoort bij de 'drijftalenten' die op zichzelf al een sterke drive aan iemands leven geven.",
    definition: "Exploitatietalent ziet en benut relevante kansen en mogelijkheden voor groei. Natuurlijke aanleg en motivatie om kansen te zien en deze aan te grijpen voor mezelf en anderen. Voorziet in de behoefte van anderen aan iemand die gedreven is en voor ze tot het gaatje gaat.",
    skills: "doorzettingsvermogen, energie, ambitie hebben, besluitvaardigheid, slagvaardig handelen. Ook: Ambitieus, Argumenteren, Assertiviteit, Betrokkenheid, Commercieel inzicht, Doelen stellen, Durf, Initiatief.",
    blindSpot: "Je vergeet kansen te benutten die bij jou passen. Je benut niet alle kansen die bij jou passen. Hierdoor mis je kansen om nog meer ervaring op te doen met waar jij zo goed in bent.",
    compensation: "Je compenseert door alle kansen te moeten benutten.",
    example: "Koffie inschenken: 'mag ik die glazen daar ook benutten?' Och joh, dat je dat ziet — ja, ja, doe daar ook maar koffie in.",
    hulpvraag: "Doet of deed u aan sport? Wilt u dan altijd winnen? Hoe erg is verlies?",
    schakelvraag: "Welke kansen laat ik liggen?",
    dirkWords: "Ik kan heel snel een kopje koffie inschenken, dan ben ik snel. Maar exploitatietalent zegt: ja, maar Dirk, er zijn ook glazen, mag ik daar ook koffie in doen — dan kan ik ook benutten. Iemand die wil de mogelijkheden die hij ziet benutten.",
  },
  {
    number: 24,
    slug: "export",
    name: "Export",
    code: "C8",
    column: "Bestemming",
    quote: "Ik hou van diepgang en ik daag mezelf en anderen graag uit in allerlei situaties",
    description: "Het exporttalent gaat nog een stap verder in het zoeken en benutten van mogelijkheden dan exploitatie en kijkt steeds naar de volgende kans om iets in te zetten. Het is sterk gedreven en geeft, samen met de andere drijftalenten, een grote energie en stuwkracht aan iemands handelen. Die gedrevenheid kan zo sterk zijn dat iemand zich in golven helemaal geeft en daarna weer flink moet uitrusten. Het blijft uitkijken naar nieuwe toepassingen en bestemmingen voor wat er is.",
    definition: "Exporttalent levert prestatie in uitdagende omstandigheden. Natuurlijke aanleg en motivatie om in lastige situaties te kunnen presteren. Voorziet in de behoefte van anderen om uitgedaagd te worden, geinspireerd en geprikkeld om grenzen te verleggen.",
    skills: "ondernemen, prikkelen/uitdagen, daadkracht, doorzettingsvermogen, initiatief nemen. Ook: Ambitieus, Commercieel inzicht, Durf, Initiatief.",
    blindSpot: "Je vergeet de uitdaging van jouw unieke betekenis op te pakken. Je gaat de uitdaging die je droom met zich meebrengt uit de weg. Dit belemmert de realisatie daarvan.",
    compensation: "Je compenseert door anderen te moeten uitdagen en prikkelen.",
    example: "Koffie buiten in de plantenbakken gooien — een speels voorbeeld om te laten zien hoe exporttalent de stap nog verder zet dan exploitatietalent.",
    hulpvraag: "Houdt u van veel uitdaging? Wat gebeurt er als u uitdaging mist?",
    schakelvraag: "Hoe zou jij de uitdaging die mijn droom met zich meebrengt oppakken?",
    dirkWords: "Wat doet iemand nou met exporttalent? Die zegt: weet je, buiten staan plantenbakken, mogen we daar koffie in gooien. Zie je, die gaat nog weer een stap verder. Een speels voorbeeldje, maar dan kun je het toch even los van elkaar knippen — het zijn alle drie drijftalenten.",
  },
  {
    number: 25,
    slug: "geven",
    name: "Geven",
    code: "A9",
    column: "Werkproces",
    quote: "Ik verlies de bigger picture niet uit het oog en behoud graag het overzicht",
    description: "Het geeftalent is in staat veel te geven en te investeren zonder meteen een direct rendement of resultaat te eisen. Het ziet de contouren van iets nieuws en doet graag mee aan ontwikkelingen waar pas later iets uitkomt — handig bij nieuwe producten en markten die tijd vragen. Dirk verbindt het met het manna-principe: vasthouden bederft, terwijl er steeds opnieuw mag worden ontvangen. Wie het weinig heeft, is eerder een spaarder of verzamelaar die moeilijk dingen kan loslaten.",
    definition: "Geeftalent geeft tijd en energie zonder direct zichtbaar resultaat. Natuurlijke aanleg en motivatie om tijd en energie te (blijven) steken in iets zonder direct resultaat. Voorziet in de behoefte van anderen om iets nieuws in ontwikkeling te brengen omdat het stimuleert om tijd en aandacht te blijven geven. Geeftalent creeert 'tijd'.",
    skills: "verbindend, contactueel, luistervaardigheid, communicatief, collegialiteit. Ook: Anticiperen/Helicopterview, Conflict hanteren, Creativiteit, Delegeren, Innovativiteit. Lage score Geeftalent: Aandacht voor details.",
    blindSpot: "Je vergeet tijd en energie te steken in je diepere verlangens. Je geeft geen aandacht en tijd aan diepere verlangens waardoor deze onduidelijk blijven. Onduidelijk voor jezelf maar ook voor anderen.",
    compensation: "Je compenseert door te moeten blijven geven aan iets nieuws.",
    example: "Bedrijven die nieuwe producten ontwikkelen of nieuwe markten bewerken: dat vraagt investering, tijd voordat je iets ziet, en sommige producten mislukken ook. Mensen met veel geeftalent zijn in staat veel te geven zonder direct rendement.",
    hulpvraag: "Werkt u graag met details of alleen de grote lijnen? Geef een voorbeeld?",
    schakelvraag: "Hoe kan ik meer tijd en energie steken in diepere verlangens die ik heb?",
    dirkWords: "Mensen met geeftalent zijn ook in staat om heel veel te geven zonder een direct resultaat te moeten zien, zonder direct rendement op te eisen. Het ziet de contouren, wil meedoen om nieuwe dingen te ontwikkelen waar geen direct rendement uitkomt. Eigenlijk het manna-principe: God geeft manna voor elke dag. Bewaar het niet, want morgen heb je nieuw manna.",
  },
  {
    number: 26,
    slug: "bestuur",
    name: "Bestuur",
    code: "B9",
    column: "Zekerheid",
    quote: "Ik ben graag doelgericht bezig en weet hoe we concreet van A naar B moeten komen",
    description: "Het bestuurstalent stelt realistische doelen en maakt ze concreet, haalbaar, meetbaar en navolgbaar voor anderen. Het helpt om jezelf en anderen stap voor stap ergens naartoe te coachen en te sturen, met tussendoelen onderweg. Te hoge doelen ontmoedigen en te lage doelen zijn niet spannend genoeg; dit talent vindt de juiste maat. Zo helpt het om een bestemming of plan daadwerkelijk te realiseren in plaats van het te laten verzanden.",
    definition: "Bestuurtalent vertaalt ambities in concrete, realistische en meetbare doelen. Natuurlijke aanleg en motivatie om concrete doelen te stellen en te halen. Voorziet in de behoefte van anderen om ambities concreet te kunnen vertalen naar een stappenplan en een duidelijk doel voor ogen.",
    skills: "aansturen, voorzitten, rationeel denken, doelmatig werken, organiseren. Ook: Aanpassingsvermogen, Doelen stellen.",
    blindSpot: "Je vergeet concrete, haalbare en meetbare doelen te stellen. Je vertaalt je intenties niet in concrete, haalbare en meetbare stapjes. Dit belemmert het realiseren van je intenties.",
    compensation: "Je compenseert door doelen te moeten stellen en deze moeten bereiken.",
    example: "Rick Warren en het doelgericht / purpose-driven werken. Joshua 1 vers 8: zult ge op uw wegen uw doelen bereiken.",
    hulpvraag: "Bent u van nature doelgericht? Geef eens een voorbeeld?",
    schakelvraag: "Hoe kan ik dit vertalen in concrete, haalbare en meetbare stapjes?",
    dirkWords: "Realistische doelen stellen, concreet maken, haalbaar maken, meetbaar maken, ook navolgbaar maken voor anderen. Mensen met bestuurtalent kunnen zichzelf coachen, maar ook anderen daarbij helpen. Te hoge doelen — raak ontmoedigd, haken af, komt niks meer van terecht. Te lage doelen — niet spannend genoeg, haken ook af.",
  },
  {
    number: 27,
    slug: "scope",
    name: "Scope",
    code: "C9",
    column: "Bestemming",
    quote: "Ik hou van afwisseling en sta graag open voor nieuwe en andere dingen",
    description: "Het scopetalent bepaalt hoe breed iemand zijn omgeving gelijktijdig kan waarnemen. Bij een brede scope neem je veel signalen tegelijk waar en zie je snel het verband daartussen; bij een smalle, gerichte scope kijk je als door een tunnel en werk je zeer geconcentreerd. Een gerichte scope maakt het makkelijker je af te sluiten van de omgeving, maar moeilijker om alle losse signalen te integreren en hun samenhang te zien. Zo bepaalt dit talent of iemand vooral overzicht heeft of juist diepe focus.",
    definition: "Scopetalent zoekt en integreert veranderingen in de omgeving. Natuurlijke aanleg en motivatie om te innoveren en andere en nieuwe zaken uit te proberen en te integreren. Voorziet in de behoefte van anderen aan verandering en vernieuwing en het weten te benutten en te integreren.",
    skills: "out-of-the-box denken, anticiperen, nieuwsgierigheid, aanpassingsvermogen, creativiteit. Ook: Adviseren, Anticiperen, Diversiteit hanteren, Innovativiteit.",
    blindSpot: "Je vergeet jouw droom te integreren in die van anderen. Je integreert je droom niet in de activiteiten van anderen. Dit belemmert de realisatie van je droom.",
    compensation: "Je compenseert door steeds bij nieuwe dingen betrokken moeten zijn.",
    example: "Een echtpaar dat we testten — allebei niet zoveel scopetalent. Ze hadden een zoontje dat op een soort autisme leek; ze moesten precies in zijn gezicht zitten, op die plek, helemaal precies: 'ja, nu hebben we contact, nu kunnen we even uitwisselen.' Een heel gerichte scope.",
    hulpvraag: "Houdt u van variatie in uw werk? Was dat vroeger ook al zo? Voorbeeld?",
    schakelvraag: "Hoe kan ik mijn droom integreren in die van jou of wat jij aan het doen bent?",
    dirkWords: "Stel dat je een hele brede scope hebt, dan kun je als het ware gelijktijdig waarnemen, je ziet ook heel snel het verband daartussen. Mensen met een gerichte scope kunnen zich heel geconcentreerd werken, kunnen zich makkelijker afsluiten van de omgeving. Als je met ze spreekt, kijken ze als door een tunnel naar je toe — een heel geconcentreerde energiebaan. Maar ze hebben veel minder vermogen om de samenhang te zien.",
  },
];

const en: Talent[] = [
  {
    number: 1,
    slug: "analyse",
    name: "Analysis",
    code: "A1",
    column: "Work process",
    description: "The analysis talent (which Dirk also calls the 'knowledge production' talent) seeks out the core of a problem instead of merely fighting the symptoms. Just as you cut an apple in half to see its core, this talent reveals what is really going on. It turns raw data into meaningful information and analysis, and so meets the need for a solution that truly cuts to the heart of the matter. Whoever lacks it stays on the surface and solves problems through costly trial and error.",
    definition: "The analysis talent gets to the essence fast. A natural aptitude and motivation to quickly and easily get to the core of something. It meets others' need to know what an issue is really about at its core.",
    blindSpot: "You forget to get to the core of your own need. When you don't get to the heart of what you need, you can't properly judge whether something helps you, and you keep putting off decisions about yourself.",
    compensation: "You compensate by having to analyse everything all the time.",
    example: "Controllers who provide management information; marketing managers who analyse market data into sound advice; scientists who systematically study (parts of) creation and turn it into meaningful analysis.",
  },
  {
    number: 2,
    slug: "formulering",
    name: "Formulation",
    code: "B1",
    column: "Certainty",
    description: "The formulation talent (also the 'knowledge formulation' talent) conveys analysed knowledge in the other person's language, so they can make it their own. It tailors the message to the recipient — finance people, the shop floor or major clients each get their own translation. This is how the first trust arises: the other person feels 'yes, that is exactly what I meant'. Those who have it strongly can adapt so smoothly that it sometimes comes across as slick.",
    definition: "The formulation talent expresses wishes and intentions clearly and precisely. A natural aptitude and motivation to put thoughts, wishes or intentions into fitting, precise words. It meets others' need to have their own thoughts and feelings sharply worded, to be understood, and to be spoken to in their own 'language'.",
    blindSpot: "You forget to put your own longings into words. When you don't word your longings well, you can't make them your own or share them — so others don't know what you want.",
    compensation: "You compensate by having to put every longing into words.",
    example: "You present market information differently to finance people than to the team running production. You tell large clients things differently than standard users of your products. Advertising.",
  },
  {
    number: 3,
    slug: "investering",
    name: "Investment",
    code: "C1",
    column: "Destiny",
    description: "The investment talent (also the 'knowledge investment' talent) recognises patterns in the market and extends them into the future, so it can as it were predict developments. This lets someone sense when a product needs replacing or which research is already needed now. The same feel for patterns also works in people's lives, when gauging someone's destiny. It inspires others to invest in the right things and is geared towards responsible growth.",
    definition: "The investment talent sees through and taps into patterns in its surroundings. A natural aptitude and motivation to see, understand and act on a pattern. It meets others' need to discover what is unique and their own, and to develop it.",
    blindSpot: "You forget to see the pattern in your experience and its meaning. Without seeing a pattern or trend in your knowledge, experience and talents, you don't always invest in exactly where your strength and special value lie.",
    compensation: "You compensate by always having to see a pattern in something.",
    example: "Marketing directors who recognise market patterns: 'we may need to replace that product soon — you can see the trends; let's start research now for a new product in eighteen months.' Professional investors — not everyone who invests has this talent. Also someone who saw the pattern in the lives of new hires — 'do this one, don't do that one' — and was proven right time and again.",
  },
  {
    number: 4,
    slug: "onderscheiding",
    name: "Discernment",
    code: "A2",
    column: "Work process",
    description: "The discernment talent immediately sees, in the here and now, which means are relevant to solve a problem, without endlessly laying out all available knowledge. It makes people decisive and to the point: they see at once what is needed and act on it. In a meeting they keep agenda items neatly apart. Whoever lacks it mixes points up or tackles things less purposefully.",
    definition: "The discernment talent quickly distinguishes what is and isn't relevant. A natural aptitude and motivation to tell, fast and easily, what matters in a situation. It meets others' need to focus on relevant things and on real solutions rather than symptoms.",
    blindSpot: "You forget to establish what is relevant for your own need. When you don't know what's relevant for you, you keep postponing the choices that would meet that need.",
    compensation: "You compensate by only reacting when something seems relevant.",
    example: "Someone walks into a room where everyone is struggling with the coffee pots, sizes it up in a second and a half, sorts it out, and everyone has coffee. In meetings: a person with discernment keeps the agenda cleanly on point C, while those without keep dragging B back in or pulling D forward.",
  },
  {
    number: 5,
    slug: "inleving",
    name: "Empathy",
    code: "B2",
    column: "Certainty",
    description: "The empathy talent fully puts itself in the other person's world of experience to understand how they feel about something, and tunes the environment to that. Only once you know how someone experiences things can you convey your knowledge and experience well; this also builds trust. People feel heard and can share everything. Those with strong empathy can, however, carry the other's burden home with them and must sometimes consciously shake it off.",
    definition: "The empathy talent easily enters others' world of experience. A natural aptitude and motivation to be quickly and easily drawn into how others experience things. It meets others' need for someone who can put themselves in their situation, offer a listening ear, and bring the right understanding.",
    blindSpot: "You forget to empathise with yourself. When you don't pause to feel how you experience something inside, you can't match your longing to what's really in you, and it doesn't lead to action.",
    compensation: "You compensate by only ever having to listen to others.",
    example: "People in therapeutic roles: social workers, some psychologists. They can carry the burden home: 'I really have to shake it off, pull myself out of the other person's world.' Or pitching a product to a care institution with too many commercial terms — 'we're not that commercial here'.",
  },
  {
    number: 6,
    slug: "combinatie",
    name: "Combination",
    code: "C2",
    column: "Destiny",
    description: "The combination talent has an enormous reservoir of ideas and links them to someone's identity and destiny, not just to the situation or the person. It produces an almost automatic stream of possibilities to let that unique plan come into its own. This sometimes brings up ideas that lie far from conventional thinking. It makes someone inventive and creative in devising what fits a given purpose.",
    definition: "The combination talent brings out what is unique in something or someone. A natural aptitude and motivation to let the unique come into its own. It meets others' need for ideas, solutions and innovations that are tailored and fit a unique identity.",
    blindSpot: "You forget to let your own uniqueness come into its own. By avoiding the ideas that could bring out your uniqueness, others don't get a clear view of your special value.",
    compensation: "You compensate by constantly having to come up with new ideas.",
    example: "Einstein. In hiring: you want a flexible, inventive or creative person. 'Yes, but they do need some structure too, Dirk.' A combination of talents — not one extreme.",
  },
  {
    number: 7,
    slug: "routine",
    name: "Routine",
    code: "A3",
    column: "Work process",
    description: "The routine talent gives the natural aptitude and motivation to keep going on a chosen path until the result becomes visible. It provides perseverance and discipline in carrying out a chosen strategy. Those who have it strongly can, however, also cling too long to an old approach and find it hard to switch. Others who lack this talent are quickly seen as undisciplined or impatient.",
    definition: "The routine talent perseveres in a specific way of working. A natural aptitude and motivation to work in routines that deliver stable quality. It meets others' need to keep going and hold on to a successful method, effective processes and stable output.",
    blindSpot: "You forget to build routines that meet your own needs. Without routines that address what you need, your self-care suffers.",
    compensation: "You compensate by having to keep going with your routines.",
    example: "A director of a fishing fleet with extremely high routine talent (you don't usually see it that high in managers); McDonald's staff performing the same routine flawlessly each time; prayer: persevering until results come.",
  },
  {
    number: 8,
    slug: "argumentatie",
    name: "Argumentation",
    code: "B3",
    column: "Certainty",
    description: "The argumentation talent motivates and persuades people with arguments about why a certain method or routine is needed. It makes clear why something must happen in a particular way, whether towards employees or clients. It is aimed mainly at persuasion in the short term. The danger is that someone uses their persuasive power to manipulate others or rope them into their own agenda.",
    definition: "The argumentation talent reasons out and defends the will to do something. A natural aptitude and motivation to reason things through and influence the surroundings. It meets others' need for the right arguments, to be persuaded and moved.",
    blindSpot: "You forget to convince yourself to want something. When you don't give yourself motives and arguments to want something, your longing isn't turned into a will and stays in the background.",
    compensation: "You compensate by having to convince others of something.",
    example: "A McDonald's employee: 'couldn't we make these rolls differently? I brought my own from home, you could serve those too.' That's killing for a franchise — you have to convince people why the routines must be followed.",
  },
  {
    number: 9,
    slug: "uitleg",
    name: "Explanation",
    code: "C3",
    column: "Destiny",
    description: "The explanation talent (which Dirk calls the 'teacher' talent) is about conveying knowledge or a method flawlessly, so that people know exactly what to do. Just as lesson material passes through the teacher into the class: one mistake at the front is passed on wrongly thirty times, which is why this talent cares deeply about integrity and long-term quality. Those who have it identify with their task and are therefore extra sensitive to criticism. A new question is left to 'circle around' from all sides before a well-considered response comes.",
    definition: "The explanation talent carefully thinks through possible consequences. A natural aptitude and motivation to anticipate scenarios and prevent mistakes. It meets others' need for careful analysis and preparation aimed at avoiding risks.",
    blindSpot: "You forget to work on your dream methodically. Without a planned approach to develop your uniqueness, realising your unique purpose becomes harder.",
    compensation: "You compensate by rigidly sticking to your plan.",
    example: "A teacher who instructs, uses examples and convinces students why the material matters. Production staff getting a new process line — lots of explanation, training and repetition to ensure it's carried out as intended.",
  },
  {
    number: 10,
    slug: "helpen",
    name: "Helping",
    code: "A4",
    column: "Work process",
    description: "The helping talent (formerly the 'service' talent) gladly and capably provides assistance across a wide variety of questions. It waits until someone asks for help and then steps in personally — not passing it on, but rolling up its own sleeves. It is an important pillar of an organisation's service orientation: the client calls, we answer. Those who have little of it help only within their own field and leave the rest to someone else.",
    definition: "The helping talent responds alertly to signals for help in its surroundings. A natural aptitude and motivation to respond to others' calls for help. It meets others' need to be helped further along.",
    blindSpot: "You forget to establish your own wishes clearly. You give no attention to your personal preferences — the ways of doing things that fit your personality.",
    compensation: "You compensate by having to respond to everyone else's requests for help.",
    example: "A company's phone: 'when people call, how readily are they helped?' It's a key pillar of an organisation's value system: you call, we answer.",
  },
  {
    number: 11,
    slug: "signaleren",
    name: "Signalling",
    code: "B4",
    column: "Certainty",
    description: "The signalling talent (which Dirk calls the 'caring' or 'compassion' talent) picks up signals of need early and anticipates them, often before the other person has even asked. It has a feel for timing in the medium term: you call someone just when they were thinking of you too. Instead of carrying out the task itself, this talent brings in the right person to make it happen. It makes people feel helped in an alert and attentive way.",
    definition: "The signalling talent responds alertly to signals of need around it. A natural aptitude and motivation to be sensitive to signals in my surroundings and react to them alertly. It meets others' need for a response at the right moment.",
    blindSpot: "You forget to respond to your own signals of need. By ignoring them, you don't translate what you want into a decision or initiative.",
    compensation: "You compensate by having to respond to everyone else's signals of need.",
    example: "'I'll give that group another call to see how things are going.' Or with coffee: 'we're short here, I'll call and make sure it's brought — I've taken care of it; I won't carry coffee myself, but I'll see it gets done by bringing someone else in.'",
  },
  {
    number: 12,
    slug: "etaleren",
    name: "Displaying",
    code: "C4",
    column: "Destiny",
    description: "The displaying talent focuses on how attractively an organisation or offering presents itself in the market. It creates an inviting image through means such as flyers, brochures and websites, so that people are naturally drawn in. Together with helping and signalling it forms a pillar of a company's value system. A good balance means the attractive presentation is in proportion to actually helping and picking up on needs.",
    definition: "The displaying talent profiles itself attractively to its surroundings. A natural aptitude and motivation to draw attention, attractively, to what is unique about something or someone. It meets others' need to identify with, and to see an appealing (re)presentation of, something or someone.",
    blindSpot: "You forget to make your unique value visible. By avoiding letting your value show too much, others don't know what you have to offer.",
    compensation: "You compensate by always having to be in the foreground.",
    example: "A company with a quarter-million budget for flyers, brochures and websites — that's displaying talent. Sometimes there's imbalance: 'we help if they call but don't pick up on needs that alertly — yet we do spend a quarter million on brochures and websites.'",
  },
  {
    number: 13,
    slug: "vertrouwen",
    name: "Trust",
    code: "A5",
    column: "Work process",
    description: "The trust talent (which Dirk calls the 'source' talent) dares to deploy people and involve them in the work, because it trusts that they are capable — even before everything has been proven. Like a shepherd leading his sheep into an unfamiliar pasture, it dares to undertake things with confidence. This gives people room to develop and to use their talents. Those who have it strongly can come across as naive; those who lack it are more distrustful and hold back to see how things unfold.",
    definition: "The trust talent puts others' talent, knowledge and experience to work. A natural aptitude and motivation to involve the people around me. It meets others' need for the chance, the room and the trust to be themselves, show themselves and develop.",
    blindSpot: "You forget to trust that your own wishes are achievable. When you don't believe your wishes can be realised, it's hard to take the steps that turn them into action.",
    compensation: "You compensate by having to keep trusting that everything will work out.",
    example: "A contact of Dirk's with almost 100% 'source' talent felt called to North Korea — no visa, no passport, just a credit card — and on arrival simply said 'I'm here to help your country, come with me.' Also: a manager who places someone without a diploma on a team to learn marketing anyway.",
  },
  {
    number: 14,
    slug: "contact",
    name: "Contact",
    code: "B5",
    column: "Certainty",
    description: "The contact talent constantly seeks contact with people and therefore knows well what is going on among them. By talking and consulting a lot it discovers what is in people, so the right person can be placed on the right task. Dirk compares it to a battery: with little contact talent it is drained after a few hours and someone needs to withdraw. Those who have a lot of it can, in others' eyes, sometimes talk too much.",
    definition: "The contact talent is in continuous interaction with its surroundings. A natural aptitude and motivation to be connected to my environment. It meets others' need to be encouraged to 'talk things through' and stay connected. (Note: the sharing has a function — it's not about small talk for its own sake.)",
    blindSpot: "You forget to stay in contact with yourself. Without inner dialogue you lose track of what is really going on inside you.",
    compensation: "You compensate by always having to be in contact with others.",
    example: "Dirk compares it to a battery: with little contact talent it's drained after a few hours and you need to withdraw; with a lot of it, others may feel you talk too much. Constant consulting reveals what's in people, so the right person lands on the right task.",
  },
  {
    number: 15,
    slug: "corrigeren",
    name: "Correction",
    code: "C5",
    column: "Destiny",
    description: "The correction talent is strongly focused on facts and reminds others of them, so they can be steered or trained. A correction based on facts ('you are half an hour late to every meeting') lands, whereas one based on feeling does not. It is needed to keep deploying people well and to deepen relationships. Dirk describes it as antennae tuned more to facts than to mood and emotion.",
    definition: "The correction talent corrects subjective impressions with objective facts. A natural aptitude and motivation to work from the facts rather than an emotional impression. It meets others' need to be pointed to the factual side of things, especially when emotions run high.",
    blindSpot: "You forget to remind others of your unique meaning. When you don't remind people of what makes your contribution special, you're not used to your full value.",
    compensation: "You compensate by having to keep correcting others.",
    example: "'You don't function well at the office because you keep wearing the wrong tie' — that doesn't land, it's not a fact. But 'you're half an hour late to every meeting we schedule' — that's a fact we can measure together, so I have a point.",
  },
  {
    number: 16,
    slug: "doorbraak",
    name: "Breakthrough",
    code: "A6",
    column: "Work process",
    description: "The breakthrough talent (which Dirk calls the 'absorb', 'fight' or 'combat' talent) focuses on breaking through barriers and blockages, so the workflow can continue and work does not pile up. It refuses to be held up: if someone is briefly away, they are called at once so others do not grind to a halt. It can take a lot of knocks and keeps pushing until the job is done. This also makes a team stronger, even if it sometimes earns a few 'yellow cards'.",
    definition: "The breakthrough talent absorbs blows and breaks through barriers to win. A natural aptitude and motivation to push on, take the hits, or add an extra push. It meets others' need for room to, together, give it that bit extra.",
    blindSpot: "You forget to clear the barriers blocking your wishes. When it comes to your own wishes you let yourself be stopped too easily by unexpected obstacles, which makes them hard to realise.",
    compensation: "You compensate by having to absorb everything there is to absorb.",
    example: "Footballer Edgar Davids; also a team where Jan is briefly away — 'no, we have to push on now, call his mobile, otherwise the work piles up and five people sit idle for half an hour.' And when a client wants something extra at the last minute: let's put in an extra hour and get the job done.",
  },
  {
    number: 17,
    slug: "beheersen",
    name: "Control",
    code: "B6",
    column: "Certainty",
    description: "The control talent intervenes in the medium term as soon as the agreed quality standard threatens not to be met. It sets out in advance which standards the result must meet and keeps an eye on whether everyone is on schedule. Dirk describes a kind of automatic clock or alarm in the head that goes off when something threatens to drift off course. The intervention can sometimes come across as dominant, but it prevents the joint outcome from falling short.",
    definition: "The control talent sets the bar, guards it, and steps in when things drift. A natural aptitude and motivation to set and guard a certain quality or standard. It meets others' need to take themselves and others seriously, to stand for something and protect it.",
    blindSpot: "You forget to set clear (quality) standards in advance. When you don't define what your performance must meet, you do either too much or too little.",
    compensation: "You compensate by having to check (quality) standards in others.",
    example: "A team where a client collects the product at 5pm, so everything must be done by 4. It's almost 3 and Pete was just having coffee — so you step in. 'Sorry, sorry, but we do want… — maybe I'm coming across as dominant now.'",
  },
  {
    number: 18,
    slug: "vertalen",
    name: "Translation",
    code: "C6",
    column: "Destiny",
    description: "The translation talent explains things with examples and instruction, so that another person understands exactly how something should be carried out. It turns knowledge or a method into clear, accessible directions — in a learning situation it makes the material concrete and manageable. It comes strongly to the fore when people have to master a new method or new machines and need a lot of explanation and repetition. In this way it ensures that something is actually done as intended.",
    definition: "The translation talent simplifies and translates complexity through simple instruction. A natural aptitude and motivation to make things accessible for myself and others. It meets others' need to make matters simple and accessible.",
    blindSpot: "You forget to tell others how they can make use of you. When you don't make clear how your unique value is best used, it stays underused.",
    compensation: "You compensate by having to keep instructing others.",
    example: "A teacher who says: 'I explain a few things, use some examples, give instruction — I have translation talent.' That's how children actually come to read the book.",
  },
  {
    number: 19,
    slug: "route",
    name: "Route",
    code: "A7",
    column: "Work process",
    description: "The route talent gives an automatic feel for the right direction and course in the here and now. People with this talent like to pioneer, prefer to discover things for themselves, and struggle with rules and manuals. They come across as independent and authentic and care strongly about what is real and original. As a result they can be hard to manage and may already be living in the future in their minds while physically present.",
    definition: "The route talent explores, sees and sets the right direction for itself. A natural aptitude and motivation to independently pioneer the right route for myself and others. It meets others' need to receive direction while being inspired in their own independence and expressiveness.",
    blindSpot: "You forget to express your deeper longings. Without giving them expression, it's hard to determine the right direction in which those longings get room.",
    compensation: "You compensate by having to do everything on your own.",
    example: "People who come across strongly in job interviews because of their originality and authenticity; cowboy-like types who operate independently; planning in the here and now: how do I plan for five seconds from now?",
  },
  {
    number: 20,
    slug: "structuur",
    name: "Structure",
    code: "B7",
    column: "Certainty",
    description: "The structure talent holds on to an agreed structure and has a strong feel for efficiency in the medium term. It points out that constantly deviating from agreements undermines all efficiency, and it likes a transparent, accessible approach. Clients appreciate that things run efficiently and predictably. The downside is that others sometimes find it inflexible or rigid, because it struggles to compromise on this point.",
    definition: "The structure talent brings structure and order to its surroundings. A natural aptitude and motivation to bring overview, order and structure to my environment. It meets others' need for someone available who brings structure and overview with an eye on efficiency.",
    blindSpot: "You forget to gain systematic experience with yourself. Without systematically experiencing your talents, you never get a clear view of all that is potentially in you.",
    compensation: "You compensate by having to stick to a fixed structure.",
    example: "'But we agreed, didn't we? It's efficient to do it this way — and now you're deviating again? How can that be?'",
  },
  {
    number: 21,
    slug: "harmonie",
    name: "Harmony",
    code: "C7",
    column: "Destiny",
    description: "The harmony talent stays in consultation and contact with others and therefore senses, in the long term, which direction is coming. By tuning in it knows what is changing — growth, divestment or new assignments — and it can handle many different people and clients. At its core is the willingness to undergo and take in what another has to offer. Those who have little of it find that someone with a lot of harmony talent wants to consult too much.",
    definition: "The harmony talent continuously seeks balance with its surroundings. A natural aptitude and motivation to seek and guard balance in my environment, for myself and others. It meets others' need to be taken into account and involved through attunement and sounding-out.",
    blindSpot: "You forget to attune your value to that of others. When you don't attune your dream to others', realising it becomes harder.",
    compensation: "You compensate by always having to attune to what others are doing.",
    example: "'By consulting and staying in contact with my clients, I know what's coming long-term — new assignments, changes. Oh, they'll grow; or no, they'll divest.' That's how you can handle many kinds of clients.",
  },
  {
    number: 22,
    slug: "rotatie",
    name: "Rotation",
    code: "A8",
    column: "Work process",
    description: "The rotation talent sets its surroundings in motion and likes to keep up pace and tempo. It works and thinks quickly and can play a decisive role where speed matters. People with this talent find it hard to sit still and become impatient when things go too slowly or when they have to wait. Those who work more slowly are soon seen by them as sluggish.",
    definition: "The rotation talent quickly sets others and itself in motion. A natural aptitude and motivation to think and act at a fairly high pace. It meets others' need for a quick response, for energy, and for someone who shows commitment to them.",
    blindSpot: "You forget to set your own longings in motion. By avoiding letting deeper longings play a role in your daily life, they never get moving and stay invisible to yourself and others.",
    compensation: "You compensate by always having to be in motion.",
    example: "Talking fast, thinking fast. Impatient when you have to wait in line: 'can't it go a bit quicker, and the logistics people just keep chatting — hello?'",
  },
  {
    number: 23,
    slug: "exploitatie",
    name: "Exploitation",
    code: "B8",
    column: "Certainty",
    description: "The exploitation talent sees possibilities and wants to actually make use of them. Where someone else quickly pours a single cup of coffee, this talent notices that there are also glasses standing ready to be filled at once. It is geared towards making optimal use of available means and opportunities. It belongs to the 'drive talents' that in themselves already give a strong drive to someone's life.",
    definition: "The exploitation talent sees and uses relevant opportunities for growth. A natural aptitude and motivation to spot opportunities and seize them for myself and others. It meets others' need for someone driven who goes all the way for them.",
    blindSpot: "You forget to use the opportunities that suit you. When you don't take all the chances that fit you, you miss out on gaining more experience in what you're good at.",
    compensation: "You compensate by having to seize every opportunity.",
    example: "Pouring coffee: 'may I use those glasses there too?' Oh, good that you spotted them — yes, fill those with coffee as well.",
  },
  {
    number: 24,
    slug: "export",
    name: "Export",
    code: "C8",
    column: "Destiny",
    description: "The export talent goes one step further in seeking and using possibilities than exploitation, always looking for the next opportunity to put something to use. It is strongly driven and, together with the other drive talents, gives great energy and momentum to someone's actions. That drive can be so strong that someone gives everything in waves and then has to rest considerably afterwards. It keeps looking out for new applications and destinations for what is available.",
    definition: "The export talent performs under challenging conditions. A natural aptitude and motivation to perform in difficult situations. It meets others' need to be challenged, inspired and provoked to push boundaries.",
    blindSpot: "You forget to take up the challenge of your unique meaning. By avoiding the challenge your dream brings, you hinder its realisation.",
    compensation: "You compensate by having to challenge and provoke others.",
    example: "Throwing coffee into the outdoor plant pots — a playful image for how export talent takes the step even further than exploitation talent.",
  },
  {
    number: 25,
    slug: "geven",
    name: "Giving",
    code: "A9",
    column: "Work process",
    description: "The giving talent is able to give and invest a great deal without immediately demanding a direct return or result. It sees the outlines of something new and likes to take part in developments that only pay off later — useful for new products and markets that take time. Dirk links it to the manna principle: hoarding spoils it, while there is always something new to receive. Those who have little of it are more of a saver or collector who finds it hard to let things go.",
    definition: "The giving talent invests time and energy without immediate visible results. A natural aptitude and motivation to keep putting time and energy into something without instant results. It meets others' need to bring something new into development. The giving talent 'creates time'.",
    blindSpot: "You forget to put time and energy into your own deeper longings. Without giving them attention and time, they stay unclear — to yourself and to others.",
    compensation: "You compensate by having to keep giving to something new.",
    example: "Companies developing new products or new markets: it takes investment and time before you see anything, and some products fail. People with strong giving talent can give a lot without an immediate return.",
  },
  {
    number: 26,
    slug: "bestuur",
    name: "Governance",
    code: "B9",
    column: "Certainty",
    description: "The governance talent sets realistic goals and makes them concrete, achievable, measurable and traceable for others. It helps to coach and steer yourself and others step by step towards something, with milestones along the way. Goals that are too high discourage and goals that are too low are not exciting enough; this talent finds the right measure. In this way it helps to actually realise a destiny or plan instead of letting it fizzle out.",
    definition: "The governance talent turns ambitions into concrete, realistic, measurable goals. A natural aptitude and motivation to set and reach concrete goals. It meets others' need to translate ambitions into a step plan with a clear goal in sight.",
    blindSpot: "You forget to set concrete, achievable and measurable goals. When you don't translate your intentions into concrete steps, realising them becomes hard.",
    compensation: "You compensate by having to set goals and reach them.",
    example: "Rick Warren and purpose-driven work. Joshua 1:8: then you will make your way prosperous and achieve your goals.",
  },
  {
    number: 27,
    slug: "scope",
    name: "Scope",
    code: "C9",
    column: "Destiny",
    description: "The scope talent determines how broadly someone can perceive their surroundings simultaneously. With a broad scope you take in many signals at once and quickly see the connection between them; with a narrow, focused scope you look as if through a tunnel and work with great concentration. A focused scope makes it easier to shut out the environment, but harder to integrate all the separate signals and see how they hang together. In this way this talent determines whether someone mainly has overview or rather deep focus.",
    definition: "The scope talent seeks and integrates change in its surroundings. A natural aptitude and motivation to innovate, try new things and integrate them. It meets others' need for change and renewal, and for knowing how to use and integrate it.",
    blindSpot: "You forget to integrate your dream into that of others. When you don't weave your dream into others' activities, you hinder its realisation.",
    compensation: "You compensate by always having to be involved in new things.",
    example: "A couple we tested — both with little scope talent. They had a son who seemed somewhat autistic; they had to sit precisely in his line of sight, exactly there: 'yes, now we have contact, now we can exchange.' A very narrow, focused scope.",
  },
];

export function getTalents(locale: Locale): Talent[] {
  return locale === "nl" ? nl : en;
}

export function getTalent(locale: Locale, slug: string): Talent | undefined {
  return getTalents(locale).find((t) => t.slug === slug);
}
