// Cleaned, readable transcripts of Dirk van der Schaaf's "talenten uitgelegd"
// videos, keyed by YouTube id. Source: Notta auto-transcripts, de-fillered and
// lightly condensed. Dutch (the videos are in Dutch).

export const transcripts: Record<string, string[]> = {
  // Deel 1 — Analyse, Formulering & Investering
  HxijseJ4734: [
    `Allereerst: een talent heeft veel kanten en het benut een bron in de onderneming. Het voorziet in een bepaalde behoefte, namelijk een oplossing die hout snijdt. Want als je niet de kern van het probleem oplost, dan is de oplossing ook niet goed en heb je er niets aan. Een talent geeft ook iets van God weer, van Gods unieke karakter. Hij heeft het probleem van de mensheid goed geanalyseerd: het probleem was de zonde, en daarom kwam ook de oplossing, zijn Zoon. Dat is consequent: dit is het probleem, en ik heb ook de oplossing.`,
    `Belangrijk is dat een talent bijdraagt aan een aantal competenties. Het geeft je een verlangen, een motivatie om iets te willen. Iemand met kennisproductietalent vindt het leuk om te analyseren en zoekt een baan waarin hij dat kwijt kan. Hij heeft ook de capaciteit, de aanleg, om het te kunnen. Maar het draagt ook bij aan teamcompetenties die je nodig hebt om als medewerker in een team samen te werken.`,
    `Het kennisproductietalent teken ik wel eens als een ijsberg. Het topje zie je: dat zijn de symptomen van het probleem. Maar hoe de ijsberg er onder water uitziet, daar verschillen we vaak over van mening. Iemand met dit talent zegt: laten we het water laten weglopen, zodat we samen kunnen zien hoe die ijsberg eruitziet. Dan bestrijden we geen symptomen, maar tillen we de echte oorzaak boven water. Of denk aan een appel: van buiten zie je alleen het steeltje, maar snijd je hem doormidden, dan zie je het klokhuis en de pitjes. Het legt iets bloot.`,
    `Eigenlijk neem je ruwe data en door die te analyseren maak je er zinvolle informatie van. Die stap van ruwe data naar informatie en analyse, dat is kennisproductietalent. Het produceert kennis: het geeft managementinformatie, of een zinvol marketingadvies uit marktgegevens. Daarom heb ik voor de naam kennisproductie gekozen, want 'analytische aanleg' dekt het niet; er zit meer achter. In de wetenschap onderzoeken we ook systematisch Gods schepping en maken er een zinvolle analyse van.`,
  ],
  // Deel 2 — Onderscheiding, Inleving & Combinatie
  "-Wpc2pxAopc": [
    `Bij het kennisinvesteringstalent gaat het om het herkennen van patronen. Stel je ziet behang met een bloemetje, een steeltje, weer een bloemetje. Trek je dat eraf, dan kun je toch voorspellen hoe het patroon zich doorzet. Zo werkt het ook in de markt: als je het patroon ziet, kun je aangeven welke kant het opgaat. Zie je dat patroon niet, dan is het interessant om te kijken hoe dat talent in je managementteam aanwezig is.`,
    `We hadden iemand getest die in de informatica werkte, maar meer de mensenkant op wilde. Hij zag heel makkelijk het patroon in de levens van mensen: als er iemand werd aangenomen, voorspelde hij of het wat zou worden. Het klopte vaak, maar hij was zich er niet van bewust dat dit zijn kennisinvesteringstalent was. Voor hem was het een bevestiging dat hij meer met mensen moest doen.`,
    `Zo gebruiken wij het ook: het patroon in iemands leven doortrekken naar de toekomst, dat noemen we iemands bestemming. Bij beleggers zie je dat ook. Soms is dit talent zo verweven met iemands bestemming dat het leven bijna geen zin meer lijkt te hebben als ze het niet meer kunnen inzetten. Het mes snijdt dan diep in het hout.`,
    `Elk talent heeft ook een geestelijke spiegel; hier is dat de gave van het geven. Denk aan Barnabas, die geld aan de voeten van de apostelen legde en investeringsbeslissingen nam in 'de aandelen van het evangelie'. Het stak iedereen aan. Dat is de functie van het talent: het steekt anderen aan en helpt om in het juiste te investeren.`,
    `Deze drie talenten — kennisproductie, formulering en investering — produceren samen knowhow. Maar dan kom je iemand tegen met een probleem. Geef je dan al je kennis van A tot Z? Dat is onhandig. Iemand met onderscheidingstalent weet meteen: waar gaat het om, en welk middel lost dit op? Daarom zijn zij in het hier en nu heel slagvaardig en to the point. Bij inlevingstalent gaat het niet om welke middelen relevant zijn, maar om wat past bij de beleving van die persoon.`,
  ],
  // Deel 3 — Routine, Argumentatie & Uitleg
  Trknfhqip6M: [
    `Routinetalent is de natuurlijke aanleg en motivatie om op een ingeslagen weg door te gaan. We hebben besloten een strategie uit te voeren, dus we gaan door, net zolang tot het resultaat zichtbaar wordt. Iemand die na één dag stopt en zegt 'het werkt niet', gaat kort door de bocht. Je kunt enorm doorzetten, maar ook te veel: een oude strategie blijven volgen omdat je nu eenmaal van je routine houdt. In combinatie met angst kan er zelfs dwangmatig gedrag uit voortkomen.`,
    `Ik kende een directeur van een vissersvloot met heel veel routinetalent; het leek of de locomotief steeds harder ging. Maar na een paar jaar kon hij niet makkelijk omschakelen naar iets anders, dat was zijn beperking. Zijn hobby was de elfstedentocht rijden: 200 kilometer dezelfde slag, dat paste precies bij zijn karakter.`,
    `Een mooie strategie met routines moet je wel aan mensen kunnen uitleggen en hen motiveren waaróm ze die uitvoeren. Dat is de functie van het argumentatietalent. Naar een klant toe leg je uit waarom we eerst een functieanalyse doen, dan een competentieprofiel maken, dan testen en pas daarna adviseren. Zo overtuig je met argumenten. Het gevaar is dat iemand die graag argumenteert anderen voor zijn karretje gaat spannen en gaat manipuleren.`,
    `Maar overtuigd zijn is nog niet hetzelfde als weten wat je moet doen. Daarvoor is het docenttalent nodig: uitleggen. Bij McDonald's moet je een handeling binnen elf seconden verrichten; daar leggen ze de techniek zelfs uit op een eigen Hamburger University. Toen een concurrent een handeling een paar seconden sneller deed, paste McDonald's dat aan en steeg het marktaandeel weer.`,
    `De essentie van docenttalent: de lesstof gaat als het ware dóór de docent de klas in. Maakt hij één fout, dan gaat het bij dertig leerlingen fout. Daarom zijn deze mensen heel integer en willen ze foutloos werken. Ze identificeren zich sterk met hun functie, dus kritiek op hun werk voelt als een pijl recht in hun lichaam; ze zijn er veel gevoeliger voor. Nieuwe informatie laten ze eerst dagenlang ronddraaien in een soort kwaliteitslaboratorium voordat ze reageren. Veel mensen noemen dit ten onrechte faalangst, maar het is een talent dat gericht is op kwaliteit op de lange termijn.`,
  ],
  // Deel 4 — Helpen, Signaleren & Etaleren
  C2Lb66TenXk: [
    `Als je in drie minuten in kaart wilt brengen hoe een onderneming werkt, kun je een paar vragen stellen. Eén: als mensen bellen, hoe graag wordt er dan geholpen? Twee: wordt er ook alert op behoeftesignalen gereageerd? En drie: hoe aantrekkelijk presenteer je jezelf in de markt? Vaak zie je onbalans: men helpt wel als klanten bellen, maar pakt behoeftesignalen niet alert op, terwijl er wel veel geld aan folders en websites wordt uitgegeven. Met talentkennis zie je dat snel.`,
    `Dat is de essentie van helptalent. Iemand met helptalent kan in een veelsoortigheid van vragen assistentie verlenen en heeft daar ook verstand van of is er ontvankelijk voor. Wie weinig helptalent heeft, zegt eerder: ik help wel, maar alleen waar ik goed in ben, en de rest moet een ander doen.`,
    `Daarnaast is er het ontfermtalent (signaleren). Dat lijkt op helpen, maar het is iets anders. Helptalent wacht tot de klant belt; ontfermtalent zegt: ik zal die club eens bellen om te kijken hoe het gaat. Heel vaak hoor je dan: goh, toevallig, je belt precies op het goede moment. Dat is een gevoel voor timing op de middellange termijn; je anticipeert ergens op.`,
    `Met ontfermtalent hangt samen hoeveel informatie iemand nodig heeft om een conclusie te trekken. Sommigen hebben heel weinig nodig en anticiperen snel. Anderen zeggen: ik heb veel informatie nodig, en terwijl ze nadenken komt er weer een stukje binnen, waardoor ze eigenlijk nooit een conclusie trekken. Die mensen hebben moeite met initiatief nemen en knopen doorhakken. Denk aan een manager met stapels op zijn bureau waarover besloten moet worden — terwijl zijn functie juist snelle beslissingen vraagt.`,
    `Het verschil zit ook in het zelf doen. Met ontfermtalent zeg ik: hier is te weinig koffie, ik bel even en zorg dat het gebracht wordt — ik schakel iemand in. Met helptalent zeg ik: ik ga nu zélf goede koffie voor jullie zetten. En heb ik helptalent maar geen tijd, en iemand komt me toch helpen terwijl ik nee moet zeggen, dan vind ik dat oprecht jammer; ik zit ermee dat ik niet kan helpen.`,
  ],
  // Deel 5 — Vertrouwen, Contact & Corrigeren
  "1FzXpb0ycpc": [
    `Als er een opdracht uitgevoerd moet worden, is brontalent (vertrouwen) handig. Als je mensen niet vertrouwt dat ze iets kunnen, durf je ze ook niet zomaar in te zetten. Brontalent heeft dus het effect dat mensen merken: ze geloven in mij, ze durven mij die opdracht te geven, ook al heb ik dat diploma nog niet. Zo worden mensen ingezet, betrokken en ontwikkelen ze hun talenten. Mensen met veel brontalent kunnen naïef overkomen op anderen die het niet hebben, want zonder brontalent ben je eerder wantrouwend en kijk je de kat uit de boom. In managementteams kan dat botsen.`,
    `Ik zie er een herder bij die rustig met zijn schaapjes een onbekende weide intrekt: hier groeit vast ook lekker gras, let's go. Iemand die met vertrouwen durft te ondernemen. De gave van het geloof is niet hetzelfde als brontalent, maar je gebruikt het wel om uit te leggen hoe brontalent in het natuurlijke werkt.`,
    `Je kunt mensen inzetten, maar je moet in contact blijven met wat er in ze leeft: wie kan ik het beste waar inzetten? Dat is contacttalent. Iemand die geregeld bij je zit te praten en daardoor goed op de hoogte is van wat er speelt, en zo mensen met de juiste talenten op de juiste opdracht zet. Soms praten ze te veel. Ik gebruik wel eens het beeld van een batterij: 90% is het maximum, 10% het minimum. Begin je om 9 uur en is je contactbatterij om 11 uur al leeg, dan ga je 's avonds geen mensen meer uitnodigen om bij te praten.`,
    `Om mensen te blijven inzetten heb je ook correctietalent nodig. Wie het heeft, is heel feitelijk en herinnert anderen aan feiten. Corrigeer je op gevoel — 'je hebt de verkeerde das aan' — dan landt het niet. Zeg je 'je komt elke meeting een half uur te laat', dan heb je een feit, want dat kunnen we samen meten. We hebben allemaal antennes op ons hoofd; sommigen zijn op feiten gericht (correctietalent), hun partner vaak meer op de sfeer en emotie.`,
  ],
  // Deel 6 — Doorbraak, Beheersen, Vertalen & Route
  ksvZHr3KS9E: [
    `Incasseertalent, het knoktalent (doorbraak), richt zich op het doorbreken van barrières en blokkades in de omgeving. Deze mensen willen zorgen dat de workflow doorgaat en laten zich niet ophouden. 'Iemand is er even niet, bel hem pas over een half uur' — nee, we moeten nu door, want anders kunnen vijf mensen een half uur niets doen. Ze gaan ook door als het al over tijd is en een klant nog iets extra's wil: we zetten er een uurtje tegenaan zodat de klus afkomt.`,
    `Mensen met veel vechttalent zoeken situaties op waarin ze kunnen strijden; ze kunnen zich overladen met werk om lekker af te zien. Denk aan een fel spelende profvoetballer die op het middenveld agressief de bal verovert en bijna ongeloofwaardig snelle sprintjes maakt. Zulke strijdlust kan een heel team hechter en sterker maken; het kost soms een gele kaart, maar het stak anderen aan.`,
    `Organiseren op de korte termijn is zorgen dat het werk doorgaat. Organiseren op de middellange termijn — beheerstalent — is van tevoren aangeven aan welke kwaliteitsnormen de uitkomst moet voldoen: de een doet dit, de ander dat, en om 4 uur is het klaar. Maar het is al bijna 3 uur en er wordt nog koffie gedronken — dan grijp je in, ook al kom je dominant over, want anders haalt het resultaat de afgesproken norm niet. Deze mensen hebben een soort automatisch wekkertje in hun hoofd dat aanslaat als iets uit de pas dreigt te lopen.`,
    `Om als team goed te werken moeten we elkaar duidelijke instructies geven: hoe moet je mij gebruiken, wat mag je van mij verwachten als we elkaar de bal toespelen? Korte termijn: barrières opruimen en incasseren. Middellange termijn: ingrijpen als iets dreigt af te wijken. Lange termijn: heldere instructies geven. Is een trainer vaag in zijn instructies, dan weet het team op het veld niet welk spel het moet spelen, ontstaat er verdeeldheid en is het teamwork weg.`,
    `Daarna moet er iets worden uitgevoerd, en komen het plannen en leidinggeven in beeld. Hoe plan je in het hier en nu, wat gebeurt er over vijf seconden? Daarom speelt het routetalent ook in het hier en nu een belangrijke rol: het geeft automatisch gevoel voor richting en de juiste koers.`,
  ],
};

export function getTranscript(youtubeId: string): string[] | undefined {
  return transcripts[youtubeId];
}
